// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
// Plugin-agnostic: every type is internal and lives in this plugin's own namespace, so several
// plugins can each embed their own copy (even inside one assembly) without colliding.
using System;
using System.Globalization;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    /// <summary>
    /// A brand accent: the two-color gradient used by every accent surface (primary buttons, the active tab
    /// pill, the switch track, checkboxes, the status-card border) plus the three hero-banner stops. Colors
    /// are given per skin because the light skin needs deeper tones to keep contrast on white.
    /// Presets: paw (violet to pink, PawEncrypt's own), ocean, sunset, mint, berry, aurora, grape.
    /// Custom: <see cref="FromHex"/> or <see cref="Parse"/>("#RRGGBB,#RRGGBB") derive everything else.
    /// </summary>
    internal sealed class PawAccent
    {
        internal static readonly string[] PresetIds = { "paw", "ocean", "sunset", "mint", "berry", "aurora", "grape" };

        internal readonly string Id;
        /// <summary>Gradient start/end on the dark skin (A = left, B = right).</summary>
        internal readonly Color DarkA, DarkB;
        /// <summary>Gradient start/end on the light skin.</summary>
        internal readonly Color LightA, LightB;
        /// <summary>Accent-tinted text (links, chips, highlights) on the dark skin.</summary>
        internal readonly Color DarkTextA, DarkTextB;
        /// <summary>Accent-tinted text on the light skin.</summary>
        internal readonly Color LightTextA, LightTextB;
        /// <summary>Hero banner stops: deep (left) - mid - end (right). The banner looks the same on both skins.</summary>
        internal readonly Color Banner0, Banner1, Banner2;

        private PawAccent(string id, Color darkA, Color darkB, Color lightA, Color lightB, Color darkTextA, Color darkTextB,
            Color lightTextA, Color lightTextB, Color banner0, Color banner1, Color banner2)
        {
            Id = id;
            DarkA = darkA;
            DarkB = darkB;
            LightA = lightA;
            LightB = lightB;
            DarkTextA = darkTextA;
            DarkTextB = darkTextB;
            LightTextA = lightTextA;
            LightTextB = lightTextB;
            Banner0 = banner0;
            Banner1 = banner1;
            Banner2 = banner2;
        }

        // ---- Presets (Tailwind 500/600 for fills, 300 for dark-skin text, 700 for light-skin text) ----------
        /// <summary>PawEncrypt's violet to pink - the reference look.</summary>
        internal static readonly PawAccent Paw = new PawAccent("paw",
            Hex(0x8B5CF6), Hex(0xEC4899), Hex(0x7C3AED), Hex(0xDB2777),
            Hex(0xC4B5FD), Hex(0xF9A8D4), Hex(0x6D28D9), Hex(0xBE185D),
            Hex(0x5427CC), Hex(0x8B35E3), Hex(0xE2458E));

        /// <summary>Blue to cyan - calm, technical (build/bundle/export tools).</summary>
        internal static readonly PawAccent Ocean = Make("ocean", 0x3B82F6, 0x0891B2, 0x2563EB, 0x0E7490, 0x93C5FD, 0x67E8F9, 0x1D4ED8, 0x0E7490);

        /// <summary>Orange to rose - warm, energetic (creative tools, generators).</summary>
        internal static readonly PawAccent Sunset = Make("sunset", 0xEA580C, 0xE11D48, 0xC2410C, 0xBE123C, 0xFDBA74, 0xFDA4AF, 0xC2410C, 0xBE123C);

        /// <summary>Emerald to cyan - fresh, "safe" (backup/autosave/cleanup tools).</summary>
        internal static readonly PawAccent Mint = Make("mint", 0x059669, 0x0891B2, 0x047857, 0x0E7490, 0x6EE7B7, 0x67E8F9, 0x047857, 0x0E7490);

        /// <summary>Fuchsia to rose - loud and playful.</summary>
        internal static readonly PawAccent Berry = Make("berry", 0xC026D3, 0xE11D48, 0xA21CAF, 0xBE123C, 0xF0ABFC, 0xFDA4AF, 0xA21CAF, 0xBE123C);

        /// <summary>Indigo to teal - cool, "magic" (shader/material tools).</summary>
        internal static readonly PawAccent Aurora = Make("aurora", 0x6366F1, 0x0D9488, 0x4F46E5, 0x0F766E, 0xA5B4FC, 0x5EEAD4, 0x4338CA, 0x0F766E);

        /// <summary>Purple to indigo - PawEncrypt's cousin, less pink.</summary>
        internal static readonly PawAccent Grape = Make("grape", 0xA855F7, 0x6366F1, 0x9333EA, 0x4F46E5, 0xD8B4FE, 0xA5B4FC, 0x7E22CE, 0x4338CA);

        internal static PawAccent Preset(string id)
        {
            switch ((id ?? string.Empty).Trim().ToLowerInvariant())
            {
                case "ocean": return Ocean;
                case "sunset": return Sunset;
                case "mint": return Mint;
                case "berry": return Berry;
                case "aurora": return Aurora;
                case "grape": return Grape;
                default: return Paw;
            }
        }

        /// <summary>
        /// "paw" / "ocean" / ... (a preset id) or "#8B5CF6,#EC4899" (two hex colors, '#' optional).
        /// Anything unparsable falls back to <see cref="Paw"/>.
        /// </summary>
        internal static PawAccent Parse(string spec)
        {
            if (string.IsNullOrEmpty(spec)) return Paw;
            var parts = spec.Split(',');
            if (parts.Length == 2 && TryHex(parts[0], out var a) && TryHex(parts[1], out var b)) return FromHex(a, b);
            return Preset(spec);
        }

        /// <summary>Custom accent from two dark-skin colors (0xRRGGBB); light-skin, text and banner tones are derived.</summary>
        internal static PawAccent FromHex(int a, int b)
        {
            var ca = Hex(a);
            var cb = Hex(b);
            return new PawAccent("custom-" + a.ToString("X6", CultureInfo.InvariantCulture) + "-" + b.ToString("X6", CultureInfo.InvariantCulture),
                ca, cb, Deeper(ca, 0.88f, 1.05f), Deeper(cb, 0.88f, 1.05f),
                Color.Lerp(ca, Color.white, 0.5f), Color.Lerp(cb, Color.white, 0.5f),
                Deeper(ca, 0.72f, 1.15f), Deeper(cb, 0.72f, 1.15f),
                BannerDeep(ca), BannerMid(ca, cb), BannerEnd(cb));
        }

        private static PawAccent Make(string id, int darkA, int darkB, int lightA, int lightB, int textA, int textB, int lightTextA,
            int lightTextB)
        {
            var a = Hex(darkA);
            var b = Hex(darkB);
            return new PawAccent(id, a, b, Hex(lightA), Hex(lightB), Hex(textA), Hex(textB), Hex(lightTextA), Hex(lightTextB),
                BannerDeep(a), BannerMid(a, b), BannerEnd(b));
        }

        // Banner stops derived the way PawEncrypt's were picked: a deeper, more saturated A on the left (the
        // wordmark sits there, so white text keeps its contrast), a saturated A-leaning mid, a slightly deeper B.
        private static Color BannerDeep(Color a)
        {
            Color.RGBToHSV(a, out var h, out var s, out var v);
            return Color.HSVToRGB(h, Mathf.Min(1f, s * 1.28f), v * 0.83f);
        }

        private static Color BannerMid(Color a, Color b)
        {
            Color.RGBToHSV(a, out var ha, out var sa, out var va);
            Color.RGBToHSV(b, out var hb, out var sb, out var vb);
            var d = hb - ha;
            if (d > 0.5f) d -= 1f;
            if (d < -0.5f) d += 1f;
            var h = Mathf.Repeat(ha + d * 0.3f, 1f);
            return Color.HSVToRGB(h, Mathf.Min(1f, Mathf.Max(sa, sb) * 1.1f), Mathf.Max(va, vb) * 0.9f);
        }

        private static Color BannerEnd(Color b)
        {
            Color.RGBToHSV(b, out var h, out var s, out var v);
            return Color.HSVToRGB(h, s, v * 0.94f);
        }

        private static Color Deeper(Color c, float value, float saturation)
        {
            Color.RGBToHSV(c, out var h, out var s, out var v);
            return Color.HSVToRGB(h, Mathf.Min(1f, s * saturation), v * value);
        }

        internal static Color Hex(int rgb) =>
            new Color(((rgb >> 16) & 0xFF) / 255f, ((rgb >> 8) & 0xFF) / 255f, (rgb & 0xFF) / 255f, 1f);

        private static bool TryHex(string s, out int value)
        {
            s = (s ?? string.Empty).Trim().TrimStart('#');
            if (s.StartsWith("0x", StringComparison.OrdinalIgnoreCase)) s = s.Substring(2);
            return int.TryParse(s, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out value) && s.Length == 6;
        }
    }

    /// <summary>
    /// Everything that makes a window "yours": wordmark, tagline, accent gradient, logo glyph and the words on
    /// the status pill. One static instance per window (see the starter window).
    /// </summary>
    internal sealed class PawBrand
    {
        /// <summary>Wordmark in the hero banner and the window tab title.</summary>
        internal string Name = "My Tool";
        /// <summary>
        /// One line under the wordmark: what the tool does, plainly. Keep it under ~48 characters: at 560px a longer line
        /// leaves no room for the tilted-glyph watermark and its sparkles, which then quietly disappear (the screenshot
        /// harness warns about it).
        /// </summary>
        internal string Tagline = string.Empty;
        /// <summary>Used when the long tagline doesn't fit (narrow windows). Null = ellipsize the long one.</summary>
        internal string TaglineShort = null;
        internal PawAccent Accent = PawAccent.Paw;
        /// <summary>Glyph id for the logo tile, tab icon, switch knob and watermark (see PawGlyphs.Ids).</summary>
        internal string Glyph = "paw";
        /// <summary>
        /// A custom logo: the inside-test for Glyph (unit square, y up; PawShapes helpers). The theme registers it with
        /// PawGlyphs.Define before anything is drawn, so no static constructor is needed. Null = Glyph is a built-in id.
        /// Preview it without Unity: python tools/glyph_preview.py --src "&lt;plugin&gt;/Editor".
        /// </summary>
        internal Func<float, float, bool> GlyphShape = null;
        /// <summary>
        /// Status pill words (uppercase reads best). PillOffShort is used below 390px. For a tool without an on/off
        /// switch, IsActive can mean "ready" (READY / NO MATERIAL / IDLE).
        /// </summary>
        internal string PillOn = "ACTIVE";
        internal string PillOff = "PAUSED";
        internal string PillOffShort = "OFF";
        internal string PillOnTooltip = null;
        internal string PillOffTooltip = null;
        /// <summary>Soft tilted-glyph watermark + sparkles between the wordmark and the pill.</summary>
        internal bool Watermark = true;
        /// <summary>Tooltip on the editor tab.</summary>
        internal string TitleTooltip = null;
    }
}
