// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
using System;
using System.Reflection;
using UnityEditor;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    /// <summary>
    /// "Is the control named X focused?" without GUI.GetNameOfFocusedControl's per-call string allocation: the
    /// name is looked up again only when keyboard focus moves to another control (or the last lookup found no
    /// name yet). One instance per window (PawWindow.Focus).
    /// </summary>
    internal sealed class PawFocus
    {
        private int _id;
        private string _name;

        internal bool Is(string controlName)
        {
            var id = GUIUtility.keyboardControl;
            if (id == 0)
            {
                _id = 0;
                _name = null;
                return false;
            }
            if (id != _id || string.IsNullOrEmpty(_name))
            {
                _id = id;
                _name = GUI.GetNameOfFocusedControl();
            }
            return string.Equals(_name, controlName, StringComparison.Ordinal);
        }
    }

    /// <summary>Keyboard shortcuts shared by the kit.</summary>
    internal static class PawKeys
    {
        /// <summary>Ctrl+Enter (Cmd+Enter on macOS): "apply" while typing in a multi-line field.</summary>
        internal static bool IsSubmit(Event e) =>
            e != null && e.type == EventType.KeyDown && (e.control || e.command) &&
            (e.keyCode == KeyCode.Return || e.keyCode == KeyCode.KeypadEnter);

        internal static bool IsEscape(Event e) => e != null && e.type == EventType.KeyDown && e.keyCode == KeyCode.Escape;
    }

    /// <summary>
    /// Keeps the text caret of a multi-line field visible when the field is drawn at its full text height inside a
    /// scroll view. IMGUI never scrolls an enclosing scroll view to the caret (TextEditor only moves its own
    /// scrollOffset), so arrow keys, typing past the bottom or Ctrl+End would otherwise move the caret out of sight.
    /// EditorGUI text areas edit through one shared internal TextEditor (EditorGUI.s_RecycledEditor); if a future
    /// Unity renames it, following silently does nothing.
    /// </summary>
    internal static class PawCaret
    {
        private const float Margin = 6f;
        private static readonly GUIContent Temp = new GUIContent();
        private static FieldInfo _recycledEditor;
        private static bool _lookedUp;

        /// <summary>
        /// Call on Repaint, after the scroll view has ended. <paramref name="textRect"/> is the text control's rect in
        /// the scroll view's content coordinates; view/content sizes are the scroll view's. Acts only when the caret
        /// index changed since the last call (so scrolling away with the wheel isn't undone). Returns true when
        /// <paramref name="scroll"/> changed - repaint then.
        /// </summary>
        internal static bool Follow(ref Vector2 scroll, ref int lastCaret, bool focused, Rect textRect, GUIStyle style,
            float viewWidth, float viewHeight, float contentWidth, float contentHeight)
        {
            if (!focused)
            {
                lastCaret = -1;
                return false;
            }
            var editor = RecycledEditor();
            if (editor == null || editor.controlID != GUIUtility.keyboardControl || editor.text == null) return false;
            var index = Mathf.Clamp(editor.cursorIndex, 0, editor.text.Length);
            if (index == lastCaret) return false;
            lastCaret = index;

            Temp.text = editor.text;
            var caret = style.GetCursorPixelPosition(textRect, Temp, index);
            Temp.text = null;
            var line = style.lineHeight;

            var s = scroll;
            if (caret.y - Margin < s.y) s.y = caret.y - Margin;
            else if (caret.y + line + Margin > s.y + viewHeight) s.y = caret.y + line + Margin - viewHeight;
            if (contentWidth > viewWidth + 0.5f)
            {
                if (caret.x - Margin < s.x) s.x = caret.x - 24f;
                else if (caret.x + Margin > s.x + viewWidth) s.x = caret.x + 24f - viewWidth;
            }
            s.x = Mathf.Clamp(s.x, 0f, Mathf.Max(0f, contentWidth - viewWidth));
            s.y = Mathf.Clamp(s.y, 0f, Mathf.Max(0f, contentHeight - viewHeight));
            if (s == scroll) return false;
            scroll = s;
            return true;
        }

        private static TextEditor RecycledEditor()
        {
            if (!_lookedUp)
            {
                _lookedUp = true;
                _recycledEditor = typeof(EditorGUI).GetField("s_RecycledEditor", BindingFlags.NonPublic | BindingFlags.Static);
            }
            return _recycledEditor?.GetValue(null) as TextEditor;
        }
    }

    /// <summary>
    /// 0..1 ease-out tween for on/off visuals (the status switch, the hero cross-fade). Keep one per animated
    /// thing; call Value(target) every OnGUI - it requests repaints while moving.
    /// </summary>
    internal sealed class PawTween
    {
        private readonly float _duration;
        private float _from;
        private float _to = -1f;
        private double _start;

        internal PawTween(float duration = 0.2f)
        {
            _duration = Mathf.Max(0.01f, duration);
        }

        internal float Value(bool on)
        {
            var target = on ? 1f : 0f;
            var now = EditorApplication.timeSinceStartup;
            if (_to < 0f)
            {
                _from = _to = target;
                _start = now - _duration * 4f;
            }
            if (!Mathf.Approximately(target, _to))
            {
                _from = At(now);
                _to = target;
                _start = now;
            }
            var value = At(now);
            if (!Mathf.Approximately(value, _to) && Event.current != null && Event.current.type == EventType.Repaint) HandleUtility.Repaint();
            return value;
        }

        /// <summary>Jump straight to a state (no animation) - e.g. when the harness or a reset sets it.</summary>
        internal void Snap(bool on)
        {
            _from = _to = on ? 1f : 0f;
            _start = EditorApplication.timeSinceStartup - _duration * 4f;
        }

        private float At(double now)
        {
            var p = Mathf.Clamp01((float)((now - _start) / _duration));
            p = 1f - (1f - p) * (1f - p) * (1f - p);
            return Mathf.Lerp(_from, _to, p);
        }
    }
}
