// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
using UnityEditor;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    /// <summary>
    /// Data for PawGUI.ListRow. Reuse one instance per row (or one scratch instance, refilled per row) and set the
    /// fields every OnGUI - no allocation. Only Title is required.
    /// </summary>
    internal sealed class PawRow
    {
        internal bool HasCheckbox;
        internal bool Checked;
        /// <summary>16px icon: a PawGlyphs mask (tinted with IconTint) or a built-in editor icon (IconTint alpha 0 = untinted).</summary>
        internal Texture Icon;
        internal Color IconTint;
        internal string Title;
        /// <summary>Dim 10px second line (a folder path - middle-ellipsized by default).</summary>
        internal string Subtitle;
        internal bool SubtitleMiddleEllipsis = true;
        /// <summary>Right-aligned bold 11px value (a size, a count, a time).</summary>
        internal string Trailing;
        /// <summary>Chip after the title ("IN USE", "NEW").</summary>
        internal string Chip;
        internal Color ChipColor;
        /// <summary>Bright title (selected / important) vs. secondary.</summary>
        internal bool Emphasis = true;
        /// <summary>
        /// Warning line under the subtitle: turns the row amber. "Used by " + [link icon + WarningLink] + WarningSuffix on one
        /// line, or WarningLine2 on a second line when that doesn't fit.
        /// </summary>
        internal string Warning;
        internal string WarningLink;
        internal Texture WarningLinkIcon;
        internal string WarningSuffix;
        internal string WarningLine2;
        internal string Tooltip;
        internal string LinkTooltip;

        /// <summary>Clears every field (for a scratch instance reused across rows).</summary>
        internal PawRow Reset()
        {
            HasCheckbox = Checked = false;
            Icon = null;
            IconTint = default;
            Title = Subtitle = Trailing = Chip = Warning = WarningLink = WarningSuffix = WarningLine2 = Tooltip = LinkTooltip = null;
            SubtitleMiddleEllipsis = true;
            ChipColor = default;
            WarningLinkIcon = null;
            Emphasis = true;
            return this;
        }
    }

    /// <summary>A small row action button (TreeRow). Text is dropped (icon-only) when the row is narrow.</summary>
    internal struct PawAction
    {
        internal string Text;
        internal Texture Glyph;
        internal PawButtonKind Kind;
        internal bool Enabled;
        internal string Tooltip;

        internal PawAction(string text, Texture glyph, PawButtonKind kind = PawButtonKind.Ghost, bool enabled = true, string tooltip = null)
        {
            Text = text;
            Glyph = glyph;
            Kind = kind;
            Enabled = enabled;
            Tooltip = tooltip;
        }

        internal bool IsSet => Glyph != null || !string.IsNullOrEmpty(Text);
    }

    internal static partial class PawGUI
    {
        private const float RowBlock = 44f;
        private const float RowTrailingWidth = 70f;

        // ---- List row ---------------------------------------------------------------------------------
        /// <summary>
        /// Selectable list row: [checkbox] [icon] bold title (+chip) over a dim subtitle, right-aligned trailing value,
        /// optional amber warning line with a clickable link. 44px (64/80 with a warning). Returns Main when the row
        /// was clicked (toggle Checked), Link when the warning link was clicked, Context on right-click.
        /// </summary>
        internal static PawHit ListRow(PawRow row, float width = -1f)
        {
            if (width <= 0f) width = CardWidth;
            var hasWarning = !string.IsNullOrEmpty(row.Warning);
            var oneLine = !hasWarning || WarningFitsOneLine(row, width);
            var height = !hasWarning ? RowBlock : oneLine ? 64f : 80f;
            var r = GUILayoutUtility.GetRect(0f, height, GUILayout.ExpandWidth(true), GUILayout.Height(height));

            var lead = 12f + (row.HasCheckbox ? 26f : 0f) + (row.Icon != null ? 24f : 0f);
            var x = r.x + lead;
            var warnStyle = PawTheme.Label(11, PawTheme.Warning);
            var linkStyle = PawTheme.Label(11, PawTheme.Warning, true);

            // The warning link is registered before the row so it takes the click instead of toggling the row.
            var link = default(Rect);
            var linkHover = false;
            string linkText = null;
            var result = PawHit.None;
            var hasLink = hasWarning && !string.IsNullOrEmpty(row.WarningLink);
            if (hasLink)
            {
                var iconW = row.WarningLinkIcon != null ? 17f : 0f;
                var linkX = x + 19f + Mathf.Ceil(Measure(row.Warning, warnStyle).x);
                var limit = oneLine ? r.xMax - 12f - Measure(row.WarningSuffix ?? string.Empty, warnStyle).x : r.xMax - 12f;
                var nameW = Mathf.Max(0f, limit - linkX - iconW);
                linkText = Ellipsize(row.WarningLink, linkStyle, nameW);
                link = new Rect(linkX, r.y + 41f, iconW + Mathf.Min(nameW, Mathf.Ceil(Measure(linkText, linkStyle).x)), 18f);
            }
            if (Click(hasLink ? link : Rect.zero, hasLink, row.WarningLink, out linkHover, out _)) result = PawHit.Link;
            if (Click(r, true, row.Title, out var hover, out _) && result == PawHit.None) result = PawHit.Main;
            if (ContextClick(r)) result = PawHit.Context;
            Tooltip(new Rect(r.x, r.y, r.width, RowBlock), row.Tooltip);
            if (hasLink) Tooltip(link, row.LinkTooltip);
            if (!IsRepaint) return result;

            if (hasWarning)
            {
                Fill(r, PawTheme.Alpha(PawTheme.Warning, hover && !linkHover ? 0.13f : 0.08f), TileRadius);
                Stroke(r, PawTheme.Alpha(PawTheme.Warning, 0.4f), TileRadius);
            }
            else if (hover)
            {
                Fill(r, PawTheme.SurfaceHover, TileRadius);
            }
            else if (row.HasCheckbox && row.Checked)
            {
                Fill(r, PawTheme.Alpha(PawTheme.SurfaceRaised, 0.6f), TileRadius);
            }

            // Checkbox and icon sit on the middle of the title/subtitle block; the trailing value is centered on the
            // whole row, so a warning row's extra line doesn't leave it hanging near the top.
            var mid = r.y + RowBlock / 2f;
            var ix = r.x + 12f;
            if (row.HasCheckbox)
            {
                Checkbox(new Rect(ix, mid - 8f, 16f, 16f), row.Checked, hover && !linkHover);
                ix += 26f;
            }
            if (row.Icon != null)
            {
                var tint = row.IconTint.a > 0f ? row.IconTint : Color.white;
                GUI.DrawTexture(new Rect(ix, mid - 8f, 16f, 16f), row.Icon, ScaleMode.ScaleToFit, true, 0f, tint, 0f, 0f);
            }
            var trailingW = string.IsNullOrEmpty(row.Trailing) ? 0f : RowTrailingWidth;
            if (trailingW > 0f)
            {
                GUI.Label(new Rect(r.xMax - 12f - trailingW, r.y, trailingW, r.height), row.Trailing,
                    PawTheme.Label(11, PawTheme.TextSecondary, true, TextAnchor.MiddleRight));
            }

            var textW = Mathf.Max(0f, r.xMax - 12f - trailingW - 8f - x);
            var nameStyle = PawTheme.Label(12, row.Emphasis || hasWarning ? PawTheme.Text : PawTheme.TextSecondary, true);
            var hasChip = !string.IsNullOrEmpty(row.Chip);
            var chipW = hasChip ? ChipWidth(row.Chip) : 0f;
            var name = Ellipsize(row.Title, nameStyle, Mathf.Max(0f, textW - (hasChip ? chipW + 8f : 0f)));
            var nw = Measure(name, nameStyle).x;
            var hasSub = !string.IsNullOrEmpty(row.Subtitle);
            var titleY = hasSub || hasWarning ? r.y + 5f : r.y + 13f;
            GUI.Label(new Rect(x, titleY, nw + 2f, 18f), name, nameStyle);
            if (hasChip)
            {
                var cc = row.ChipColor.a > 0f ? row.ChipColor : hasWarning ? PawTheme.Warning : PawTheme.AccentText;
                Chip(new Rect(Mathf.Round(x + nw + 8f), titleY + 1f, chipW, 16f), row.Chip, cc);
            }
            if (hasSub)
            {
                var dirStyle = PawTheme.Label(10, PawTheme.TextMuted);
                GUI.Label(new Rect(x, r.y + 23f, textW, 15f), Ellipsize(row.Subtitle, dirStyle, textW, row.SubtitleMiddleEllipsis), dirStyle);
            }

            if (hasWarning)
            {
                var y = r.y + 41f;
                Glyph(new Rect(x, y + 2f, 13f, 13f), PawGlyphs.Warn, PawTheme.Warning);
                if (hasLink)
                {
                    GUI.Label(new Rect(x + 19f, y, link.x - x - 19f + 1f, 18f), row.Warning, warnStyle);
                    var nameX = link.x;
                    if (row.WarningLinkIcon != null)
                    {
                        GUI.DrawTexture(new Rect(link.x, y + 2f, 14f, 14f), row.WarningLinkIcon, ScaleMode.ScaleToFit, true);
                        nameX += 17f;
                    }
                    GUI.Label(new Rect(nameX, y, link.xMax - nameX + 1f, 18f), linkText, linkStyle);
                    Fill(new Rect(nameX, y + 15f, link.xMax - nameX, 1f), PawTheme.Alpha(PawTheme.Warning, linkHover ? 0.9f : 0.35f));
                    if (oneLine)
                    {
                        GUI.Label(new Rect(link.xMax, y, Mathf.Max(0f, r.xMax - 12f - link.xMax), 18f), row.WarningSuffix, warnStyle);
                    }
                    else
                    {
                        GUI.Label(new Rect(x + 19f, y + 17f, Mathf.Max(0f, r.xMax - 12f - x - 19f), 18f), row.WarningLine2 ?? row.WarningSuffix, warnStyle);
                    }
                }
                else
                {
                    GUI.Label(new Rect(x + 19f, y, Mathf.Max(0f, r.xMax - 12f - x - 19f), 18f), Ellipsize(row.Warning, warnStyle, r.xMax - 12f - x - 19f), warnStyle);
                }
            }
            return result;
        }

        private static bool WarningFitsOneLine(PawRow row, float width)
        {
            if (string.IsNullOrEmpty(row.WarningLink)) return true;
            var style = PawTheme.Label(11, PawTheme.Warning);
            var linkStyle = PawTheme.Label(11, PawTheme.Warning, true);
            var lead = 12f + (row.HasCheckbox ? 26f : 0f) + (row.Icon != null ? 24f : 0f);
            var need = 19f + Measure(row.Warning, style).x + (row.WarningLinkIcon != null ? 17f : 0f) + Measure(row.WarningLink, linkStyle).x +
                       Measure(row.WarningSuffix ?? string.Empty, style).x + 2f;
            return need <= width - lead - 12f;
        }

        // ---- Group header + tree rows -----------------------------------------------------------------
        /// <summary>Initial bubble + bold name + dim summary (36px) - heads a group of TreeRows.</summary>
        internal static void GroupHeader(string initial, Color color, string title, string summary)
        {
            var r = GUILayoutUtility.GetRect(0f, 36f, GUILayout.ExpandWidth(true), GUILayout.Height(36f));
            if (!IsRepaint) return;
            var circle = new Rect(r.x, r.y + 3f, 30f, 30f);
            Initial(circle, initial, color);
            var textX = circle.xMax + 10f;
            var textW = r.xMax - textX;
            var nameStyle = PawTheme.Label(13, PawTheme.Text, true);
            GUI.Label(new Rect(textX, r.y + 1f, textW, 18f), Ellipsize(title, nameStyle, textW), nameStyle);
            GUI.Label(new Rect(textX, r.y + 19f, textW, 15f), summary, PawTheme.Label(11, PawTheme.TextMuted));
        }

        /// <summary>
        /// Row under a GroupHeader, joined to it by a tree connector (spine + elbow on the last row): title (+chip),
        /// right-aligned trailing value and up to two small action buttons (icon-only when narrow).
        /// Returns 1 or 2 for the clicked action, 0 otherwise.
        /// </summary>
        internal static int TreeRow(string title, string chip, string trailing, bool last, string tooltip, PawAction a, PawAction b)
        {
            var r = GUILayoutUtility.GetRect(0f, 38f, GUILayout.ExpandWidth(true), GUILayout.Height(38f));
            var row = new Rect(r.x + 30f, r.y + 3f, r.width - 30f, 32f);
            var compact = row.width < 340f;

            var bw = !b.IsSet ? 0f : compact ? 32f : ButtonWidth(b.Text, b.Glyph, 10f);
            var aw = !a.IsSet ? 0f : compact ? 32f : ButtonWidth(a.Text, a.Glyph, 10f);
            var bRect = new Rect(row.xMax - bw - 3f, row.center.y - 13f, bw, 26f);
            var aRect = new Rect(bRect.x - (bw > 0f ? 4f : 0f) - aw, bRect.y, aw, 26f);
            const float sizeW = 64f;
            var size = new Rect(aRect.x - 10f - sizeW, row.y, sizeW, row.height);
            var hover = Hovering(row);

            if (IsRepaint)
            {
                if (hover) Fill(row, PawTheme.Alpha(PawTheme.SurfaceHover, 0.8f), ControlRadius);
                var spine = PawTheme.BorderStrong;
                if (!last) Fill(new Rect(r.x + 14.5f, r.y - 3f, 1f, r.height + 3f), spine);
                Elbow(new Rect(r.x + 14.5f, r.y - 3f, 11f, r.height * 0.5f + 3.5f), spine, 6f);

                var x = row.x + 10f;
                var dateStyle = PawTheme.Label(12, PawTheme.Text);
                var hasChip = !string.IsNullOrEmpty(chip);
                var chipW = hasChip ? ChipWidth(chip) : 0f;
                var titleW = Mathf.Max(0f, size.x - x - (hasChip ? chipW + 8f : 0f));
                var shown = Ellipsize(title, dateStyle, titleW);
                var dw = Mathf.Min(titleW, Measure(shown, dateStyle).x);
                GUI.Label(new Rect(x, row.y, dw + 2f, row.height), shown, dateStyle);
                if (hasChip && titleW > 20f) Chip(new Rect(x + dw + 8f, row.center.y - 9f, chipW, 18f), chip, PawTheme.AccentText);
                if (!string.IsNullOrEmpty(trailing)) GUI.Label(size, trailing, PawTheme.Label(11, PawTheme.TextSecondary, true, TextAnchor.MiddleRight));
            }
            Tooltip(new Rect(row.x, row.y, Mathf.Max(0f, size.xMax - row.x), row.height), tooltip);

            var result = 0;
            if (a.IsSet && Button(aRect, compact ? string.Empty : a.Text, a.Kind, a.Enabled, a.Glyph, a.Tooltip)) result = 1;
            if (b.IsSet && Button(bRect, compact ? string.Empty : b.Text, b.Kind, b.Enabled, b.Glyph, b.Tooltip)) result = 2;
            return result;
        }

        // ---- Log rows ---------------------------------------------------------------------------------
        /// <summary>
        /// One log line: tinted round glyph + wrapped 12px text (rich text allowed - build it once, not per frame).
        /// Put inside BeginCard(PawTheme.LogCardPad); dividers are inset 32px. Returns true on right-click.
        /// </summary>
        internal static bool LogRow(Texture glyph, Color color, string text, bool rich, bool first, bool dim = false) =>
            LogRow(glyph, color, text, rich, first, dim, null);

        /// <summary>
        /// Log line with a dim 10px detail line under it (a file path, an asset): one line, middle-ellipsized when it
        /// doesn't fit (long paths never wrap mid-word), the full text in its tooltip. No rich-text colors to rebuild.
        /// </summary>
        internal static bool LogRow(Texture glyph, Color color, string text, bool rich, bool first, bool dim, string detail)
        {
            if (!first) Divider(32f);
            var row = EditorGUILayout.BeginHorizontal(PawTheme.LogRowPad);
            var icon = GUILayoutUtility.GetRect(22f, 22f, GUILayout.Width(22f), GUILayout.Height(22f));
            if (IsRepaint)
            {
                Fill(icon, PawTheme.Alpha(color, PawTheme.TintAlpha + 0.02f), 11f);
                Glyph(Inset(icon, 6f), glyph, color);
            }
            GUILayout.Space(10f);
            var style = PawTheme.Label(12, dim ? PawTheme.TextSecondary : PawTheme.Text, wrap: true, rich: rich);
            if (string.IsNullOrEmpty(detail))
            {
                GUILayout.Label(text, style);
            }
            else
            {
                EditorGUILayout.BeginVertical();
                GUILayout.Label(text, style);
                GUILayout.Space(1f);
                var d = GUILayoutUtility.GetRect(0f, 15f, GUILayout.ExpandWidth(true), GUILayout.Height(15f));
                if (IsRepaint)
                {
                    var detailStyle = PawTheme.Label(10, PawTheme.TextMuted);
                    GUI.Label(d, Ellipsize(detail, detailStyle, d.width, true), detailStyle);
                }
                Tooltip(d, detail);
                EditorGUILayout.EndVertical();
            }
            EditorGUILayout.EndHorizontal();
            return ContextClick(row);
        }

        // ---- Sticky footer ----------------------------------------------------------------------------
        /// <summary>
        /// Sticky action bar at the bottom of the window (PawWindow reserves the rect - see HasFooter/DrawFooter):
        /// soft shadow above, bold summary + dim sub line on the left, one big button on the right. Returns true on click.
        /// </summary>
        internal static bool FooterBar(Rect f, string main, string sub, Color subColor, string buttonText, PawButtonKind kind, bool enabled,
            Texture glyph = null, string tooltip = null)
        {
            if (IsRepaint)
            {
                GUI.DrawTexture(new Rect(f.x, f.y - 14f, f.width, 14f), PawTheme.FadeUpTex, ScaleMode.StretchToFill, true, 0f,
                    PawTheme.Alpha(PawTheme.ShadowColor, 0.6f), 0f, 0f);
                Fill(f, PawTheme.Surface);
                Fill(new Rect(f.x, f.y, f.width, 1f), PawTheme.Border);
            }

            var bw = Mathf.Min(170f, f.width * 0.42f);
            var button = new Rect(f.xMax - Margin - bw, f.y + 15f, bw, 34f);
            var textW = Mathf.Max(0f, button.x - 12f - Margin);
            if (IsRepaint)
            {
                var mainStyle = PawTheme.Label(13, PawTheme.Text, true);
                GUI.Label(new Rect(f.x + Margin, f.y + 13f, textW, 20f), Ellipsize(main, mainStyle, textW), mainStyle);
                var subStyle = PawTheme.Label(11, subColor.a > 0f ? subColor : PawTheme.TextSecondary);
                GUI.Label(new Rect(f.x + Margin, f.y + 33f, textW, 16f), Ellipsize(sub, subStyle, textW), subStyle);
            }
            return Button(button, buttonText, kind, enabled, glyph, enabled ? tooltip : null);
        }
    }
}
