// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
using System;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    /// <summary>A frosted round icon button in the hero banner, left of the status pill (settings, help, style menu...).</summary>
    internal sealed class PawBannerButton
    {
        /// <summary>Glyph id (PawGlyphs).</summary>
        internal string Glyph = "gear";
        internal string Tooltip = null;
        /// <summary>Called with the button rect (use it for GenericMenu.DropDown / PopupWindow.Show).</summary>
        internal Action<Rect> OnClick = null;
    }

    /// <summary>Badge shown on a tab: a count bubble (Text), red when Danger, and/or a small amber "unsaved" dot.</summary>
#pragma warning disable 0649 // assigned by window code (GetTabBadge)
    internal struct PawTabBadge
    {
        internal string Text;
        internal bool Danger;
        internal bool Dot;
        internal string Tooltip;
    }
#pragma warning restore 0649

    internal static partial class PawGUI
    {
        internal const float BannerHeight = 96f;
        internal const float TabBarY = 74f;
        internal const float TabBarHeight = 40f;

        /// <summary>
        /// The hero banner across the top of the window: brand gradient (cross-fading to slate + amber as t goes to 0),
        /// soft bokeh, frosted logo tile with the brand glyph, wordmark + tagline, tilted-glyph watermark, frosted icon
        /// buttons and the status pill. Returns the index of the clicked banner button (clickedRect = its rect) or -1.
        /// </summary>
        internal static int HeroBanner(float width, PawBrand brand, float t, string pillText, bool pillOn, string pillTooltip,
            PawBannerButton[] buttons, out Rect clickedRect)
        {
            clickedRect = default;
            var hasPill = !string.IsNullOrEmpty(pillText);
            var pillStyle = PawTheme.Label(10, Color.white, true);
            var pw = hasPill ? Mathf.Ceil(Measure(pillText, pillStyle).x) + 30f : 0f;
            var pill = new Rect(width - Margin - pw, 17f, pw, 24f);
            var controlsLeft = hasPill ? pill.x : width - Margin + 8f;
            var buttonCount = buttons?.Length ?? 0;
            var firstButtonX = controlsLeft - 8f - 24f;
            if (buttonCount > 0) controlsLeft = firstButtonX - (buttonCount - 1) * 32f;

            if (IsRepaint)
            {
                var banner = new Rect(0, 0, width, BannerHeight);
                if (t < 0.999f) GUI.DrawTexture(banner, PawTheme.BannerOffTex, ScaleMode.StretchToFill, false);
                if (t > 0.001f) GUI.DrawTexture(banner, PawTheme.BannerTex, ScaleMode.StretchToFill, true, 0f, new Color(1f, 1f, 1f, t), 0f, 0f);
                Bokeh(banner, t);

                // Wordmark geometry (the watermark sits in the gap between it and the right-hand controls).
                var logo = new Rect(Margin, 14f, 44f, 44f);
                var textX = logo.xMax + 12f;
                var textW = Mathf.Max(0f, controlsLeft - 10f - textX);
                var titleStyle = PawTheme.Label(20, Color.white, true);
                var sub = PawTheme.Label(11, new Color(1f, 1f, 1f, 0.84f));
                var tagline = brand.Tagline ?? string.Empty;
                if (!string.IsNullOrEmpty(brand.TaglineShort) && Measure(tagline, sub).x > textW) tagline = brand.TaglineShort;
                var textEnd = textX + Mathf.Min(textW, Mathf.Max(Measure(brand.Name, titleStyle).x, Measure(tagline, sub).x));

                WatermarkState = brand.Watermark ? (Watermark(textEnd, controlsLeft, t) ? 1 : 2) : 0;

                // App mark: frosted squircle with the brand glyph.
                Fill(new Rect(logo.x, logo.y + 2f, logo.width, logo.height), new Color(0.1f, 0f, 0.25f, 0.18f), 13f);
                Fill(logo, new Color(1f, 1f, 1f, 0.17f), 12f);
                Stroke(logo, new Color(1f, 1f, 1f, 0.32f), 12f);
                Glyph(Inset(logo, 9f), PawTheme.BrandGlyph, Color.white);

                // Status pill: frosted white + green dot when on, dark glass + amber ring when off.
                if (hasPill)
                {
                    if (pillOn)
                    {
                        Fill(pill, new Color(1f, 1f, 1f, 0.2f), 12f);
                        Stroke(pill, new Color(1f, 1f, 1f, 0.28f), 12f);
                    }
                    else
                    {
                        Fill(pill, new Color(0.1f, 0.06f, 0.02f, 0.42f), 12f);
                        Stroke(pill, new Color(0.99f, 0.8f, 0.3f, 0.75f), 12f);
                    }
                    var dot = new Rect(pill.x + 11f, pill.center.y - 3.5f, 7f, 7f);
                    var dotColor = pillOn ? new Color(0.53f, 0.94f, 0.67f) : new Color(0.99f, 0.8f, 0.3f);
                    Fill(Inset(dot, -2.5f), PawTheme.Alpha(dotColor, 0.3f), 6f);
                    Fill(dot, dotColor, 3.5f);
                    GUI.Label(new Rect(pill.x + 23f, pill.y, pw - 23f, pill.height), pillText,
                        pillOn ? pillStyle : PawTheme.Label(10, new Color(1f, 0.9f, 0.62f), true));
                }

                GUI.Label(new Rect(textX, 13f, textW, 28f), Ellipsize(brand.Name, titleStyle, textW), titleStyle);
                GUI.Label(new Rect(textX, 40f, textW, 18f), Ellipsize(tagline, sub, textW), sub);
            }
            if (hasPill) Tooltip(pill, pillTooltip);

            var clicked = -1;
            for (var i = 0; i < buttonCount; i++)
            {
                var b = buttons[i];
                var r = new Rect(firstButtonX - i * 32f, 17f, 24f, 24f);
                if (FrostButton(r, PawGlyphs.Get(b?.Glyph ?? "gear"), b?.Tooltip, b?.Tooltip))
                {
                    clicked = i;
                    clickedRect = r;
                }
            }
            return clicked;
        }

        /// <summary>
        /// Soft tilted-glyph watermark + sparkles, fully inside the visible banner (above the tab bar) and in the gap
        /// between the wordmark and the right-hand controls. Skipped when too tight, so the glyph always reads.
        /// </summary>
        private static bool Watermark(float textEnd, float controlsLeft, float t)
        {
            var right = controlsLeft - 24f;
            var size = Mathf.Min(62f, right - (textEnd + 22f));
            if (size < 40f) return false;

            var mark = new Rect(Mathf.Round(right - size), Mathf.Round(40f - size / 2f), size, size);
            var a = Mathf.Lerp(0.8f, 1f, t);
            var tilted = PawTheme.BrandTilted;
            Glyph(mark, tilted, new Color(1f, 1f, 1f, 0.14f * a));

            // The small secondary glyph only when it keeps clear of the tagline.
            var small = Mathf.Round(size * 0.36f);
            var smallRect = new Rect(Mathf.Round(mark.x - small - 4f), Mathf.Round(mark.yMax - small), small, small);
            if (smallRect.x >= textEnd + 24f) Glyph(smallRect, tilted, new Color(1f, 1f, 1f, 0.1f * a));

            Glyph(new Rect(mark.x - 12f, mark.y + 3f, 10f, 10f), PawGlyphs.SparkleGlyph, new Color(1f, 1f, 1f, 0.55f * a));
            Glyph(new Rect(mark.xMax - 4f, mark.yMax - 9f, 7f, 7f), PawGlyphs.SparkleGlyph, new Color(1f, 1f, 1f, 0.35f * a));
            return true;
        }

        /// <summary>A few large, very faint circles in the top-right corner, clipped to the banner.</summary>
        private static void Bokeh(Rect banner, float t)
        {
            var a = Mathf.Lerp(0.6f, 1f, t);
            var w = banner.width;
            GUI.BeginClip(banner);
            Fill(CircleRect(w - 30f, 4f, 46f), new Color(1f, 1f, 1f, 0.075f * a), 46f);
            Fill(CircleRect(w - 98f, 70f, 24f), new Color(1f, 1f, 1f, 0.06f * a), 24f);
            Fill(CircleRect(w + 8f, 72f, 34f), new Color(1f, 1f, 1f, 0.055f * a), 34f);
            GUI.EndClip();
        }

        /// <summary>
        /// Floating pill tab bar (overlaps the bottom of the banner): shadowed surface, the active tab is a gradient pill
        /// (toned down by <paramref name="mute"/> 0..1 while the tool is inactive), badges per tab. Labels that don't fit
        /// first turn their count into a dot, then ellipsize. Returns the clicked tab index or -1.
        /// </summary>
        internal static int TabBar(Rect bar, string[] labels, int current, float mute, PawTabBadge[] badges)
        {
            Shadow(bar, 12f);
            Fill(bar, PawTheme.Border, 12f);
            Fill(Inset(bar, 1f), PawTheme.Surface, 11f);

            var count = labels.Length;
            var inner = Inset(bar, 4f);
            var segW = inner.width / count;
            var clicked = -1;
            for (var i = 0; i < count; i++)
            {
                var seg = new Rect(inner.x + i * segW + (i == 0 ? 0f : 1f), inner.y, segW - (i == 0 || i == count - 1 ? 1f : 2f), inner.height);
                var badge = badges != null && i < badges.Length ? badges[i] : default;
                if (TabSegment(seg, labels[i], badge, current == i, mute)) clicked = i;
                if (!string.IsNullOrEmpty(badge.Tooltip)) Tooltip(seg, badge.Tooltip);
            }
            return clicked;
        }

        private static bool TabSegment(Rect r, string label, PawTabBadge badge, bool selected, float mute)
        {
            var clicked = Click(r, !selected, label, out var hover, out _);
            if (!IsRepaint) return clicked;

            if (selected)
            {
                Gradient(r, 9f);
                if (mute > 0.001f)
                {
                    // Toward the surface in the dark skin; toward a mid grey in the light skin, where the near-white
                    // surface would wash out the white label.
                    var toward = PawTheme.IsDark ? PawTheme.SurfaceRaised : PawTheme.TextMuted;
                    Fill(r, PawTheme.Alpha(toward, mute), 9f);
                }
                Fill(new Rect(r.x, r.y, r.width, r.height * 0.5f), new Color(1f, 1f, 1f, 0.05f), 9f);
            }
            else if (hover)
            {
                Fill(r, PawTheme.SurfaceHover, 9f);
            }

            var fg = selected ? Color.white : hover ? PawTheme.Text : PawTheme.TextSecondary;
            var style = PawTheme.Label(12, fg, true);
            var lw = Measure(label, style).x;
            var hasCount = !string.IsNullOrEmpty(badge.Text);
            var bw = hasCount ? BadgeWidth(badge.Text) : 0f;
            var dot = badge.Dot;
            var countAsDot = false;
            var room = r.width - 8f;
            if (hasCount && lw + 6f + bw + (dot ? 10f : 0f) > room)
            {
                // Too tight for the number: a colored dot keeps the signal.
                countAsDot = true;
                bw = 0f;
            }
            var gap = hasCount && !countAsDot ? 6f : 0f;
            var dw = dot || countAsDot ? 10f : 0f;
            var maxLabel = Mathf.Max(0f, room - dw - gap - bw);
            var shown = lw > maxLabel ? Ellipsize(label, style, maxLabel) : label;
            if (!ReferenceEquals(shown, label)) lw = Measure(shown, style).x;
            var x = Mathf.Round(r.center.x - (lw + dw + gap + bw) / 2f);
            GUI.Label(new Rect(x, r.y, lw + 2f, r.height), shown, style);

            if (dot || countAsDot)
            {
                // Superscript-style dot after the label: amber = unsaved edits, red/grey = a count that didn't fit.
                var d = new Rect(x + lw + 4f, Mathf.Round(r.center.y - 8f), 6f, 6f);
                var c = dot ? PawTheme.Warning : badge.Danger ? PawTheme.DangerFill : selected ? Color.white : PawTheme.TextMuted;
                Fill(Inset(d, -1.5f), selected ? new Color(1f, 1f, 1f, 0.35f) : PawTheme.Alpha(c, 0.25f), 4.5f);
                Fill(d, c, 3f);
            }
            if (hasCount && !countAsDot)
            {
                var br = new Rect(x + lw + dw + gap, Mathf.Round(r.center.y - 8f), bw, 16f);
                Badge(br, badge.Text, badge.Danger, selected);
            }
            return clicked;
        }
    }
}
