// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
using System;
using System.Collections.Generic;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    /// <summary>
    /// Signed-distance / inside-test helpers for glyph shapes. Coordinates are the unit square with y UP
    /// (0,0 = bottom-left), which is how GUI.DrawTexture shows a texture. Use them in PawGlyphs.Define.
    /// </summary>
    internal static class PawShapes
    {
        internal static float Circle(float x, float y, float cx, float cy)
        {
            var dx = x - cx;
            var dy = y - cy;
            return Mathf.Sqrt(dx * dx + dy * dy);
        }

        /// <summary>Distance from (px,py) to the segment a-b. "Seg(...) &lt; w" is a capsule stroke of half-width w.</summary>
        internal static float Seg(float px, float py, float ax, float ay, float bx, float by)
        {
            var pax = px - ax;
            var pay = py - ay;
            var bax = bx - ax;
            var bay = by - ay;
            var h = Mathf.Clamp01((pax * bax + pay * bay) / (bax * bax + bay * bay));
            var dx = pax - bax * h;
            var dy = pay - bay * h;
            return Mathf.Sqrt(dx * dx + dy * dy);
        }

        /// <summary>Signed distance to a rounded box (center, half size, corner radius). &lt; 0 = inside.</summary>
        internal static float RoundBox(float px, float py, float cx, float cy, float hx, float hy, float r)
        {
            var qx = Mathf.Abs(px - cx) - hx + r;
            var qy = Mathf.Abs(py - cy) - hy + r;
            var ox = Mathf.Max(qx, 0f);
            var oy = Mathf.Max(qy, 0f);
            return Mathf.Sqrt(ox * ox + oy * oy) + Mathf.Min(Mathf.Max(qx, qy), 0f) - r;
        }

        internal static bool Ellipse(float x, float y, float cx, float cy, float rx, float ry, float degrees)
        {
            var a = degrees * Mathf.Deg2Rad;
            var dx = x - cx;
            var dy = y - cy;
            var ux = dx * Mathf.Cos(a) + dy * Mathf.Sin(a);
            var uy = -dx * Mathf.Sin(a) + dy * Mathf.Cos(a);
            return (ux / rx) * (ux / rx) + (uy / ry) * (uy / ry) <= 1f;
        }

        /// <summary>Rotates (x,y) around the square's center (for tilted glyphs: rotate the sample point by -angle).</summary>
        internal static void Rotate(ref float x, ref float y, float degrees)
        {
            var a = degrees * Mathf.Deg2Rad;
            var dx = x - 0.5f;
            var dy = y - 0.5f;
            x = 0.5f + dx * Mathf.Cos(a) - dy * Mathf.Sin(a);
            y = 0.5f + dx * Mathf.Sin(a) + dy * Mathf.Cos(a);
        }

        /// <summary>Angle of (x,y) around (cx,cy) in degrees, 0..360, counter-clockwise from +x.</summary>
        internal static float Angle(float x, float y, float cx = 0.5f, float cy = 0.5f)
        {
            var a = Mathf.Atan2(y - cy, x - cx) * Mathf.Rad2Deg;
            return a < 0f ? a + 360f : a;
        }

        internal static bool Ring(float x, float y, float cx, float cy, float radius, float halfWidth) =>
            Mathf.Abs(Circle(x, y, cx, cy) - radius) < halfWidth;

        internal static bool InTriangle(float px, float py, float ax, float ay, float bx, float by, float cx, float cy)
        {
            var d1 = (px - bx) * (ay - by) - (ax - bx) * (py - by);
            var d2 = (px - cx) * (by - cy) - (bx - cx) * (py - cy);
            var d3 = (px - ax) * (cy - ay) - (cx - ax) * (py - ay);
            var neg = d1 < 0 || d2 < 0 || d3 < 0;
            var pos = d1 > 0 || d2 > 0 || d3 > 0;
            return !(neg && pos);
        }

        /// <summary>Even-odd point-in-polygon; pts = x0,y0,x1,y1,...</summary>
        internal static bool InPoly(float px, float py, float[] pts)
        {
            var inside = false;
            var n = pts.Length / 2;
            for (int i = 0, j = n - 1; i < n; j = i++)
            {
                float xi = pts[2 * i], yi = pts[2 * i + 1], xj = pts[2 * j], yj = pts[2 * j + 1];
                if ((yi > py) != (yj > py) && px < (xj - xi) * (py - yi) / (yj - yi) + xi) inside = !inside;
            }
            return inside;
        }

        /// <summary>Four-point sparkle (astroid) of radius r.</summary>
        internal static bool Sparkle(float x, float y, float cx, float cy, float r)
        {
            var dx = Mathf.Abs(x - cx) / r;
            var dy = Mathf.Abs(y - cy) / r;
            return Mathf.Sqrt(dx) + Mathf.Sqrt(dy) <= 1f;
        }

        /// <summary>Five-point star (outer radius R, inner radius r), one tip pointing up.</summary>
        internal static bool Star(float x, float y, float cx, float cy, float outer, float inner)
        {
            const float sector = Mathf.PI * 2f / 5f;
            var a = Mathf.Atan2(y - cy, x - cx);
            var d = Circle(x, y, cx, cy);
            var b = Mathf.Repeat(a - Mathf.PI / 2f, sector);
            if (b > sector / 2f) b = sector - b;
            var px = d * Mathf.Cos(b);
            var py = d * Mathf.Sin(b);
            var bx = inner * Mathf.Cos(sector / 2f);
            var by = inner * Mathf.Sin(sector / 2f);
            return (bx - outer) * py - by * (px - outer) >= 0f;
        }

        internal static bool Paw(float x, float y)
        {
            return Ellipse(x, y, 0.5f, 0.305f, 0.245f, 0.19f, 0f)
                   || Ellipse(x, y, 0.375f, 0.235f, 0.135f, 0.125f, 0f)
                   || Ellipse(x, y, 0.625f, 0.235f, 0.135f, 0.125f, 0f)
                   || Ellipse(x, y, 0.5f, 0.205f, 0.13f, 0.11f, 0f)
                   || Ellipse(x, y, 0.155f, 0.555f, 0.095f, 0.125f, -28f)
                   || Ellipse(x, y, 0.845f, 0.555f, 0.095f, 0.125f, 28f)
                   || Ellipse(x, y, 0.365f, 0.76f, 0.1f, 0.13f, -10f)
                   || Ellipse(x, y, 0.635f, 0.76f, 0.1f, 0.13f, 10f);
        }
    }

    /// <summary>
    /// Procedural glyph library: white alpha masks (4x4 supersampled, mipmapped) rasterized from code - no image
    /// files. Tint them with PawGUI.Glyph(rect, tex, color). Textures are created lazily on first use, cached,
    /// owned by PawTheme (destroyed on release / domain reload) and rebuilt transparently afterwards.
    /// Add your own with <see cref="Define"/> (e.g. in the window's static constructor) using PawShapes.
    /// </summary>
    internal static class PawGlyphs
    {
        internal const int Size = 48;
        internal const int LargeSize = 128;
        internal const float TiltDegrees = -20f;

        private static readonly Dictionary<string, Func<float, float, bool>> Shapes = new Dictionary<string, Func<float, float, bool>>(StringComparer.Ordinal);
        private static readonly Dictionary<string, Texture2D> Small = new Dictionary<string, Texture2D>(StringComparer.Ordinal);
        private static readonly Dictionary<string, Texture2D> Large = new Dictionary<string, Texture2D>(StringComparer.Ordinal);
        private static readonly Dictionary<string, Texture2D> Tilted = new Dictionary<string, Texture2D>(StringComparer.Ordinal);
        private static readonly HashSet<string> Warned = new HashSet<string>(StringComparer.Ordinal);
        private static readonly List<string> IdList = new List<string>();

        /// <summary>Every built-in glyph id, in gallery order.</summary>
        internal static readonly string[] BuiltinIds =
        {
            "paw", "check", "cross", "plus", "dash", "info", "letter-i", "question", "warn", "sparkle", "star", "heart",
            "search", "filter", "list", "grid", "layers", "folder", "box", "cube", "image", "palette", "material", "tag", "link",
            "external", "upload", "download", "save", "copy", "trash", "pencil", "wand", "gear", "refresh", "clock", "bell", "dice",
            "play", "pause", "stop", "lock", "unlock", "shield", "key", "eye", "bolt", "home", "sun", "moon",
            "cloud", "bug", "chevron", "chevron-down", "arrow-right",
        };

        static PawGlyphs()
        {
            RegisterBuiltins();
        }

        /// <summary>All registered ids (built-in first, then custom ones in definition order). Do not modify.</summary>
        internal static IReadOnlyList<string> Ids => IdList;

        internal static bool Has(string id) => id != null && Shapes.ContainsKey(id);

        /// <summary>The raw inside-test for a glyph (null when unknown) - e.g. to rasterize it in two colors.</summary>
        internal static Func<float, float, bool> Shape(string id) => id != null && Shapes.TryGetValue(id, out var s) ? s : null;

        /// <summary>
        /// Adds (or replaces) a glyph. <paramref name="inside"/> gets unit-square coordinates, y up, and returns
        /// whether the point is inside the shape. Keep strokes >= 0.05 half-width so they survive at 14px.
        /// </summary>
        internal static void Define(string id, Func<float, float, bool> inside)
        {
            if (string.IsNullOrEmpty(id) || inside == null) return;
            if (!Shapes.ContainsKey(id)) IdList.Add(id);
            Shapes[id] = inside;
            Forget(Small, id);
            Forget(Large, id);
            Forget(Tilted, id);
        }

        /// <summary>48px mask - icons, buttons, tiles.</summary>
        internal static Texture2D Get(string id) => Build(Small, id, Size, 0f);

        /// <summary>128px mask - logo tile, big empty states, watermark-size art.</summary>
        internal static Texture2D GetLarge(string id) => Build(Large, id, LargeSize, 0f);

        /// <summary>128px mask rotated by TiltDegrees - the hero watermark.</summary>
        internal static Texture2D GetTilted(string id) => Build(Tilted, id, LargeSize, TiltDegrees);

        // ---- Typed shortcuts (no allocation; dictionary lookups) ---------------------------------------
        internal static Texture2D PawGlyph => Get("paw");
        internal static Texture2D Check => Get("check");
        internal static Texture2D Cross => Get("cross");
        internal static Texture2D Plus => Get("plus");
        internal static Texture2D Dash => Get("dash");
        internal static Texture2D Info => Get("info");
        internal static Texture2D LetterI => Get("letter-i");
        internal static Texture2D Question => Get("question");
        internal static Texture2D Warn => Get("warn");
        internal static Texture2D SparkleGlyph => Get("sparkle");
        internal static Texture2D StarGlyph => Get("star");
        internal static Texture2D Heart => Get("heart");
        internal static Texture2D Search => Get("search");
        internal static Texture2D Filter => Get("filter");
        internal static Texture2D List => Get("list");
        internal static Texture2D Grid => Get("grid");
        internal static Texture2D Layers => Get("layers");
        internal static Texture2D Folder => Get("folder");
        internal static Texture2D Box => Get("box");
        internal static Texture2D Cube => Get("cube");
        internal static Texture2D Image => Get("image");
        internal static Texture2D Palette => Get("palette");
        internal static Texture2D Material => Get("material");
        internal static Texture2D Tag => Get("tag");
        internal static Texture2D Link => Get("link");
        internal static Texture2D External => Get("external");
        internal static Texture2D Upload => Get("upload");
        internal static Texture2D Download => Get("download");
        internal static Texture2D Save => Get("save");
        internal static Texture2D Copy => Get("copy");
        internal static Texture2D Trash => Get("trash");
        internal static Texture2D Pencil => Get("pencil");
        internal static Texture2D Wand => Get("wand");
        internal static Texture2D Gear => Get("gear");
        internal static Texture2D Refresh => Get("refresh");
        internal static Texture2D Clock => Get("clock");
        internal static Texture2D Bell => Get("bell");
        internal static Texture2D Dice => Get("dice");
        internal static Texture2D Play => Get("play");
        internal static Texture2D Pause => Get("pause");
        internal static Texture2D Stop => Get("stop");
        internal static Texture2D Lock => Get("lock");
        internal static Texture2D Unlock => Get("unlock");
        internal static Texture2D Shield => Get("shield");
        internal static Texture2D Key => Get("key");
        internal static Texture2D Eye => Get("eye");
        internal static Texture2D Bolt => Get("bolt");
        internal static Texture2D Home => Get("home");
        internal static Texture2D Sun => Get("sun");
        internal static Texture2D Moon => Get("moon");
        internal static Texture2D Cloud => Get("cloud");
        internal static Texture2D Bug => Get("bug");
        internal static Texture2D Chevron => Get("chevron");
        internal static Texture2D ChevronDown => Get("chevron-down");
        internal static Texture2D ArrowRight => Get("arrow-right");

        /// <summary>Called by PawTheme when it destroys its textures.</summary>
        internal static void ClearCache()
        {
            Small.Clear();
            Large.Clear();
            Tilted.Clear();
        }

        private static void Forget(Dictionary<string, Texture2D> cache, string id)
        {
            if (cache.TryGetValue(id, out var tex) && tex != null) UnityEngine.Object.DestroyImmediate(tex);
            cache.Remove(id);
        }

        private static Texture2D Build(Dictionary<string, Texture2D> cache, string id, int size, float degrees)
        {
            if (id == null) return null;
            if (cache.TryGetValue(id, out var tex) && tex != null) return tex;
            if (!Shapes.TryGetValue(id, out var shape))
            {
                if (Warned.Add(id)) Debug.LogWarning("PawUI: unknown glyph id '" + id + "' - showing 'question'. Known: PawGlyphs.BuiltinIds or PawGlyphs.Define.");
                if (id == "question") return null;
                return Build(cache, "question", size, degrees);
            }
            if (Mathf.Abs(degrees) > 0.01f)
            {
                var inner = shape;
                // Rotating the sample point by -20 degrees tilts the drawn glyph the way PawEncrypt's watermark leans.
                shape = (x, y) =>
                {
                    PawShapes.Rotate(ref x, ref y, degrees);
                    return inner(x, y);
                };
            }
            tex = Rasterize(size, shape, "PawUI Glyph " + id);
            cache[id] = tex;
            return tex;
        }

        /// <summary>White mask with 4x4 supersampled coverage in alpha; mipmapped so it stays smooth when drawn small.</summary>
        internal static Texture2D Rasterize(int size, Func<float, float, bool> inside, string name)
        {
            const int ss = 4;
            var tex = new Texture2D(size, size, TextureFormat.RGBA32, true)
            {
                hideFlags = HideFlags.HideAndDontSave,
                wrapMode = TextureWrapMode.Clamp,
                filterMode = FilterMode.Trilinear,
                name = name,
            };
            var px = new Color32[size * size];
            for (var y = 0; y < size; y++)
            {
                for (var x = 0; x < size; x++)
                {
                    var hits = 0;
                    for (var sy = 0; sy < ss; sy++)
                    {
                        for (var sx = 0; sx < ss; sx++)
                        {
                            var u = (x + (sx + 0.5f) / ss) / size;
                            var v = (y + (sy + 0.5f) / ss) / size;
                            if (inside(u, v)) hits++;
                        }
                    }
                    px[y * size + x] = new Color32(255, 255, 255, (byte)(255 * hits / (ss * ss)));
                }
            }
            tex.SetPixels32(px);
            tex.Apply(true, true);
            PawTheme.Own(tex);
            return tex;
        }

        // ---------------------------------------------------------------------------------------------
        private static void Add(string id, Func<float, float, bool> inside)
        {
            if (!Shapes.ContainsKey(id)) IdList.Add(id);
            Shapes[id] = inside;
        }

        private static readonly float[] BoltPoly = { 0.6f, 0.95f, 0.2f, 0.42f, 0.47f, 0.42f, 0.4f, 0.05f, 0.8f, 0.58f, 0.53f, 0.58f };
        private static readonly float[] FilterPoly = { 0.12f, 0.86f, 0.88f, 0.86f, 0.58f, 0.48f, 0.58f, 0.14f, 0.42f, 0.24f, 0.42f, 0.48f };
        private static readonly float[] TagPoly = { 0.34f, 0.08f, 0.66f, 0.08f, 0.66f, 0.66f, 0.5f, 0.9f, 0.34f, 0.66f };
        private static readonly float[] CubePts = { 0.5f, 0.92f, 0.87f, 0.71f, 0.87f, 0.29f, 0.5f, 0.08f, 0.13f, 0.29f, 0.13f, 0.71f };

        private static bool Tray(float x, float y) =>
            PawShapes.Seg(x, y, 0.16f, 0.14f, 0.84f, 0.14f) < 0.065f || PawShapes.Seg(x, y, 0.16f, 0.14f, 0.16f, 0.36f) < 0.065f ||
            PawShapes.Seg(x, y, 0.84f, 0.14f, 0.84f, 0.36f) < 0.065f;

        private static bool LockBody(float x, float y)
        {
            if (PawShapes.RoundBox(x, y, 0.5f, 0.33f, 0.31f, 0.24f, 0.07f) >= 0f) return false;
            return !(PawShapes.Circle(x, y, 0.5f, 0.37f) < 0.065f || PawShapes.Seg(x, y, 0.5f, 0.37f, 0.5f, 0.22f) < 0.035f);
        }

        private static void RegisterBuiltins()
        {
            Add("paw", PawShapes.Paw);
            Add("check", (x, y) =>
                PawShapes.Seg(x, y, 0.2f, 0.5f, 0.42f, 0.28f) < 0.085f || PawShapes.Seg(x, y, 0.42f, 0.28f, 0.81f, 0.7f) < 0.085f);
            Add("cross", (x, y) =>
                PawShapes.Seg(x, y, 0.26f, 0.26f, 0.74f, 0.74f) < 0.08f || PawShapes.Seg(x, y, 0.26f, 0.74f, 0.74f, 0.26f) < 0.08f);
            Add("plus", (x, y) =>
                PawShapes.Seg(x, y, 0.5f, 0.2f, 0.5f, 0.8f) < 0.08f || PawShapes.Seg(x, y, 0.2f, 0.5f, 0.8f, 0.5f) < 0.08f);
            Add("dash", (x, y) => PawShapes.Seg(x, y, 0.27f, 0.5f, 0.73f, 0.5f) < 0.085f);
            Add("info", (x, y) =>
            {
                var d = PawShapes.Circle(x, y, 0.5f, 0.5f);
                if (d < 0.46f && d > 0.37f) return true;
                return PawShapes.Circle(x, y, 0.5f, 0.69f) < 0.06f || PawShapes.Seg(x, y, 0.5f, 0.28f, 0.5f, 0.52f) < 0.05f;
            });
            Add("letter-i", (x, y) =>
                PawShapes.Circle(x, y, 0.5f, 0.76f) < 0.095f || PawShapes.Seg(x, y, 0.5f, 0.2f, 0.5f, 0.54f) < 0.08f);
            Add("question", (x, y) =>
            {
                var d = PawShapes.Circle(x, y, 0.5f, 0.5f);
                if (d < 0.46f && d > 0.37f) return true;
                var a = PawShapes.Angle(x, y, 0.5f, 0.6f);
                if (Mathf.Abs(PawShapes.Circle(x, y, 0.5f, 0.6f) - 0.12f) < 0.05f && !(a > 200f && a < 290f)) return true;
                return PawShapes.Seg(x, y, 0.5f, 0.48f, 0.5f, 0.42f) < 0.05f || PawShapes.Circle(x, y, 0.5f, 0.27f) < 0.055f;
            });
            Add("warn", (x, y) =>
            {
                if (!PawShapes.InTriangle(x, y, 0.5f, 0.93f, 0.04f, 0.1f, 0.96f, 0.1f)) return false;
                if (PawShapes.Seg(x, y, 0.5f, 0.42f, 0.5f, 0.67f) < 0.06f) return false;
                return PawShapes.Circle(x, y, 0.5f, 0.25f) >= 0.065f;
            });
            Add("sparkle", (x, y) => PawShapes.Sparkle(x, y, 0.5f, 0.5f, 0.48f));
            Add("star", (x, y) => PawShapes.Star(x, y, 0.5f, 0.47f, 0.46f, 0.2f));
            Add("heart", (x, y) =>
            {
                var u = (x - 0.5f) / 0.43f;
                var v = (y - 0.47f) / 0.43f;
                var k = u * u + v * v - 1f;
                return k * k * k - u * u * v * v * v <= 0f;
            });
            Add("search", (x, y) =>
            {
                var d = PawShapes.Circle(x, y, 0.43f, 0.57f);
                return (d < 0.29f && d > 0.2f) || PawShapes.Seg(x, y, 0.63f, 0.37f, 0.84f, 0.16f) < 0.07f;
            });
            Add("filter", (x, y) => PawShapes.InPoly(x, y, FilterPoly));
            Add("list", (x, y) =>
            {
                for (var i = 0; i < 3; i++)
                {
                    var cy = 0.75f - i * 0.25f;
                    if (PawShapes.Circle(x, y, 0.17f, cy) < 0.075f || PawShapes.Seg(x, y, 0.36f, cy, 0.86f, cy) < 0.06f) return true;
                }
                return false;
            });
            Add("grid", (x, y) =>
                PawShapes.RoundBox(x, y, 0.3f, 0.3f, 0.15f, 0.15f, 0.05f) < 0f || PawShapes.RoundBox(x, y, 0.7f, 0.3f, 0.15f, 0.15f, 0.05f) < 0f ||
                PawShapes.RoundBox(x, y, 0.3f, 0.7f, 0.15f, 0.15f, 0.05f) < 0f || PawShapes.RoundBox(x, y, 0.7f, 0.7f, 0.15f, 0.15f, 0.05f) < 0f);
            Add("layers", (x, y) =>
            {
                if (Mathf.Abs(x - 0.5f) / 0.4f + Mathf.Abs(y - 0.64f) / 0.2f <= 1f) return true;
                for (var i = 0; i < 2; i++)
                {
                    var c = i == 0 ? 0.46f : 0.3f;
                    var dist = Mathf.Abs(x - 0.5f) / 0.4f + Mathf.Abs(y - c) / 0.2f;
                    if (Mathf.Abs(dist - 1f) < 0.2f && y < c - 0.02f && Mathf.Abs(x - 0.5f) < 0.4f) return true;
                }
                return false;
            });
            Add("folder", (x, y) =>
                PawShapes.RoundBox(x, y, 0.5f, 0.44f, 0.42f, 0.29f, 0.08f) < 0f || PawShapes.RoundBox(x, y, 0.28f, 0.72f, 0.2f, 0.1f, 0.06f) < 0f);
            Add("box", (x, y) =>
            {
                if (PawShapes.RoundBox(x, y, 0.5f, 0.74f, 0.42f, 0.1f, 0.04f) < 0f) return true;
                if (PawShapes.RoundBox(x, y, 0.5f, 0.35f, 0.36f, 0.25f, 0.05f) >= 0f) return false;
                return PawShapes.RoundBox(x, y, 0.5f, 0.47f, 0.11f, 0.04f, 0.035f) >= 0f;
            });
            Add("cube", (x, y) =>
            {
                const float w = 0.058f;
                for (var i = 0; i < 6; i++)
                {
                    var j = (i + 1) % 6;
                    if (PawShapes.Seg(x, y, CubePts[2 * i], CubePts[2 * i + 1], CubePts[2 * j], CubePts[2 * j + 1]) < w) return true;
                }
                for (var i = 1; i < 6; i += 2)
                {
                    if (PawShapes.Seg(x, y, 0.5f, 0.5f, CubePts[2 * i], CubePts[2 * i + 1]) < w) return true;
                }
                return false;
            });
            Add("image", (x, y) =>
            {
                var frame = PawShapes.RoundBox(x, y, 0.5f, 0.5f, 0.42f, 0.36f, 0.09f);
                if (frame >= 0f) return false;
                if (frame > -0.07f) return true;
                return PawShapes.InTriangle(x, y, 0.16f, 0.2f, 0.42f, 0.56f, 0.68f, 0.2f) ||
                       PawShapes.InTriangle(x, y, 0.46f, 0.2f, 0.64f, 0.42f, 0.84f, 0.2f) || PawShapes.Circle(x, y, 0.68f, 0.64f) < 0.075f;
            });
            // Paint palette: a round board with a thumb notch and four paint wells.
            Add("palette", (x, y) =>
            {
                if (PawShapes.Circle(x, y, 0.5f, 0.5f) > 0.45f) return false;
                if (PawShapes.Circle(x, y, 0.76f, 0.24f) < 0.17f) return false;
                if (PawShapes.Circle(x, y, 0.62f, 0.37f) < 0.07f) return false;
                return !(PawShapes.Circle(x, y, 0.27f, 0.47f) < 0.075f || PawShapes.Circle(x, y, 0.35f, 0.71f) < 0.075f ||
                         PawShapes.Circle(x, y, 0.59f, 0.76f) < 0.075f || PawShapes.Circle(x, y, 0.75f, 0.6f) < 0.075f);
            });
            // Material preview ball: a sphere with a specular highlight and a shading terminator cut out.
            Add("material", (x, y) =>
            {
                if (PawShapes.Circle(x, y, 0.5f, 0.5f) > 0.44f) return false;
                if (PawShapes.Circle(x, y, 0.36f, 0.64f) < 0.095f) return false;
                var t = PawShapes.Circle(x, y, 0.27f, 0.73f);
                return t <= 0.55f || t >= 0.63f;
            });
            Add("tag", (x, y) =>
            {
                PawShapes.Rotate(ref x, ref y, 45f);
                if (PawShapes.Circle(x, y, 0.5f, 0.64f) < 0.065f) return false;
                return PawShapes.InPoly(x, y, TagPoly) || PawShapes.RoundBox(x, y, 0.5f, 0.38f, 0.16f, 0.3f, 0.06f) < 0f;
            });
            Add("link", (x, y) =>
            {
                PawShapes.Rotate(ref x, ref y, -45f);
                return Mathf.Abs(PawShapes.Seg(x, y, 0.5f, 0.2f, 0.5f, 0.42f) - 0.13f) < 0.055f ||
                       Mathf.Abs(PawShapes.Seg(x, y, 0.5f, 0.58f, 0.5f, 0.8f) - 0.13f) < 0.055f ||
                       PawShapes.Seg(x, y, 0.5f, 0.38f, 0.5f, 0.62f) < 0.055f;
            });
            // Opens outside the window: a frame open at its top-right corner with an arrow leaving through the gap.
            Add("external", (x, y) =>
            {
                var box = PawShapes.RoundBox(x, y, 0.44f, 0.44f, 0.32f, 0.32f, 0.09f);
                if (box < 0f && box > -0.075f && !(x > 0.47f && y > 0.47f)) return true;
                return PawShapes.Seg(x, y, 0.45f, 0.45f, 0.84f, 0.84f) < 0.065f || PawShapes.Seg(x, y, 0.58f, 0.86f, 0.86f, 0.86f) < 0.065f ||
                       PawShapes.Seg(x, y, 0.86f, 0.58f, 0.86f, 0.86f) < 0.065f;
            });
            Add("upload", (x, y) =>
                PawShapes.Seg(x, y, 0.5f, 0.36f, 0.5f, 0.84f) < 0.065f || PawShapes.Seg(x, y, 0.5f, 0.86f, 0.3f, 0.66f) < 0.065f ||
                PawShapes.Seg(x, y, 0.5f, 0.86f, 0.7f, 0.66f) < 0.065f || Tray(x, y));
            Add("download", (x, y) =>
                PawShapes.Seg(x, y, 0.5f, 0.86f, 0.5f, 0.38f) < 0.065f || PawShapes.Seg(x, y, 0.5f, 0.36f, 0.3f, 0.56f) < 0.065f ||
                PawShapes.Seg(x, y, 0.5f, 0.36f, 0.7f, 0.56f) < 0.065f || Tray(x, y));
            Add("save", (x, y) =>
            {
                if (PawShapes.RoundBox(x, y, 0.5f, 0.5f, 0.38f, 0.38f, 0.07f) >= 0f) return false;
                if (PawShapes.InTriangle(x, y, 0.72f, 0.9f, 0.9f, 0.9f, 0.9f, 0.72f)) return false;
                if (PawShapes.RoundBox(x, y, 0.47f, 0.73f, 0.17f, 0.1f, 0.03f) < 0f) return false;
                return PawShapes.Circle(x, y, 0.5f, 0.36f) >= 0.1f;
            });
            Add("copy", (x, y) =>
            {
                var front = PawShapes.RoundBox(x, y, 0.6f, 0.4f, 0.26f, 0.26f, 0.07f);
                if (front < 0f) return front > -0.075f;
                var back = PawShapes.RoundBox(x, y, 0.4f, 0.6f, 0.26f, 0.26f, 0.07f);
                return back < 0f && back > -0.075f && front > 0.07f;
            });
            Add("trash", (x, y) =>
            {
                if (PawShapes.RoundBox(x, y, 0.5f, 0.75f, 0.35f, 0.045f, 0.03f) < 0f) return true;
                if (PawShapes.RoundBox(x, y, 0.5f, 0.83f, 0.11f, 0.06f, 0.03f) < 0f) return true;
                if (PawShapes.RoundBox(x, y, 0.5f, 0.38f, 0.26f, 0.3f, 0.07f) >= 0f) return false;
                return !(PawShapes.RoundBox(x, y, 0.41f, 0.38f, 0.03f, 0.17f, 0.02f) < 0f || PawShapes.RoundBox(x, y, 0.59f, 0.38f, 0.03f, 0.17f, 0.02f) < 0f);
            });
            Add("pencil", (x, y) =>
            {
                PawShapes.Rotate(ref x, ref y, 45f);
                if (PawShapes.InTriangle(x, y, 0.38f, 0.28f, 0.62f, 0.28f, 0.5f, 0.06f)) return true;
                if (PawShapes.RoundBox(x, y, 0.5f, 0.56f, 0.12f, 0.28f, 0.02f) >= 0f) return false;
                return PawShapes.RoundBox(x, y, 0.5f, 0.8f, 0.12f, 0.012f, 0f) >= 0f;
            });
            Add("wand", (x, y) =>
                PawShapes.Seg(x, y, 0.16f, 0.16f, 0.6f, 0.6f) < 0.06f || PawShapes.Sparkle(x, y, 0.74f, 0.74f, 0.2f) ||
                PawShapes.Sparkle(x, y, 0.36f, 0.84f, 0.1f) || PawShapes.Sparkle(x, y, 0.86f, 0.4f, 0.09f));
            Add("gear", (x, y) =>
            {
                var d = PawShapes.Circle(x, y, 0.5f, 0.5f);
                if (d <= 0.135f) return false;
                var a = PawShapes.Angle(x, y) * Mathf.Deg2Rad;
                var t = Mathf.Clamp01((Mathf.Cos(a * 8f) - 0.05f) * 2.2f);
                return d < 0.33f + 0.12f * t;
            });
            Add("refresh", (x, y) =>
            {
                const float r0 = 0.3f;
                var a = PawShapes.Angle(x, y);
                if (Mathf.Abs(PawShapes.Circle(x, y, 0.5f, 0.5f) - r0) < 0.068f && !(a > 18f && a < 78f)) return true;
                // Arrowhead at the top end of the arc, pointing clockwise.
                var e = 78f * Mathf.Deg2Rad;
                float px = 0.5f + r0 * Mathf.Cos(e), py = 0.5f + r0 * Mathf.Sin(e);
                float tx = Mathf.Sin(e), ty = -Mathf.Cos(e), nx = Mathf.Cos(e), ny = Mathf.Sin(e);
                return PawShapes.InTriangle(x, y, px + tx * 0.2f, py + ty * 0.2f,
                    px + nx * 0.16f - tx * 0.02f, py + ny * 0.16f - ty * 0.02f, px - nx * 0.16f - tx * 0.02f, py - ny * 0.16f - ty * 0.02f);
            });
            Add("clock", (x, y) =>
            {
                var d = PawShapes.Circle(x, y, 0.5f, 0.5f);
                if (d < 0.45f && d > 0.36f) return true;
                return PawShapes.Seg(x, y, 0.5f, 0.5f, 0.5f, 0.74f) < 0.055f || PawShapes.Seg(x, y, 0.5f, 0.5f, 0.67f, 0.4f) < 0.055f;
            });
            Add("bell", (x, y) =>
                (PawShapes.Ellipse(x, y, 0.5f, 0.42f, 0.28f, 0.4f, 0f) && y > 0.3f) || PawShapes.RoundBox(x, y, 0.5f, 0.3f, 0.38f, 0.055f, 0.05f) < 0f ||
                (PawShapes.Circle(x, y, 0.5f, 0.16f) < 0.085f && y < 0.2f) || PawShapes.Circle(x, y, 0.5f, 0.84f) < 0.06f);
            Add("dice", (x, y) =>
            {
                if (PawShapes.RoundBox(x, y, 0.5f, 0.5f, 0.42f, 0.42f, 0.13f) >= 0f) return false;
                return !(PawShapes.Circle(x, y, 0.3f, 0.7f) < 0.095f || PawShapes.Circle(x, y, 0.5f, 0.5f) < 0.095f || PawShapes.Circle(x, y, 0.7f, 0.3f) < 0.095f);
            });
            Add("play", (x, y) => PawShapes.InTriangle(x, y, 0.3f, 0.16f, 0.3f, 0.84f, 0.86f, 0.5f));
            Add("pause", (x, y) =>
                PawShapes.RoundBox(x, y, 0.33f, 0.5f, 0.1f, 0.32f, 0.05f) < 0f || PawShapes.RoundBox(x, y, 0.67f, 0.5f, 0.1f, 0.32f, 0.05f) < 0f);
            Add("stop", (x, y) => PawShapes.RoundBox(x, y, 0.5f, 0.5f, 0.3f, 0.3f, 0.07f) < 0f);
            Add("lock", (x, y) =>
                LockBody(x, y) || (PawShapes.Ring(x, y, 0.5f, 0.6f, 0.17f, 0.06f) && y > 0.6f) ||
                PawShapes.Seg(x, y, 0.33f, 0.6f, 0.33f, 0.5f) < 0.06f || PawShapes.Seg(x, y, 0.67f, 0.6f, 0.67f, 0.5f) < 0.06f);
            Add("unlock", (x, y) =>
                LockBody(x, y) || (PawShapes.Ring(x, y, 0.5f, 0.66f, 0.17f, 0.06f) && y > 0.66f) || PawShapes.Seg(x, y, 0.33f, 0.66f, 0.33f, 0.5f) < 0.06f);
            Add("shield", (x, y) =>
            {
                if (y > 0.9f || y < 0.08f) return false;
                var w = y > 0.55f ? 0.37f : 0.37f * Mathf.Sqrt(Mathf.Clamp01((y - 0.08f) / 0.47f));
                if (Mathf.Abs(x - 0.5f) > w) return false;
                return !(PawShapes.Seg(x, y, 0.32f, 0.52f, 0.45f, 0.39f) < 0.05f || PawShapes.Seg(x, y, 0.45f, 0.39f, 0.7f, 0.66f) < 0.05f);
            });
            Add("key", (x, y) =>
            {
                PawShapes.Rotate(ref x, ref y, 45f);
                return PawShapes.Ring(x, y, 0.5f, 0.72f, 0.15f, 0.065f) || PawShapes.Seg(x, y, 0.5f, 0.57f, 0.5f, 0.08f) < 0.06f ||
                       PawShapes.Seg(x, y, 0.5f, 0.14f, 0.66f, 0.14f) < 0.055f || PawShapes.Seg(x, y, 0.5f, 0.28f, 0.62f, 0.28f) < 0.055f;
            });
            Add("eye", (x, y) =>
            {
                if (PawShapes.Circle(x, y, 0.5f, 0.5f) < 0.15f) return true;
                var lens = PawShapes.Circle(x, y, 0.5f, 0.06f) < 0.6f && PawShapes.Circle(x, y, 0.5f, 0.94f) < 0.6f;
                var inner = PawShapes.Circle(x, y, 0.5f, 0.06f) < 0.51f && PawShapes.Circle(x, y, 0.5f, 0.94f) < 0.51f;
                return lens && !inner;
            });
            Add("bolt", (x, y) => PawShapes.InPoly(x, y, BoltPoly));
            Add("home", (x, y) =>
            {
                if (PawShapes.Seg(x, y, 0.1f, 0.5f, 0.5f, 0.88f) < 0.065f || PawShapes.Seg(x, y, 0.5f, 0.88f, 0.9f, 0.5f) < 0.065f) return true;
                if (y >= 0.56f || PawShapes.RoundBox(x, y, 0.5f, 0.31f, 0.27f, 0.22f, 0.05f) >= 0f) return false;
                return PawShapes.RoundBox(x, y, 0.5f, 0.2f, 0.075f, 0.12f, 0.03f) >= 0f;
            });
            Add("sun", (x, y) =>
            {
                if (PawShapes.Circle(x, y, 0.5f, 0.5f) < 0.18f) return true;
                for (var k = 0; k < 8; k++)
                {
                    var a = k * 45f * Mathf.Deg2Rad;
                    float c = Mathf.Cos(a), s = Mathf.Sin(a);
                    if (PawShapes.Seg(x, y, 0.5f + 0.29f * c, 0.5f + 0.29f * s, 0.5f + 0.41f * c, 0.5f + 0.41f * s) < 0.055f) return true;
                }
                return false;
            });
            Add("moon", (x, y) => PawShapes.Circle(x, y, 0.47f, 0.5f) < 0.38f && PawShapes.Circle(x, y, 0.66f, 0.62f) > 0.3f);
            Add("cloud", (x, y) =>
                PawShapes.Circle(x, y, 0.36f, 0.44f) < 0.19f || PawShapes.Circle(x, y, 0.58f, 0.54f) < 0.24f ||
                PawShapes.Circle(x, y, 0.76f, 0.4f) < 0.16f || PawShapes.RoundBox(x, y, 0.53f, 0.33f, 0.33f, 0.1f, 0.1f) < 0f);
            Add("bug", (x, y) =>
            {
                var body = PawShapes.Ellipse(x, y, 0.5f, 0.42f, 0.22f, 0.3f, 0f);
                var head = PawShapes.Circle(x, y, 0.5f, 0.78f) < 0.13f;
                if (body || head) return !(Mathf.Abs(x - 0.5f) < 0.025f && y < 0.66f);
                for (var i = 0; i < 3; i++)
                {
                    var ly = 0.52f - i * 0.12f;
                    var dy = 0.08f - i * 0.08f;
                    if (PawShapes.Seg(x, y, 0.5f, ly, 0.12f, ly + dy) < 0.045f || PawShapes.Seg(x, y, 0.5f, ly, 0.88f, ly + dy) < 0.045f) return true;
                }
                return false;
            });
            Add("chevron", (x, y) =>
                PawShapes.Seg(x, y, 0.38f, 0.2f, 0.64f, 0.5f) < 0.075f || PawShapes.Seg(x, y, 0.64f, 0.5f, 0.38f, 0.8f) < 0.075f);
            Add("chevron-down", (x, y) =>
                PawShapes.Seg(x, y, 0.2f, 0.62f, 0.5f, 0.36f) < 0.075f || PawShapes.Seg(x, y, 0.5f, 0.36f, 0.8f, 0.62f) < 0.075f);
            Add("arrow-right", (x, y) =>
                PawShapes.Seg(x, y, 0.16f, 0.5f, 0.8f, 0.5f) < 0.07f || PawShapes.Seg(x, y, 0.82f, 0.5f, 0.58f, 0.74f) < 0.07f ||
                PawShapes.Seg(x, y, 0.82f, 0.5f, 0.58f, 0.26f) < 0.07f);

            // Keep IdList in gallery order (BuiltinIds), then anything else.
            IdList.Clear();
            foreach (var id in BuiltinIds)
            {
                if (Shapes.ContainsKey(id)) IdList.Add(id);
            }
            foreach (var id in Shapes.Keys)
            {
                if (!IdList.Contains(id)) IdList.Add(id);
            }
        }
    }
}
