// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
using System.Collections.Generic;
using System.Globalization;
using UnityEditor;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    internal enum PawButtonKind { Primary, Secondary, Danger, DangerSoft, Ghost, GhostDanger }

    /// <summary>What a composite control reports: nothing, its main area, its inline button, its link, or a right-click.</summary>
    internal enum PawHit { None, Main, Button, Link, Context }

    /// <summary>
    /// The PawUI immediate-mode widget kit (IMGUI only - no UI Toolkit, no image/font files). Rounded shapes use
    /// GUI.DrawTexture's corner-radius overload, so any color works without a texture per color. Every draw call
    /// is a no-op outside Repaint; every interactive control registers its control ID on every event, so IDs
    /// never shift between Layout and Repaint.
    /// Files: PawGUI.cs (primitives), PawGUI.Controls.cs (buttons, chips, fields...), PawGUI.Layout.cs (cards,
    /// status card, tiles...), PawGUI.Lists.cs (rows, log, footer), PawGUI.Chrome.cs (hero banner, tab bar).
    /// </summary>
    internal static partial class PawGUI
    {
        // ---- Layout grid (4px rhythm) ------------------------------------------------------------------
        internal const float Margin = 16f;
        internal const float CardGap = 12f;
        internal const float CardRadius = 12f;
        internal const float ControlRadius = 8f;
        internal const float TileRadius = 10f;

        /// <summary>
        /// Usable width inside the page padding for the current OnGUI (PawWindow sets it before drawing a page).
        /// Layout-time decisions (row heights, chip wrapping) read it so every event lays out identically.
        /// </summary>
        internal static float PageWidth = 400f;

        /// <summary>Width inside a default card (PageWidth minus CardPad).</summary>
        internal static float CardWidth => PageWidth - 32f;

        private static readonly int ClickHash = "PawUI.Click".GetHashCode();
        private static readonly GUIContent TempContent = new GUIContent();
        private static readonly Dictionary<(string, int, bool), (float, string)> EllipsisCache =
            new Dictionary<(string, int, bool), (float, string)>();
        private static readonly Dictionary<int, string> CountStrings = new Dictionary<int, string>();
        private static readonly Dictionary<string, Texture> BuiltinIcons = new Dictionary<string, Texture>();
        private static int _builtinIconVersion = -1;

        /// <summary>
        /// Screenshot harness switch: no hover states anywhere, so captures don't depend on where the real mouse cursor
        /// happens to be. Set by paw-ui/tools/harness/PawUIShot.cs only.
        /// </summary>
        internal static bool SuppressHover = false;

        /// <summary>
        /// Hero watermark on the last banner repaint: 0 = off (PawBrand.Watermark false), 1 = shown, 2 = dropped because
        /// the wordmark/tagline left no room (keep the tagline short). The screenshot harness reports 2 as a warning.
        /// </summary>
        internal static int WatermarkState = 0;

        internal static bool IsRepaint => Event.current.type == EventType.Repaint;

        /// <summary>Hover test for areas that aren't a Click control (cards, rows): pointer inside and no drag in progress.</summary>
        internal static bool Hovering(Rect r) => !SuppressHover && GUIUtility.hotControl == 0 && r.Contains(Event.current.mousePosition);

        /// <summary>Shared temp GUIContent (no allocation). Don't hold on to it.</summary>
        internal static GUIContent Content(string text, string tooltip = null)
        {
            TempContent.text = text;
            TempContent.tooltip = tooltip;
            TempContent.image = null;
            return TempContent;
        }

        internal static Vector2 Measure(string text, GUIStyle style) => style.CalcSize(Content(text));

        internal static Rect Inset(Rect r, float d) => new Rect(r.x + d, r.y + d, r.width - d * 2f, r.height - d * 2f);

        internal static Rect CircleRect(float cx, float cy, float radius) => new Rect(cx - radius, cy - radius, radius * 2f, radius * 2f);

        // ---- Shapes ----------------------------------------------------------------------------------
        internal static void Fill(Rect r, Color c, float radius = 0f)
        {
            if (!IsRepaint || c.a <= 0f) return;
            GUI.DrawTexture(r, Texture2D.whiteTexture, ScaleMode.StretchToFill, true, 0f, c, 0f, radius);
        }

        internal static void Stroke(Rect r, Color c, float radius, float width = 1f)
        {
            if (!IsRepaint || c.a <= 0f) return;
            GUI.DrawTexture(r, Texture2D.whiteTexture, ScaleMode.StretchToFill, true, 0f, c, width, radius);
        }

        /// <summary>1px tree connector: left + bottom edges of r with a rounded bottom-left corner.</summary>
        internal static void Elbow(Rect r, Color c, float radius)
        {
            if (!IsRepaint || c.a <= 0f) return;
            GUI.DrawTexture(r, Texture2D.whiteTexture, ScaleMode.StretchToFill, true, 0f, c,
                new Vector4(1f, 0f, 0f, 1f), new Vector4(0f, 0f, 0f, radius));
        }

        /// <summary>The brand gradient (Accent to Accent2, left to right).</summary>
        internal static void Gradient(Rect r, float radius, float alpha = 1f)
        {
            if (!IsRepaint || alpha <= 0f) return;
            GUI.DrawTexture(r, PawTheme.GradientTex, ScaleMode.StretchToFill, true, 0f, new Color(1f, 1f, 1f, alpha), 0f, radius);
        }

        /// <summary>Draws a white mask glyph (PawGlyphs) tinted with c.</summary>
        internal static void Glyph(Rect r, Texture tex, Color c)
        {
            if (!IsRepaint || tex == null) return;
            GUI.DrawTexture(r, tex, ScaleMode.ScaleToFit, true, 0f, c, 0f, 0f);
        }

        /// <summary>Soft 4-step drop shadow under a floating element (the tab bar).</summary>
        internal static void Shadow(Rect r, float radius, float strength = 1f)
        {
            if (!IsRepaint) return;
            var c = PawTheme.ShadowColor;
            for (var i = 4; i >= 1; i--)
            {
                var g = new Rect(r.x - i, r.y - i + 2f, r.width + i * 2f, r.height + i * 2f);
                Fill(g, PawTheme.Alpha(c, strength * 0.28f / i), radius + i);
            }
        }

        /// <summary>Card body: 1px lip shadow, 1px border, surface fill.</summary>
        internal static void CardFrame(Rect r, float radius = CardRadius)
        {
            if (!IsRepaint) return;
            Fill(new Rect(r.x, r.y + 1f, r.width, r.height + 1f), PawTheme.Alpha(PawTheme.ShadowColor, 0.5f), radius + 1f);
            Fill(r, PawTheme.Border, radius);
            Fill(Inset(r, 1f), PawTheme.Surface, radius - 1f);
        }

        /// <summary>The hero status card frame: brand-gradient border + soft accent glow when on (t=1), amber when off.</summary>
        internal static void StatusCardFrame(Rect r, float t)
        {
            if (!IsRepaint) return;
            const float radius = 14f;
            if (t > 0.01f)
            {
                for (var i = 3; i >= 1; i--)
                {
                    Fill(Inset(r, -i * 2.5f), PawTheme.Alpha(PawTheme.Accent, 0.07f * t / i), radius + i * 2.5f);
                }
            }
            else
            {
                Fill(new Rect(r.x, r.y + 1f, r.width, r.height + 1f), PawTheme.Alpha(PawTheme.ShadowColor, 0.5f), radius + 1f);
            }
            Fill(r, PawTheme.Alpha(PawTheme.Warning, 0.6f * (1f - t)), radius);
            Gradient(r, radius, t);
            var inner = Inset(r, 1f);
            Fill(inner, Color.Lerp(PawTheme.SurfaceWarn, PawTheme.Surface, t), radius - 1f);
            Gradient(inner, radius - 1f, 0.07f * t);
        }

        // ---- Interaction ------------------------------------------------------------------------------
        /// <summary>
        /// Click-on-release control over a rect. Returns true on the frame the click completes. Always takes a
        /// control ID (even when disabled) so IDs never shift. Register overlapping controls (an inline button over
        /// a clickable row) BEFORE the larger one so the smaller wins the click.
        /// </summary>
        internal static bool Click(Rect r, bool enabled, out bool hover, out bool pressed) => Click(r, enabled, null, out hover, out pressed);

        /// <summary>
        /// Click with a label: interaction tests find and click the control by that text (PawTest.Click(window, label)).
        /// Pass what the user reads on it (button text, tab label, row title).
        /// </summary>
        internal static bool Click(Rect r, bool enabled, string label, out bool hover, out bool pressed)
        {
            var id = GUIUtility.GetControlID(ClickHash, FocusType.Passive, r);
            var e = Event.current;
            pressed = GUIUtility.hotControl == id;
            hover = enabled && !SuppressHover && r.Contains(e.mousePosition) && (GUIUtility.hotControl == 0 || pressed);
            if (PawTest.Active)
            {
                PawTest.Note(label, r, enabled);
                if (enabled && PawTest.Take(r)) return true;
            }
            if (!enabled) return false;

            switch (e.GetTypeForControl(id))
            {
                case EventType.MouseDown:
                    if (e.button == 0 && r.Contains(e.mousePosition))
                    {
                        GUIUtility.hotControl = id;
                        e.Use();
                    }
                    break;
                case EventType.MouseDrag:
                    if (GUIUtility.hotControl == id) e.Use();
                    break;
                case EventType.MouseUp:
                    if (GUIUtility.hotControl == id)
                    {
                        GUIUtility.hotControl = 0;
                        e.Use();
                        return r.Contains(e.mousePosition);
                    }
                    break;
                case EventType.Repaint:
                    EditorGUIUtility.AddCursorRect(r, MouseCursor.Link);
                    break;
            }
            return false;
        }

        /// <summary>True (and consumes the event) when r was right-clicked this event.</summary>
        internal static bool ContextClick(Rect r)
        {
            var e = Event.current;
            if (e.type != EventType.ContextClick || !r.Contains(e.mousePosition)) return false;
            e.Use();
            return true;
        }

        internal static void Tooltip(Rect r, string tooltip)
        {
            if (string.IsNullOrEmpty(tooltip)) return;
            GUI.Label(r, Content(string.Empty, tooltip), GUIStyle.none);
        }

        // ---- Text --------------------------------------------------------------------------------------
        /// <summary>Shortens text to fit a width with an ellipsis at the end (or in the middle, for paths). Cached per width.</summary>
        internal static string Ellipsize(string text, GUIStyle style, float width, bool middle = false)
        {
            if (string.IsNullOrEmpty(text) || width <= 4f) return string.Empty;
            var key = (text, style.fontSize * 4 + (int)style.fontStyle, middle);
            if (EllipsisCache.TryGetValue(key, out var hit) && Mathf.Abs(hit.Item1 - width) < 0.5f) return hit.Item2;

            string result;
            if (Measure(text, style).x <= width)
            {
                result = text;
            }
            else
            {
                result = "\u2026";
                int lo = 1, hi = text.Length - 1;
                while (lo <= hi)
                {
                    var mid = (lo + hi) / 2;
                    var candidate = Cut(text, mid, middle);
                    if (Measure(candidate, style).x <= width)
                    {
                        result = candidate;
                        lo = mid + 1;
                    }
                    else
                    {
                        hi = mid - 1;
                    }
                }
            }

            if (EllipsisCache.Count > 2048) EllipsisCache.Clear();
            EllipsisCache[key] = (width, result);
            return result;
        }

        private static string Cut(string s, int keep, bool middle)
        {
            if (!middle) return s.Substring(0, keep).TrimEnd() + "\u2026";
            var left = (keep + 1) / 2;
            var right = keep - left;
            return s.Substring(0, left) + "\u2026" + s.Substring(s.Length - right);
        }

        /// <summary>Cached "7" / "99+" strings for badges (no per-frame int.ToString()).</summary>
        internal static string CountText(int n)
        {
            if (n > 99) return "99+";
            if (!CountStrings.TryGetValue(n, out var s)) CountStrings[n] = s = n.ToString(CultureInfo.InvariantCulture);
            return s;
        }

        /// <summary>
        /// A built-in editor icon by name, cached and reloaded after a skin change. Only use names that exist in
        /// Unity 2022.3 ("Folder Icon", "Material Icon", "Texture Icon", "Shader Icon", "Prefab Icon",
        /// "SceneAsset Icon", "DefaultAsset Icon", "Mesh Icon", "AudioClip Icon", "AnimationClip Icon",
        /// "cs Script Icon") - unknown names spam "Unable to load the icon" warnings. Prefer PawGlyphs.
        /// </summary>
        internal static Texture BuiltinIcon(string name)
        {
            if (_builtinIconVersion != PawTheme.Version)
            {
                _builtinIconVersion = PawTheme.Version;
                BuiltinIcons.Clear();
            }
            if (BuiltinIcons.TryGetValue(name, out var tex) && tex != null) return tex;
            tex = EditorGUIUtility.IconContent(name)?.image;
            BuiltinIcons[name] = tex;
            return tex;
        }
    }
}
