// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
using UnityEditor;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    internal static partial class PawGUI
    {
        // ---- Buttons ----------------------------------------------------------------------------------
        /// <summary>Width a button needs for its text + optional 14px glyph.</summary>
        internal static float ButtonWidth(string text, Texture glyph, float padding = 14f)
        {
            var w = string.IsNullOrEmpty(text) ? 0f : Measure(text, PawTheme.Label(12, Color.white, true)).x;
            if (glyph != null) w += string.IsNullOrEmpty(text) ? 14f : 20f;
            return Mathf.Ceil(w + padding * 2f);
        }

        /// <summary>
        /// A button. Primary = brand gradient (one per view: the main action). Secondary = framed. Danger = solid red
        /// (destructive, confirm first). DangerSoft = red tint (destructive but secondary). Ghost / GhostDanger =
        /// frameless (row actions, toolbars).
        /// </summary>
        internal static bool Button(Rect r, string text, PawButtonKind kind, bool enabled = true, Texture glyph = null, string tooltip = null)
        {
            var clicked = Click(r, enabled, string.IsNullOrEmpty(text) ? tooltip : text, out var hover, out var pressed);
            if (IsRepaint) DrawButton(r, text, kind, enabled, hover, pressed, glyph);
            Tooltip(r, tooltip);
            return clicked;
        }

        /// <summary>Layout version; width 0 = fit the content.</summary>
        internal static bool LayoutButton(string text, PawButtonKind kind, bool enabled = true, Texture glyph = null, float height = 30f,
            float width = 0f, string tooltip = null)
        {
            var w = width > 0f ? width : ButtonWidth(text, glyph);
            var r = GUILayoutUtility.GetRect(w, height, GUILayout.Width(w), GUILayout.Height(height));
            return Button(r, text, kind, enabled, glyph, tooltip);
        }

        /// <summary>Square glyph-only button (ghost by default) - toolbars, row actions, the dice in a preview strip.</summary>
        internal static bool IconButton(Rect r, Texture glyph, string tooltip, PawButtonKind kind = PawButtonKind.Ghost, bool enabled = true) =>
            Button(r, string.Empty, kind, enabled, glyph, tooltip);

        internal static void DrawButton(Rect r, string text, PawButtonKind kind, bool enabled, bool hover, bool pressed, Texture glyph)
        {
            const float radius = ControlRadius;
            Color fg;
            if (!enabled)
            {
                if (kind != PawButtonKind.Ghost && kind != PawButtonKind.GhostDanger)
                {
                    Fill(r, PawTheme.SurfaceRaised, radius);
                    Stroke(r, PawTheme.Border, radius);
                }
                fg = PawTheme.Alpha(PawTheme.TextMuted, 0.8f);
            }
            else
            {
                switch (kind)
                {
                    case PawButtonKind.Primary:
                        Gradient(r, radius);
                        if (hover) Fill(r, new Color(1f, 1f, 1f, 0.12f), radius);
                        if (pressed) Fill(r, new Color(0f, 0f, 0f, 0.14f), radius);
                        fg = Color.white;
                        break;
                    case PawButtonKind.Danger:
                        Fill(r, hover ? PawTheme.DangerFillHover : PawTheme.DangerFill, radius);
                        if (pressed) Fill(r, new Color(0f, 0f, 0f, 0.14f), radius);
                        fg = Color.white;
                        break;
                    case PawButtonKind.DangerSoft:
                        Fill(r, PawTheme.Alpha(PawTheme.Danger, hover ? 0.22f : 0.13f), radius);
                        if (pressed) Fill(r, PawTheme.Alpha(PawTheme.Danger, 0.12f), radius);
                        fg = PawTheme.Danger;
                        break;
                    case PawButtonKind.Ghost:
                        if (hover) Fill(r, PawTheme.SurfaceHover, radius);
                        if (pressed) Fill(r, PawTheme.Alpha(PawTheme.ShadowColor, 0.4f), radius);
                        fg = hover ? PawTheme.Text : PawTheme.TextSecondary;
                        break;
                    case PawButtonKind.GhostDanger:
                        if (hover) Fill(r, PawTheme.Alpha(PawTheme.Danger, 0.14f), radius);
                        if (pressed) Fill(r, PawTheme.Alpha(PawTheme.Danger, 0.1f), radius);
                        fg = hover ? PawTheme.Danger : PawTheme.TextSecondary;
                        break;
                    default:
                        Fill(r, hover ? PawTheme.SurfaceHover : PawTheme.SurfaceRaised, radius);
                        Stroke(r, hover ? PawTheme.BorderStrong : PawTheme.Border, radius);
                        if (pressed) Fill(r, PawTheme.Alpha(PawTheme.ShadowColor, 0.3f), radius);
                        fg = PawTheme.Text;
                        break;
                }
            }

            var style = PawTheme.Label(12, fg, true);
            var hasText = !string.IsNullOrEmpty(text);
            var tw = hasText ? Measure(text, style).x : 0f;
            var gw = glyph != null ? 14f : 0f;
            var gap = glyph != null && hasText ? 6f : 0f;
            var x = Mathf.Round(r.center.x - (tw + gw + gap) / 2f);
            if (glyph != null)
            {
                Glyph(new Rect(x, Mathf.Round(r.center.y - 7f), 14f, 14f), glyph, fg);
                x += gw + gap;
            }
            if (hasText) GUI.Label(new Rect(x, r.y, tw + 2f, r.height), text, style);
        }

        /// <summary>Frosted round icon button for the hero banner (white glass on the gradient).</summary>
        internal static bool FrostButton(Rect r, Texture glyph, string tooltip, string label = null)
        {
            var clicked = Click(r, true, label ?? tooltip, out var hover, out var pressed);
            if (IsRepaint)
            {
                var radius = r.height / 2f;
                Fill(r, new Color(1f, 1f, 1f, pressed ? 0.12f : hover ? 0.28f : 0.17f), radius);
                Stroke(r, new Color(1f, 1f, 1f, hover ? 0.45f : 0.3f), radius);
                Glyph(Inset(r, 5.5f), glyph, new Color(1f, 1f, 1f, hover ? 1f : 0.92f));
            }
            Tooltip(r, tooltip);
            return clicked;
        }

        // ---- Chips & badges ---------------------------------------------------------------------------
        internal static float ChipWidth(string text, int size = 9) =>
            Mathf.Ceil(Measure(text, PawTheme.Label(size, Color.white, true)).x + 16f);

        /// <summary>Tinted pill with bold uppercase text: kinds, "RECOMMENDED", "LATEST", "IN USE", counts.</summary>
        internal static void Chip(Rect r, string text, Color color, int size = 9)
        {
            if (!IsRepaint) return;
            Fill(r, PawTheme.Alpha(color, PawTheme.TintAlpha + 0.02f), r.height / 2f);
            GUI.Label(r, text, PawTheme.Label(size, color, true, TextAnchor.MiddleCenter));
        }

        internal static void LayoutChip(string text, Color color, float height = 20f, int size = 9)
        {
            var w = ChipWidth(text, size);
            var r = GUILayoutUtility.GetRect(w, height, GUILayout.Width(w), GUILayout.Height(height));
            Chip(r, text, color, size);
        }

        internal static float BadgeWidth(string text) =>
            Mathf.Max(18f, Measure(text, PawTheme.Label(10, Color.white, true, TextAnchor.MiddleCenter)).x + 10f);

        /// <summary>
        /// Count bubble (16px tall) - tab badges, list counts. danger = solid red (failures); onAccent = white glass,
        /// for use on top of the gradient (the selected tab).
        /// </summary>
        internal static void Badge(Rect r, string text, bool danger = false, bool onAccent = false)
        {
            if (!IsRepaint) return;
            var radius = r.height / 2f;
            if (onAccent && danger)
            {
                Fill(r, PawTheme.Alpha(PawTheme.DangerFill, 0.85f), radius);
                Stroke(r, new Color(1f, 1f, 1f, 0.85f), radius);
            }
            else
            {
                Fill(r, onAccent ? new Color(1f, 1f, 1f, 0.24f) : danger ? PawTheme.DangerFill : PawTheme.Alpha(PawTheme.TextMuted, 0.25f), radius);
            }
            var fg = onAccent || danger ? Color.white : PawTheme.TextSecondary;
            GUI.Label(r, text, PawTheme.Label(10, fg, true, TextAnchor.MiddleCenter));
        }

        /// <summary>Small status dot with a soft halo (unsaved edits, live state).</summary>
        internal static void Dot(Rect r, Color color, bool halo = true)
        {
            if (!IsRepaint) return;
            if (halo) Fill(Inset(r, -2.5f), PawTheme.Alpha(color, 0.3f), r.width / 2f + 2.5f);
            Fill(r, color, r.width / 2f);
        }

        // ---- Checkbox / radio / switch ----------------------------------------------------------------
        internal static void Checkbox(Rect r, bool on, bool hover)
        {
            if (!IsRepaint) return;
            if (on)
            {
                Gradient(r, 5f);
                if (hover) Fill(r, new Color(1f, 1f, 1f, 0.12f), 5f);
                Glyph(Inset(r, 2.5f), PawGlyphs.Check, Color.white);
            }
            else
            {
                Fill(r, PawTheme.FieldBg, 5f);
                Stroke(r, hover ? PawTheme.Accent : PawTheme.BorderStrong, 5f, 1.5f);
            }
        }

        internal static void Radio(Rect r, bool on, bool hover)
        {
            if (!IsRepaint) return;
            if (on)
            {
                Gradient(r, r.width / 2f);
                Fill(Inset(r, 5f), Color.white, (r.width - 10f) / 2f);
            }
            else
            {
                Fill(r, PawTheme.FieldBg, r.width / 2f);
                Stroke(r, hover ? PawTheme.Accent : PawTheme.BorderStrong, r.width / 2f, 1.5f);
            }
        }

        /// <summary>The ON/OFF switch (60x32 in the status card, 36x20 in toggle rows). t = 0 off .. 1 on (animate with PawTween).</summary>
        internal static void Switch(Rect r, float t, bool hover, bool glyphKnob = true)
        {
            if (!IsRepaint) return;
            var radius = r.height / 2f;
            Fill(r, PawTheme.SwitchOff, radius);
            Gradient(r, radius, t);
            if (hover) Fill(r, new Color(1f, 1f, 1f, 0.07f), radius);

            var pad = r.height >= 28f ? 3f : 2f;
            var k = r.height - pad * 2f;
            var kx = Mathf.Lerp(r.x + pad, r.xMax - pad - k, t);
            var knob = new Rect(kx, r.y + pad, k, k);
            Fill(new Rect(knob.x - 0.5f, knob.y + 1f, k + 1f, k + 1f), new Color(0f, 0f, 0f, 0.28f), k / 2f + 0.5f);
            Fill(knob, Color.white, k / 2f);
            if (glyphKnob && k >= 18f)
            {
                Glyph(Inset(knob, 6f), PawTheme.BrandGlyph, Color.Lerp(PawTheme.Alpha(Color.gray, 0.55f), PawTheme.Accent, t));
            }
        }

        /// <summary>Checkbox + label, the whole row clickable. Returns the new value.</summary>
        internal static bool CheckToggle(string label, bool value, string tooltip = null, bool enabled = true)
        {
            var style = PawTheme.Label(12, enabled ? PawTheme.Text : PawTheme.TextMuted);
            var w = 24f + Mathf.Ceil(Measure(label, style).x);
            var r = GUILayoutUtility.GetRect(w, 22f, GUILayout.Height(22f), GUILayout.ExpandWidth(false));
            var clicked = Click(r, enabled, label, out var hover, out _);
            if (IsRepaint)
            {
                Checkbox(new Rect(r.x, Mathf.Round(r.center.y - 8f), 16f, 16f), value, hover);
                GUI.Label(new Rect(r.x + 24f, r.y, r.width - 24f, r.height), label, style);
            }
            Tooltip(r, tooltip);
            if (clicked)
            {
                GUI.changed = true;
                return !value;
            }
            return value;
        }

        /// <summary>
        /// Settings row: bold title + wrapped description on the left, a small switch on the right; the whole row
        /// toggles. Returns the new value (wrap in BeginChangeCheck/EndChangeCheck and save on change).
        /// </summary>
        internal static bool ToggleRow(string title, string description, bool value, string tooltip = null, bool enabled = true)
        {
            var row = EditorGUILayout.BeginHorizontal(GUILayout.MinHeight(34f));
            // The row rect is final on Repaint, so the hover fill goes in first - behind the text, never over it.
            var hit = new Rect(row.x - 6f, row.y - 4f, row.width + 12f, row.height + 8f);
            if (IsRepaint && enabled && Hovering(hit)) Fill(hit, PawTheme.Alpha(PawTheme.SurfaceHover, 0.7f), ControlRadius);
            GUILayout.BeginVertical();
            GUILayout.Label(title, PawTheme.Label(12, enabled ? PawTheme.Text : PawTheme.TextMuted, true), GUILayout.Height(18f));
            if (!string.IsNullOrEmpty(description))
            {
                GUILayout.Space(1f);
                GUILayout.Label(description, PawTheme.Label(11, PawTheme.TextSecondary, wrap: true));
            }
            GUILayout.EndVertical();
            GUILayout.Space(12f);
            GUILayoutUtility.GetRect(38f, 20f, GUILayout.Width(38f), GUILayout.Height(20f));
            EditorGUILayout.EndHorizontal();

            hit = new Rect(row.x - 6f, row.y - 4f, row.width + 12f, row.height + 8f);
            var clicked = Click(hit, enabled, title, out var hover, out _);
            if (IsRepaint)
            {
                var sw = new Rect(row.xMax - 38f, Mathf.Round(row.y + Mathf.Min(row.height, 40f) / 2f - 10f), 38f, 20f);
                Switch(sw, value ? 1f : 0f, hover, false);
                if (!enabled) Fill(sw, PawTheme.Alpha(PawTheme.Surface, 0.5f), 10f);
            }
            Tooltip(hit, tooltip);
            if (clicked)
            {
                GUI.changed = true;
                return !value;
            }
            return value;
        }

        // ---- Icon tile, divider, link, progress -------------------------------------------------------
        /// <summary>28px tinted rounded tile holding a glyph - card headers, tiles.</summary>
        internal static void IconTile(Texture glyph, Color color, float size = 28f)
        {
            var r = GUILayoutUtility.GetRect(size, size, GUILayout.Width(size), GUILayout.Height(size));
            IconTile(r, glyph, color);
        }

        internal static void IconTile(Rect r, Texture glyph, Color color)
        {
            if (!IsRepaint) return;
            Fill(r, PawTheme.Alpha(color, PawTheme.TintAlpha), Mathf.Round(r.width * 0.29f));
            Glyph(Inset(r, Mathf.Round(r.width * 0.24f)), glyph, color);
        }

        /// <summary>Round tinted avatar/initial bubble.</summary>
        internal static void Initial(Rect r, string letter, Color color)
        {
            if (!IsRepaint) return;
            Fill(r, PawTheme.Alpha(color, PawTheme.TintAlpha + 0.06f), r.width / 2f);
            GUI.Label(r, letter, PawTheme.Label(13, color, true, TextAnchor.MiddleCenter));
        }

        internal static void Divider(float insetLeft = 0f)
        {
            var r = GUILayoutUtility.GetRect(0f, 1f, GUILayout.ExpandWidth(true), GUILayout.Height(1f));
            r.xMin += insetLeft;
            Fill(r, PawTheme.Divider);
        }

        /// <summary>Quiet text link ("View log &gt;"): muted at rest, accent + underline on hover.</summary>
        internal static bool Link(Rect r, string text, bool enabled = true, string tooltip = null)
        {
            var clicked = Click(r, enabled, text, out var hover, out _);
            if (IsRepaint)
            {
                var fg = !enabled ? PawTheme.Alpha(PawTheme.TextMuted, 0.6f) : hover ? PawTheme.AccentText : PawTheme.TextMuted;
                var style = PawTheme.Label(11, fg);
                GUI.Label(r, text, style);
                if (hover)
                {
                    var w = Mathf.Min(r.width, Mathf.Ceil(Measure(text, style).x));
                    Fill(new Rect(r.x, Mathf.Round(r.center.y + 7f), w, 1f), PawTheme.Alpha(fg, 0.7f));
                }
            }
            if (enabled) Tooltip(r, tooltip);
            return clicked;
        }

        internal static float LinkWidth(string text) => Mathf.Ceil(Measure(text, PawTheme.Label(11, Color.white)).x) + 1f;

        /// <summary>Gradient progress bar (0..1) on a quiet track.</summary>
        internal static void Progress(Rect r, float t)
        {
            if (!IsRepaint) return;
            var radius = r.height / 2f;
            Fill(r, PawTheme.Alpha(PawTheme.TextMuted, 0.2f), radius);
            t = Mathf.Clamp01(t);
            if (t <= 0f) return;
            var w = Mathf.Max(r.height, r.width * t);
            Gradient(new Rect(r.x, r.y, w, r.height), radius);
        }

        internal static Rect LayoutProgress(float t, float height = 8f)
        {
            var r = GUILayoutUtility.GetRect(0f, height, GUILayout.ExpandWidth(true), GUILayout.Height(height));
            Progress(r, t);
            return r;
        }

        // ---- Fields -----------------------------------------------------------------------------------
        /// <summary>Rounded field frame with the accent focus ring (search, text and number fields). Disabled = flat and dim.</summary>
        internal static void FieldFrame(Rect r, bool focused, bool strong, bool enabled = true)
        {
            if (!IsRepaint) return;
            if (!enabled)
            {
                Fill(r, PawTheme.Border, ControlRadius);
                Fill(Inset(r, 1f), PawTheme.SurfaceRaised, ControlRadius - 1f);
                return;
            }
            if (focused) Fill(Inset(r, -3f), PawTheme.Alpha(PawTheme.Accent, 0.18f), 11f);
            Fill(r, focused ? PawTheme.Accent : strong ? PawTheme.BorderStrong : PawTheme.Border, ControlRadius);
            Fill(Inset(r, focused ? 1.5f : 1f), PawTheme.FieldBg, ControlRadius - 1f);
        }

        /// <summary>11px bold muted label above a field ("Name prefix"), 4px gap below. Use inside a vertical group.</summary>
        internal static void FieldLabel(string text, string tooltip = null)
        {
            GUILayout.Label(Content(text, tooltip), PawTheme.Label(11, PawTheme.TextMuted, true), GUILayout.Height(16f));
            GUILayout.Space(4f);
        }

        /// <summary>
        /// Starts a labelled field column: FieldLabel + your field(s), then EndLabeledField(). width 0 = stretch. Put two
        /// side by side in a horizontal group with GUILayout.Space(12f) between them (showcase Settings tab).
        /// </summary>
        internal static void BeginLabeledField(string label, float width = 0f, string tooltip = null)
        {
            if (width > 0f) EditorGUILayout.BeginVertical(GUILayout.Width(width));
            else EditorGUILayout.BeginVertical();
            FieldLabel(label, tooltip);
        }

        internal static void EndLabeledField() => EditorGUILayout.EndVertical();

        /// <summary>
        /// Rounded single-line text field with placeholder and optional leading glyph. Returns the new text.
        /// enabled = false draws it flat and read-only (EditorGUI.BeginDisabledGroup inside).
        /// </summary>
        internal static string TextField(string controlName, string value, string placeholder, PawFocus focus, Texture glyph = null,
            float height = 30f, string tooltip = null, bool enabled = true)
        {
            var r = GUILayoutUtility.GetRect(0f, height, GUILayout.ExpandWidth(true), GUILayout.Height(height));
            return TextField(r, controlName, value, placeholder, focus, glyph, tooltip, enabled);
        }

        internal static string TextField(Rect r, string controlName, string value, string placeholder, PawFocus focus, Texture glyph = null,
            string tooltip = null, bool enabled = true)
        {
            value = value ?? string.Empty;
            var focused = enabled && focus != null && focus.Is(controlName);
            FieldFrame(r, focused, value.Length > 0, enabled);
            var left = glyph != null ? 32f : 12f;
            if (glyph != null && IsRepaint)
            {
                Glyph(new Rect(r.x + 10f, Mathf.Round(r.center.y - 7f), 14f, 14f), glyph,
                    focused ? PawTheme.AccentText : PawTheme.Alpha(PawTheme.TextMuted, enabled ? 1f : 0.6f));
            }
            var field = new Rect(r.x + left, r.y, Mathf.Max(0f, r.width - left - 10f), r.height);
            EditorGUI.BeginDisabledGroup(!enabled);
            GUI.SetNextControlName(controlName);
            var text = EditorGUI.TextField(field, value, PawTheme.FieldText);
            EditorGUI.EndDisabledGroup();
            if (IsRepaint && value.Length == 0 && !focused && !string.IsNullOrEmpty(placeholder))
            {
                GUI.Label(field, placeholder, PawTheme.Label(12, PawTheme.Alpha(PawTheme.TextMuted, enabled ? 1f : 0.6f)));
            }
            Tooltip(r, tooltip);
            return enabled ? text : value;
        }

        /// <summary>Rounded integer field (fixed width) with an optional dim suffix ("px", "min"). Returns the new value.</summary>
        internal static int IntField(string controlName, int value, PawFocus focus, float width = 90f, float height = 30f, string suffix = null,
            bool enabled = true, string tooltip = null)
        {
            var r = GUILayoutUtility.GetRect(width, height, GUILayout.Width(width), GUILayout.Height(height));
            return IntField(r, controlName, value, focus, suffix, enabled, tooltip);
        }

        internal static int IntField(Rect r, string controlName, int value, PawFocus focus, string suffix = null, bool enabled = true,
            string tooltip = null)
        {
            var field = NumberFieldFrame(r, controlName, focus, suffix, enabled);
            EditorGUI.BeginDisabledGroup(!enabled);
            GUI.SetNextControlName(controlName);
            var v = EditorGUI.IntField(field, value, PawTheme.FieldText);
            EditorGUI.EndDisabledGroup();
            NumberFieldSuffix(r, suffix, enabled);
            Tooltip(r, tooltip);
            return enabled ? v : value;
        }

        /// <summary>Rounded float field (fixed width) with an optional dim suffix. Returns the new value.</summary>
        internal static float FloatField(string controlName, float value, PawFocus focus, float width = 90f, float height = 30f,
            string suffix = null, bool enabled = true, string tooltip = null)
        {
            var r = GUILayoutUtility.GetRect(width, height, GUILayout.Width(width), GUILayout.Height(height));
            return FloatField(r, controlName, value, focus, suffix, enabled, tooltip);
        }

        internal static float FloatField(Rect r, string controlName, float value, PawFocus focus, string suffix = null, bool enabled = true,
            string tooltip = null)
        {
            var field = NumberFieldFrame(r, controlName, focus, suffix, enabled);
            EditorGUI.BeginDisabledGroup(!enabled);
            GUI.SetNextControlName(controlName);
            var v = EditorGUI.FloatField(field, value, PawTheme.FieldText);
            EditorGUI.EndDisabledGroup();
            NumberFieldSuffix(r, suffix, enabled);
            Tooltip(r, tooltip);
            return enabled ? v : value;
        }

        private static Rect NumberFieldFrame(Rect r, string controlName, PawFocus focus, string suffix, bool enabled)
        {
            var focused = enabled && focus != null && focus.Is(controlName);
            FieldFrame(r, focused, true, enabled);
            return new Rect(r.x + 12f, r.y, Mathf.Max(0f, r.width - 20f - SuffixWidth(suffix)), r.height);
        }

        private static float SuffixWidth(string suffix) =>
            string.IsNullOrEmpty(suffix) ? 0f : Mathf.Ceil(Measure(suffix, PawTheme.Label(11, Color.white)).x) + 8f;

        private static void NumberFieldSuffix(Rect r, string suffix, bool enabled)
        {
            var sw = SuffixWidth(suffix);
            if (sw <= 0f || !IsRepaint) return;
            GUI.Label(new Rect(r.xMax - 8f - sw, r.y, sw, r.height), suffix,
                PawTheme.Label(11, PawTheme.Alpha(PawTheme.TextMuted, enabled ? 1f : 0.6f), anchor: TextAnchor.MiddleRight));
        }

        // ---- Sliders ----------------------------------------------------------------------------------
        private static readonly int SliderHash = "PawUI.Slider".GetHashCode();

        /// <summary>
        /// Branded slider: 6px track, gradient fill up to the value, 18px white knob with an accent core, accent ring on
        /// hover/drag. Click or drag anywhere on the rect (30px tall reads best). Always takes its control ID.
        /// step &gt; 0 snaps (1 = whole numbers). Returns the new value (GUI.changed is set when it moves).
        /// </summary>
        internal static float Slider(Rect r, float value, float min, float max, bool enabled = true, string tooltip = null, float step = 0f)
        {
            var id = GUIUtility.GetControlID(SliderHash, FocusType.Passive, r);
            var e = Event.current;
            var track = new Rect(r.x + 9f, Mathf.Round(r.center.y - 3f), Mathf.Max(1f, r.width - 18f), 6f);
            var hot = GUIUtility.hotControl == id;
            var result = value;
            if (enabled)
            {
                switch (e.GetTypeForControl(id))
                {
                    case EventType.MouseDown:
                        if (e.button == 0 && r.Contains(e.mousePosition))
                        {
                            GUIUtility.hotControl = id;
                            // Drop keyboard focus so a paired number field shows the dragged value, not its edit buffer.
                            GUIUtility.keyboardControl = 0;
                            result = SliderValueAt(track, e.mousePosition.x, min, max, step);
                            e.Use();
                        }
                        break;
                    case EventType.MouseDrag:
                        if (hot)
                        {
                            result = SliderValueAt(track, e.mousePosition.x, min, max, step);
                            e.Use();
                        }
                        break;
                    case EventType.MouseUp:
                        if (hot)
                        {
                            GUIUtility.hotControl = 0;
                            e.Use();
                        }
                        break;
                    case EventType.Repaint:
                        EditorGUIUtility.AddCursorRect(r, MouseCursor.SlideArrow);
                        break;
                }
            }

            if (IsRepaint)
            {
                var t = max > min ? Mathf.Clamp01((value - min) / (max - min)) : 0f;
                var kx = track.x + t * track.width;
                Fill(track, PawTheme.Alpha(PawTheme.TextMuted, 0.2f), 3f);
                var fill = new Rect(track.x, track.y, Mathf.Max(6f, kx - track.x), track.height);
                if (enabled) Gradient(fill, 3f);
                else Fill(fill, PawTheme.Alpha(PawTheme.TextMuted, 0.35f), 3f);

                var knob = new Rect(Mathf.Round(kx - 9f), Mathf.Round(r.center.y - 9f), 18f, 18f);
                var hover = enabled && (hot || Hovering(r));
                if (hover) Fill(Inset(knob, -4f), PawTheme.Alpha(PawTheme.Accent, hot ? 0.3f : 0.2f), 13f);
                Fill(new Rect(knob.x - 0.5f, knob.y + 1f, knob.width + 1f, knob.height + 1f), new Color(0f, 0f, 0f, 0.28f), 9.5f);
                Fill(knob, enabled ? Color.white : PawTheme.SwitchOff, 9f);
                if (enabled) Fill(Inset(knob, 6f), PawTheme.Accent, 3f);
            }
            if (enabled) Tooltip(r, tooltip);
            if (!Mathf.Approximately(result, value)) GUI.changed = true;
            return result;
        }

        /// <summary>Whole-number slider (see Slider).</summary>
        internal static int IntSlider(Rect r, int value, int min, int max, bool enabled = true, string tooltip = null) =>
            Mathf.RoundToInt(Slider(r, value, min, max, enabled, tooltip, 1f));

        private static float SliderValueAt(Rect track, float x, float min, float max, float step)
        {
            var v = min + Mathf.Clamp01((x - track.x) / track.width) * (max - min);
            if (step > 0f) v = min + Mathf.Round((v - min) / step) * step;
            return Mathf.Clamp(v, Mathf.Min(min, max), Mathf.Max(min, max));
        }

        /// <summary>
        /// Slider + number field + optional end labels ("1 min" ... "30 min") - the EditorGUILayout.IntSlider replacement.
        /// The field clamps typed values to min..max. Returns the new value; wrap in BeginChangeCheck/EndChangeCheck.
        /// </summary>
        internal static int LayoutIntSlider(string controlName, int value, int min, int max, PawFocus focus, string suffix = null,
            string minLabel = null, string maxLabel = null, bool enabled = true, string tooltip = null, float fieldWidth = 88f)
        {
            EditorGUILayout.BeginHorizontal();
            var slid = IntSlider(SliderColumn(minLabel, maxLabel, enabled), value, min, max, enabled, tooltip);
            GUILayout.Space(14f);
            var typed = IntField(controlName, value, focus, fieldWidth, 30f, suffix, enabled);
            EditorGUILayout.EndHorizontal();
            return Mathf.Clamp(typed != value ? typed : slid, Mathf.Min(min, max), Mathf.Max(min, max));
        }

        /// <summary>Float version of LayoutIntSlider (step 0 = continuous).</summary>
        internal static float LayoutSlider(string controlName, float value, float min, float max, PawFocus focus, string suffix = null,
            string minLabel = null, string maxLabel = null, bool enabled = true, string tooltip = null, float step = 0f, float fieldWidth = 88f)
        {
            EditorGUILayout.BeginHorizontal();
            var slid = Slider(SliderColumn(minLabel, maxLabel, enabled), value, min, max, enabled, tooltip, step);
            GUILayout.Space(14f);
            var typed = FloatField(controlName, value, focus, fieldWidth, 30f, suffix, enabled);
            EditorGUILayout.EndHorizontal();
            return Mathf.Clamp(!Mathf.Approximately(typed, value) ? typed : slid, Mathf.Min(min, max), Mathf.Max(min, max));
        }

        private static Rect SliderColumn(string minLabel, string maxLabel, bool enabled)
        {
            EditorGUILayout.BeginVertical();
            var r = GUILayoutUtility.GetRect(0f, 30f, GUILayout.ExpandWidth(true), GUILayout.Height(30f));
            if (minLabel != null || maxLabel != null)
            {
                var ticks = GUILayoutUtility.GetRect(0f, 14f, GUILayout.ExpandWidth(true), GUILayout.Height(14f));
                if (IsRepaint)
                {
                    var c = PawTheme.Alpha(PawTheme.TextMuted, enabled ? 1f : 0.6f);
                    if (minLabel != null) GUI.Label(new Rect(ticks.x + 2f, ticks.y, ticks.width / 2f, ticks.height), minLabel, PawTheme.Label(10, c));
                    if (maxLabel != null)
                    {
                        GUI.Label(new Rect(ticks.center.x, ticks.y, ticks.width / 2f - 2f, ticks.height), maxLabel,
                            PawTheme.Label(10, c, anchor: TextAnchor.MiddleRight));
                    }
                }
            }
            EditorGUILayout.EndVertical();
            return r;
        }

        /// <summary>
        /// Rounded search field: glyph, placeholder, clear button, Esc clears (and drops focus). Returns the new text.
        /// Filter your list on the next Layout event, not immediately, so every event of a frame draws the same rows.
        /// </summary>
        internal static string SearchField(string controlName, string text, string placeholder, PawFocus focus, float height = 30f)
        {
            var r = GUILayoutUtility.GetRect(0f, height, GUILayout.ExpandWidth(true), GUILayout.Height(height));
            var ev = Event.current;
            text = text ?? string.Empty;
            var hasText = text.Length > 0;
            var focused = focus != null && focus.Is(controlName);
            var clear = false;

            if (focused && hasText && PawKeys.IsEscape(ev))
            {
                ev.Use();
                clear = true;
            }

            // The clear button is registered before the text field so it wins the click.
            var clearRect = new Rect(r.xMax - 26f, Mathf.Round(r.center.y - 10f), 20f, 20f);
            if (Click(clearRect, hasText, "Clear search", out var clearHover, out _)) clear = true;

            if (IsRepaint)
            {
                FieldFrame(r, focused, hasText);
                Glyph(new Rect(r.x + 10f, Mathf.Round(r.center.y - 7f), 14f, 14f), PawGlyphs.Search,
                    focused || hasText ? PawTheme.AccentText : PawTheme.TextMuted);
            }

            var field = new Rect(r.x + 32f, r.y, Mathf.Max(0f, r.width - 32f - 30f), r.height);
            GUI.SetNextControlName(controlName);
            var typed = EditorGUI.TextField(field, text, PawTheme.FieldText);

            if (IsRepaint)
            {
                if (!hasText && !focused) GUI.Label(field, placeholder, PawTheme.Label(12, PawTheme.TextMuted));
                if (hasText)
                {
                    if (clearHover) Fill(clearRect, PawTheme.SurfaceHover, 10f);
                    Glyph(Inset(clearRect, 5f), PawGlyphs.Cross, clearHover ? PawTheme.Text : PawTheme.TextMuted);
                }
            }
            if (hasText) Tooltip(clearRect, "Clear the search (Esc)");

            if (clear)
            {
                // Drop focus so the field shows the cleared text instead of its edit buffer.
                GUIUtility.keyboardControl = 0;
                GUI.changed = true;
                return string.Empty;
            }
            return typed;
        }

        // ---- Mini segment & filter chips --------------------------------------------------------------
        /// <summary>Two-part mini segmented control ("All | None"). A half that would change nothing is disabled. Returns 0/1, or -1.</summary>
        internal static int MiniSegment(string a, bool aEnabled, string b, bool bEnabled, string aTooltip = null, string bTooltip = null,
            float width = 96f, float height = 24f)
        {
            var seg = GUILayoutUtility.GetRect(width, height, GUILayout.Width(width), GUILayout.Height(height));
            var half = Mathf.Floor((width - 2f) / 2f);
            var left = new Rect(seg.x, seg.y, half, seg.height);
            var right = new Rect(seg.xMax - half, seg.y, half, seg.height);
            if (IsRepaint)
            {
                Fill(seg, PawTheme.FieldBg, 7f);
                Stroke(seg, PawTheme.Border, 7f);
                Fill(new Rect(seg.x + half + 1f, seg.y + 5f, 1f, seg.height - 10f), PawTheme.Border);
            }
            var result = -1;
            if (SegmentHalf(left, a, aEnabled, aTooltip)) result = 0;
            if (SegmentHalf(right, b, bEnabled, bTooltip)) result = 1;
            return result;
        }

        private static bool SegmentHalf(Rect r, string label, bool enabled, string tooltip)
        {
            var clicked = Click(r, enabled, label, out var hover, out _);
            if (IsRepaint)
            {
                if (hover) Fill(Inset(r, 2f), PawTheme.SurfaceHover, 5f);
                var fg = !enabled ? PawTheme.Alpha(PawTheme.TextMuted, 0.55f) : hover ? PawTheme.Text : PawTheme.TextSecondary;
                GUI.Label(r, label, PawTheme.Label(11, fg, enabled, TextAnchor.MiddleCenter));
            }
            if (enabled) Tooltip(r, tooltip);
            return clicked;
        }

        /// <summary>
        /// Flow-wrapped filter chips ("All 15", "Done 8", ...), each with a colored dot (the gradientIndex chip gets a
        /// gradient dot). Widths only depend on the labels and <paramref name="available"/> (default: card width), so
        /// every event lays out identically. Returns the clicked index or -1 (the active chip is not clickable).
        /// </summary>
        internal static int FilterChips(string[] labels, PawTone[] tones, int active, int gradientIndex = 0, float available = -1f)
        {
            if (available <= 0f) available = CardWidth;
            var x = 0f;
            var clicked = -1;
            EditorGUILayout.BeginHorizontal();
            for (var i = 0; i < labels.Length; i++)
            {
                var label = labels[i];
                var style = PawTheme.Label(11, PawTheme.Text, true);
                var w = Mathf.Ceil(Measure(label, style).x) + 31f;
                if (x > 0f && x + w > available)
                {
                    GUILayout.FlexibleSpace();
                    EditorGUILayout.EndHorizontal();
                    GUILayout.Space(6f);
                    EditorGUILayout.BeginHorizontal();
                    x = 0f;
                }
                if (x > 0f) GUILayout.Space(6f);
                var r = GUILayoutUtility.GetRect(w, 28f, GUILayout.Width(w), GUILayout.Height(28f));
                x += w + 6f;

                var isActive = active == i;
                if (Click(r, !isActive, label, out var hover, out _)) clicked = i;
                if (IsRepaint)
                {
                    var color = i < tones.Length ? PawTheme.Tone(tones[i]) : PawTheme.Accent;
                    if (isActive)
                    {
                        Fill(r, PawTheme.Alpha(color, PawTheme.TintAlpha + 0.04f), 14f);
                        Stroke(r, PawTheme.Alpha(color, 0.75f), 14f, 1.25f);
                    }
                    else
                    {
                        Fill(r, hover ? PawTheme.SurfaceHover : PawTheme.SurfaceRaised, 14f);
                        Stroke(r, PawTheme.Border, 14f);
                    }
                    var dot = new Rect(r.x + 11f, r.center.y - 3.5f, 7f, 7f);
                    if (i == gradientIndex) Gradient(dot, 3.5f);
                    else Fill(dot, color, 3.5f);
                    GUI.Label(new Rect(r.x + 23f, r.y, r.width - 23f, r.height), label,
                        PawTheme.Label(11, isActive || hover ? PawTheme.Text : PawTheme.TextSecondary, true));
                }
            }
            GUILayout.FlexibleSpace();
            EditorGUILayout.EndHorizontal();
            return clicked;
        }
    }
}
