// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
using UnityEditor;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    /// <summary>
    /// Data for PawGUI.NavTile. Keep one instance per tile and refresh its fields every OnGUI (Colors and
    /// Textures change when the skin/theme is rebuilt) - assigning fields allocates nothing.
    /// </summary>
    internal sealed class PawNavTile
    {
        internal Texture Glyph = null;
        internal Color Tint = default;
        /// <summary>Dim first line ("Build outputs").</summary>
        internal string Label = null;
        /// <summary>First line used when Sub doesn't fit next to the value ("Leftovers - can be freed"). Optional.</summary>
        internal string LabelWithSub = null;
        /// <summary>Bold second line ("186.0 MB").</summary>
        internal string Value = null;
        /// <summary>Dim text after the value ("3 builds"). Optional.</summary>
        internal string Sub = null;
        internal Color ValueColor = default;
        internal bool Strong = true;
        /// <summary>Small glyph before the value (e.g. a check for "Clean"). Optional.</summary>
        internal Texture ValueGlyph = null;
        internal string Tooltip = null;
        /// <summary>Inline button text ("Scan") - replaces the chevron. Optional.</summary>
        internal string ButtonText = null;
        internal bool ButtonEnabled = true;
        internal string ButtonTooltip = null;
        /// <summary>Read-only stat tile: no chevron, no hover, not clickable (a value to glance at).</summary>
        internal bool Static = false;
        /// <summary>Opens something outside the window (a URL, a file): an external-link glyph instead of the chevron.</summary>
        internal bool External = false;
    }

    internal static partial class PawGUI
    {
        // ---- Cards ------------------------------------------------------------------------------------
        /// <summary>
        /// Starts a card (vertical group with the card frame). Default padding 16/16/14/16; pass
        /// PawTheme.CompactCardPad / LogCardPad for dense cards. stretch = take the remaining page height (one per page).
        /// </summary>
        internal static Rect BeginCard(GUIStyle pad = null, bool stretch = false)
        {
            var r = stretch
                ? EditorGUILayout.BeginVertical(pad ?? PawTheme.CardPad, GUILayout.ExpandHeight(true))
                : EditorGUILayout.BeginVertical(pad ?? PawTheme.CardPad);
            CardFrame(r);
            return r;
        }

        internal static void EndCard() => EditorGUILayout.EndVertical();

        /// <summary>Icon tile + bold 13px title.</summary>
        internal static void CardHeader(Texture glyph, Color tint, string title)
        {
            BeginCardHeader(glyph, tint, title);
            EndCardHeader();
        }

        /// <summary>Icon tile + title + a dim right-aligned meta text ("Airi Custom - Today, 13:10").</summary>
        internal static void CardHeader(Texture glyph, Color tint, string title, string meta)
        {
            EditorGUILayout.BeginHorizontal();
            IconTile(glyph, tint);
            GUILayout.Space(10f);
            GUILayout.Label(title, PawTheme.Label(13, PawTheme.Text, true), GUILayout.Height(28f));
            var r = GUILayoutUtility.GetRect(10f, 28f, GUILayout.MinWidth(10f), GUILayout.ExpandWidth(true), GUILayout.Height(28f));
            if (IsRepaint && !string.IsNullOrEmpty(meta))
            {
                var style = PawTheme.Label(11, PawTheme.TextSecondary, anchor: TextAnchor.MiddleRight);
                GUI.Label(r, Ellipsize(meta, style, r.width - 8f), style);
            }
            EditorGUILayout.EndHorizontal();
        }

        /// <summary>Icon tile + title + a count chip on the right ("162 NAMES").</summary>
        internal static void CardHeader(Texture glyph, Color tint, string title, string chip, Color chipColor, string chipTooltip = null)
        {
            BeginCardHeader(glyph, tint, title);
            var cw = ChipWidth(chip);
            var r = GUILayoutUtility.GetRect(cw, 28f, GUILayout.Width(cw), GUILayout.Height(28f));
            Chip(new Rect(r.x, r.y + 4f, r.width, 20f), chip, chipColor);
            Tooltip(r, chipTooltip);
            EndCardHeader();
        }

        /// <summary>
        /// Icon tile + title, then a flexible space: add right-side controls (LayoutButton with height 28) and call
        /// EndCardHeader.
        /// </summary>
        internal static void BeginCardHeader(Texture glyph, Color tint, string title)
        {
            EditorGUILayout.BeginHorizontal();
            IconTile(glyph, tint);
            GUILayout.Space(10f);
            GUILayout.Label(title, PawTheme.Label(13, PawTheme.Text, true), GUILayout.Height(28f), GUILayout.MinWidth(40f));
            GUILayout.FlexibleSpace();
        }

        internal static void EndCardHeader() => EditorGUILayout.EndHorizontal();

        /// <summary>
        /// Collapsible card header (the EditorGUILayout.Foldout replacement): icon tile + title + dim meta + chevron, the
        /// whole row toggles. Returns the new open state; draw the body only when open:
        ///   PawGUI.BeginCard(); _open = PawGUI.FoldoutHeader(_open, glyph, tint, "Advanced", "3 options");
        ///   if (_open) { PawGUI.CardText(...); ... } PawGUI.EndCard();
        /// Keep the open flag in a [SerializeField] so it survives domain reloads.
        /// </summary>
        internal static bool FoldoutHeader(bool open, Texture glyph, Color tint, string title, string meta = null, string tooltip = null)
        {
            var r = GUILayoutUtility.GetRect(0f, 28f, GUILayout.ExpandWidth(true), GUILayout.Height(28f));
            var hit = new Rect(r.x - 6f, r.y - 4f, r.width + 12f, r.height + 8f);
            var clicked = Click(hit, true, title, out var hover, out _);
            if (IsRepaint)
            {
                if (hover) Fill(hit, PawTheme.Alpha(PawTheme.SurfaceHover, 0.7f), ControlRadius);
                IconTile(new Rect(r.x, r.y, 28f, 28f), glyph, tint);
                var x = r.x + 38f;
                var chevron = new Rect(r.xMax - 18f, Mathf.Round(r.center.y - 7f), 14f, 14f);
                var titleStyle = PawTheme.Label(13, PawTheme.Text, true);
                var shown = Ellipsize(title, titleStyle, Mathf.Max(0f, chevron.x - 8f - x));
                var tw = Measure(shown, titleStyle).x;
                GUI.Label(new Rect(x, r.y, tw + 2f, r.height), shown, titleStyle);
                if (!string.IsNullOrEmpty(meta))
                {
                    var metaStyle = PawTheme.Label(11, PawTheme.TextSecondary, anchor: TextAnchor.MiddleRight);
                    var mx = x + tw + 12f;
                    var mw = Mathf.Max(0f, chevron.x - 10f - mx);
                    GUI.Label(new Rect(mx, r.y, mw, r.height), Ellipsize(meta, metaStyle, mw), metaStyle);
                }
                Glyph(chevron, open ? PawGlyphs.ChevronDown : PawGlyphs.Chevron, hover ? PawTheme.Text : PawTheme.TextMuted);
            }
            Tooltip(hit, tooltip ?? (open ? "Click to collapse" : "Click to expand"));
            if (!clicked) return open;
            GUI.changed = true;
            return !open;
        }

        /// <summary>
        /// The one headline figure of a card: a 22px bold value with a dim caption on its baseline ("03:12  until the next
        /// save", "186 MB  can be freed"). valueWidth &gt; 0 keeps a ticking value from jittering the caption.
        /// </summary>
        internal static void Metric(string value, string caption, Color color = default, float valueWidth = 0f)
        {
            var valueStyle = PawTheme.Label(22, color.a > 0f ? color : PawTheme.Text, true);
            var w = valueWidth > 0f ? valueWidth : Mathf.Ceil(Measure(value, valueStyle).x) + 2f;
            EditorGUILayout.BeginHorizontal();
            GUILayout.Label(value, valueStyle, GUILayout.Width(w), GUILayout.Height(30f));
            if (!string.IsNullOrEmpty(caption))
            {
                GUILayout.Space(6f);
                var r = GUILayoutUtility.GetRect(20f, 30f, GUILayout.MinWidth(20f), GUILayout.ExpandWidth(true), GUILayout.Height(30f));
                if (IsRepaint)
                {
                    var style = PawTheme.Label(11, PawTheme.TextSecondary);
                    GUI.Label(new Rect(r.x, r.y + 11f, r.width, 16f), Ellipsize(caption, style, r.width), style);
                }
            }
            EditorGUILayout.EndHorizontal();
        }

        /// <summary>11px secondary wrapped text under a header (rich = allow &lt;b&gt;).</summary>
        internal static void CardText(string text, bool rich = false, float spaceAbove = 6f)
        {
            if (spaceAbove > 0f) GUILayout.Space(spaceAbove);
            GUILayout.Label(text, PawTheme.Label(11, PawTheme.TextSecondary, wrap: true, rich: rich));
        }

        /// <summary>11px muted wrapped footnote.</summary>
        internal static void MutedText(string text, float spaceAbove = 6f)
        {
            if (spaceAbove > 0f) GUILayout.Space(spaceAbove);
            GUILayout.Label(text, PawTheme.Label(11, PawTheme.TextMuted, wrap: true));
        }

        /// <summary>Bold 11px muted line between cards ("FOUND 9 LEFTOVERS - 230.3 MB").</summary>
        internal static void SectionLabel(string text)
        {
            GUILayout.Label(text, PawTheme.Label(11, PawTheme.TextMuted, true), GUILayout.Height(16f));
        }

        /// <summary>Glyph + wrapped 11px text (info / warning notes inside cards).</summary>
        internal static void Note(Texture glyph, Color tint, string text)
        {
            EditorGUILayout.BeginHorizontal();
            var icon = GUILayoutUtility.GetRect(14f, 16f, GUILayout.Width(14f), GUILayout.Height(16f));
            Glyph(new Rect(icon.x, icon.y + 1f, 14f, 14f), glyph, tint);
            GUILayout.Space(8f);
            GUILayout.Label(text, PawTheme.Label(11, PawTheme.TextSecondary, wrap: true));
            EditorGUILayout.EndHorizontal();
        }

        /// <summary>Centered halo glyph + title + body - inside a card, when a list is empty or a task is done.</summary>
        internal static void EmptyState(Texture glyph, Color tint, string title, string body)
        {
            GUILayout.Space(14f);
            var r = GUILayoutUtility.GetRect(0f, 68f, GUILayout.ExpandWidth(true), GUILayout.Height(68f));
            if (IsRepaint)
            {
                var c = new Rect(Mathf.Round(r.center.x - 34f), r.y, 68f, 68f);
                Fill(c, PawTheme.Alpha(tint, 0.08f), 34f);
                Fill(Inset(c, 9f), PawTheme.Alpha(tint, 0.14f), 25f);
                Glyph(Inset(c, 22f), glyph, tint);
            }
            GUILayout.Space(12f);
            GUILayout.Label(title, PawTheme.Label(14, PawTheme.Text, true, TextAnchor.MiddleCenter), GUILayout.Height(20f), GUILayout.ExpandWidth(true));
            GUILayout.Space(4f);
            EditorGUILayout.BeginHorizontal();
            GUILayout.Space(12f);
            GUILayout.Label(body, PawTheme.Label(11, PawTheme.TextSecondary, anchor: TextAnchor.UpperCenter, wrap: true));
            GUILayout.Space(12f);
            EditorGUILayout.EndHorizontal();
            GUILayout.Space(6f);
        }

        // ---- Status card ------------------------------------------------------------------------------
        /// <summary>
        /// The glowing status-card frame without the switch, for tools whose state is "ready / not ready" rather than
        /// on/off (a picked asset, a found SDK): glowing brand border at t = 1, amber at t = 0 (pass ActiveT with
        /// IsActive = "ready"). Fill it like a card (CardHeader, CardText, controls), then EndStatusCard().
        /// </summary>
        internal static Rect BeginStatusCard(float t)
        {
            var card = EditorGUILayout.BeginVertical(PawTheme.StatusPad);
            StatusCardFrame(card, t);
            return card;
        }

        internal static void EndStatusCard() => EditorGUILayout.EndVertical();

        /// <summary>
        /// The hero status card: big switch + 16px title + body, glowing brand border when on, amber when off, optional
        /// footnote under a divider. t = animated on-ness (PawWindow.ActiveT). Returns true when clicked (toggle it).
        /// </summary>
        internal static bool StatusCard(float t, string title, string body, string footnote = null, string tooltip = null)
        {
            var card = EditorGUILayout.BeginVertical(PawTheme.StatusPad);
            StatusCardFrame(card, t);

            var row = EditorGUILayout.BeginHorizontal();
            // Reserve the switch column; the switch is drawn centered on the row once its height is known.
            var switchColumn = GUILayoutUtility.GetRect(60f, 32f, GUILayout.Width(60f), GUILayout.Height(32f));
            GUILayout.Space(16f);
            GUILayout.BeginVertical();
            GUILayout.Label(title, PawTheme.Label(16, PawTheme.Text, true), GUILayout.Height(24f));
            GUILayout.Space(3f);
            GUILayout.Label(body, PawTheme.Label(12, PawTheme.TextSecondary, wrap: true));
            GUILayout.EndVertical();
            EditorGUILayout.EndHorizontal();

            var clicked = Click(row, true, title, out var hover, out _);
            Switch(new Rect(switchColumn.x, Mathf.Round(row.center.y - 16f), 60f, 32f), t, hover);
            Tooltip(row, tooltip);

            if (!string.IsNullOrEmpty(footnote))
            {
                GUILayout.Space(16f);
                Divider();
                GUILayout.Space(12f);
                EditorGUILayout.BeginHorizontal();
                var info = GUILayoutUtility.GetRect(16f, 16f, GUILayout.Width(16f), GUILayout.Height(16f));
                Glyph(info, PawGlyphs.Info, PawTheme.TextMuted);
                GUILayout.Space(8f);
                GUILayout.Label(footnote, PawTheme.Label(11, PawTheme.TextSecondary, wrap: true));
                EditorGUILayout.EndHorizontal();
            }
            EditorGUILayout.EndVertical();
            if (clicked) GUI.changed = true;
            return clicked;
        }

        // ---- Radio cards ------------------------------------------------------------------------------
        /// <summary>One selectable option card (radio + bold title + optional chip + description). Returns true when picked.</summary>
        internal static bool RadioCard(string title, string description, bool selected, string chip = null, PawTone chipTone = PawTone.Success)
        {
            var r = EditorGUILayout.BeginVertical(PawTheme.OptionPad);
            var hover = !selected && Hovering(r);
            if (IsRepaint)
            {
                if (selected)
                {
                    Fill(r, PawTheme.Alpha(PawTheme.Accent, PawTheme.IsDark ? 0.12f : 0.07f), TileRadius);
                    Stroke(r, PawTheme.Alpha(PawTheme.Accent, 0.85f), TileRadius, 1.5f);
                }
                else
                {
                    Fill(r, hover ? PawTheme.SurfaceHover : PawTheme.SurfaceRaised, TileRadius);
                    Stroke(r, hover ? PawTheme.BorderStrong : PawTheme.Border, TileRadius);
                }
                Radio(new Rect(r.x + 14f, r.y + 12f, 16f, 16f), selected, hover);
            }

            EditorGUILayout.BeginHorizontal();
            GUILayout.Label(title, PawTheme.Label(12, PawTheme.Text, true), GUILayout.Height(20f));
            if (!string.IsNullOrEmpty(chip))
            {
                GUILayout.Space(8f);
                LayoutChip(chip, PawTheme.Tone(chipTone), 20f);
            }
            GUILayout.FlexibleSpace();
            EditorGUILayout.EndHorizontal();
            if (!string.IsNullOrEmpty(description))
            {
                GUILayout.Space(2f);
                GUILayout.Label(description, PawTheme.Label(11, PawTheme.TextSecondary, wrap: true));
            }
            EditorGUILayout.EndVertical();

            var clicked = Click(r, !selected, title, out _, out _);
            if (clicked) GUI.changed = true;
            return clicked;
        }

        /// <summary>A stack of radio cards (8px apart). Returns the new value; wrap in BeginChangeCheck/EndChangeCheck.</summary>
        internal static int RadioGroup(int value, string[] titles, string[] descriptions, int recommended = -1, string recommendedChip = "RECOMMENDED")
        {
            var chosen = value;
            for (var i = 0; i < titles.Length; i++)
            {
                var description = descriptions != null && i < descriptions.Length ? descriptions[i] : null;
                if (RadioCard(titles[i], description, value == i, i == recommended ? recommendedChip : null)) chosen = i;
                if (i < titles.Length - 1) GUILayout.Space(8f);
            }
            return chosen;
        }

        // ---- Segmented stat bar + legend --------------------------------------------------------------
        /// <summary>
        /// Segmented bar (rounded pills with 2px gaps), e.g. done / skipped / failed. Every non-empty segment gets at
        /// least 8px so a single failure stays visible; the rest is proportional. Returns its rect (for a tooltip).
        /// </summary>
        internal static Rect StatBar(int[] counts, PawTone[] tones, float height = 8f)
        {
            var bar = GUILayoutUtility.GetRect(0f, height, GUILayout.ExpandWidth(true), GUILayout.Height(height));
            if (!IsRepaint) return bar;

            var total = 0;
            var parts = 0;
            for (var i = 0; i < counts.Length; i++)
            {
                total += counts[i];
                if (counts[i] > 0) parts++;
            }
            if (total == 0)
            {
                Fill(bar, PawTheme.Alpha(PawTheme.TextMuted, 0.22f), height / 2f);
                return bar;
            }

            var available = Mathf.Max(0f, bar.width - (parts - 1) * 2f);
            var minW = Mathf.Min(8f, available / parts);
            var free = available - minW * parts;
            var x = bar.x;
            var drawn = 0;
            for (var i = 0; i < counts.Length; i++)
            {
                var count = counts[i];
                if (count == 0) continue;
                drawn++;
                var w = drawn == parts ? bar.xMax - x : Mathf.Round(minW + free * count / total);
                Fill(new Rect(x, bar.y, Mathf.Max(0f, w), bar.height), PawTheme.Tone(tones[i]), Mathf.Min(height / 2f, w / 2f));
                x += w + 2f;
            }
            return bar;
        }

        /// <summary>
        /// "8 done  3 skipped  2 failed" (dot + label, each clickable when its count &gt; 0) and an optional quiet link at
        /// the right ("View log &gt;"), dropped when it doesn't fit. Returns the clicked index, labels.Length for the
        /// link, or -1.
        /// </summary>
        internal static int StatLegend(string[] labels, int[] counts, PawTone[] tones, string linkText = null, string[] tooltips = null,
            string linkTooltip = null)
        {
            var row = GUILayoutUtility.GetRect(0f, 18f, GUILayout.ExpandWidth(true), GUILayout.Height(18f));
            var clicked = -1;
            var x = row.x;
            for (var i = 0; i < labels.Length; i++)
            {
                var count = counts[i];
                var style = PawTheme.Label(11, PawTheme.TextSecondary);
                var w = 13f + Mathf.Ceil(Measure(labels[i], style).x);
                var r = new Rect(x, row.y, w, row.height);
                if (Click(r, count > 0, labels[i], out var hover, out _)) clicked = i;
                if (IsRepaint)
                {
                    var color = PawTheme.Tone(tones[i]);
                    Fill(new Rect(r.x, r.center.y - 3.5f, 7f, 7f), count > 0 ? color : PawTheme.Alpha(color, 0.45f), 3.5f);
                    var fg = count == 0 ? PawTheme.TextMuted : hover ? PawTheme.Text : PawTheme.TextSecondary;
                    GUI.Label(new Rect(r.x + 13f, r.y, w - 12f, r.height), labels[i], PawTheme.Label(11, fg));
                    if (hover) Fill(new Rect(r.x + 13f, Mathf.Round(r.center.y + 7f), w - 13f, 1f), PawTheme.Alpha(PawTheme.Text, 0.6f));
                }
                if (count > 0 && tooltips != null && i < tooltips.Length) Tooltip(r, tooltips[i]);
                x += w + 16f;
            }

            // The link always takes its control ID (a zero rect when it doesn't fit), so IDs never shift.
            if (linkText != null)
            {
                var lw = LinkWidth(linkText);
                var link = new Rect(row.xMax - lw, row.y, lw, row.height);
                var fits = link.x - x >= 8f;
                if (Link(fits ? link : Rect.zero, linkText, fits, linkTooltip)) clicked = labels.Length;
            }
            return clicked;
        }

        // ---- Nav tiles --------------------------------------------------------------------------------
        /// <summary>Splits a layout row into two equal tiles with an 8px gap.</summary>
        internal static void TileRow(out Rect left, out Rect right, float height = 40f)
        {
            var row = GUILayoutUtility.GetRect(0f, height, GUILayout.ExpandWidth(true), GUILayout.Height(height));
            var half = Mathf.Floor((row.width - 8f) / 2f);
            left = new Rect(row.x, row.y, half, row.height);
            right = new Rect(row.xMax - half, row.y, half, row.height);
        }

        /// <summary>
        /// Compact navigation tile: tinted glyph, dim label, bold value + dim sub, chevron (or an inline button). When the
        /// sub doesn't fit next to the value it moves up into the label line (LabelWithSub), so a narrow window never
        /// loses what the number means. Returns Main (tile clicked), Button (inline button clicked) or None.
        /// </summary>
        internal static PawHit NavTile(Rect r, PawNavTile tile)
        {
            var hasButton = !string.IsNullOrEmpty(tile.ButtonText);
            var buttonW = hasButton ? ButtonWidth(tile.ButtonText, null, 12f) : 0f;
            var buttonRect = new Rect(r.xMax - 10f - buttonW, Mathf.Round(r.center.y - 12f), buttonW, 24f);
            // The inline button is registered before its tile so it wins the click; it is drawn on top afterwards.
            var buttonClicked = Click(hasButton ? buttonRect : Rect.zero, hasButton && tile.ButtonEnabled, tile.ButtonText, out var bHover, out var bPressed);
            var clicked = Click(r, !tile.Static, tile.Label ?? tile.Value, out var hover, out var pressed);

            if (IsRepaint)
            {
                Fill(r, hover ? PawTheme.SurfaceHover : PawTheme.SurfaceRaised, TileRadius);
                Stroke(r, hover ? PawTheme.BorderStrong : PawTheme.Border, TileRadius);
                if (pressed) Fill(r, PawTheme.Alpha(PawTheme.ShadowColor, 0.25f), TileRadius);

                var x = r.x + 12f;
                if (r.width >= 190f && tile.Glyph != null)
                {
                    var icon = new Rect(x, Mathf.Round(r.center.y - 12f), 24f, 24f);
                    Fill(icon, PawTheme.Alpha(tile.Tint, PawTheme.TintAlpha), 7f);
                    Glyph(Inset(icon, 5.5f), tile.Glyph, tile.Tint);
                    x = icon.xMax + 10f;
                }

                var textRight = r.xMax - (hasButton ? buttonW + 16f : tile.Static ? 12f : 28f);
                var textW = Mathf.Max(0f, textRight - x);
                var vx = x;
                var valueColor = tile.ValueColor.a > 0f ? tile.ValueColor : PawTheme.Text;
                if (tile.ValueGlyph != null)
                {
                    Glyph(new Rect(vx, r.y + 21f, 13f, 13f), tile.ValueGlyph, valueColor);
                    vx += 17f;
                }
                var valueStyle = tile.Strong ? PawTheme.Label(13, valueColor, true) : PawTheme.Label(12, valueColor);
                var vw = Mathf.Max(0f, textRight - vx);
                var shown = Ellipsize(tile.Value, valueStyle, vw);
                GUI.Label(new Rect(vx, r.y + 18f, vw, 19f), shown, valueStyle);

                var subFits = false;
                if (!string.IsNullOrEmpty(tile.Sub))
                {
                    var subStyle = PawTheme.Label(11, PawTheme.TextMuted);
                    var sx = vx + Measure(shown, valueStyle).x + 6f;
                    var sw = Measure(tile.Sub, subStyle).x;
                    subFits = sx + sw <= textRight;
                    if (subFits) GUI.Label(new Rect(sx, r.y + 19f, sw + 1f, 19f), tile.Sub, subStyle);
                }

                var labelStyle = PawTheme.Label(11, PawTheme.TextMuted);
                var labelText = !string.IsNullOrEmpty(tile.Sub) && !subFits && tile.LabelWithSub != null ? tile.LabelWithSub : tile.Label;
                GUI.Label(new Rect(x, r.y + 4f, textW, 15f), Ellipsize(labelText, labelStyle, textW), labelStyle);

                if (!hasButton && !tile.Static)
                {
                    var trail = tile.External ? PawGlyphs.External : PawGlyphs.Chevron;
                    Glyph(new Rect(r.xMax - 22f, Mathf.Round(r.center.y - 6f), 12f, 12f), trail, hover ? PawTheme.Text : PawTheme.TextMuted);
                }
                else
                {
                    DrawButton(buttonRect, tile.ButtonText, PawButtonKind.Secondary, tile.ButtonEnabled, bHover, bPressed, null);
                }
            }
            if (hasButton) Tooltip(buttonRect, tile.ButtonTooltip);
            Tooltip(r, tile.Tooltip);
            if (buttonClicked) return PawHit.Button;
            return clicked ? PawHit.Main : PawHit.None;
        }

        // ---- Location row -----------------------------------------------------------------------------
        /// <summary>
        /// Read-only path row: folder glyph, dim label, bold root + dim suffix (middle-ellipsized when narrow) and a
        /// framed button ("Show"). Returns true when the button was clicked.
        /// </summary>
        internal static bool LocationRow(string label, string root, string suffix, string tooltip, string buttonText = "Show", bool buttonEnabled = true,
            string buttonTooltip = null)
        {
            EditorGUILayout.BeginHorizontal();
            var loc = GUILayoutUtility.GetRect(60f, 28f, GUILayout.ExpandWidth(true), GUILayout.Height(28f));
            if (IsRepaint)
            {
                Glyph(new Rect(loc.x, Mathf.Round(loc.center.y - 7f), 14f, 14f), PawGlyphs.Folder, PawTheme.TextMuted);
                var labelStyle = PawTheme.Label(11, PawTheme.TextMuted);
                var lw = Mathf.Ceil(Measure(label, labelStyle).x);
                GUI.Label(new Rect(loc.x + 22f, loc.y, lw + 1f, loc.height), label, labelStyle);

                var x = loc.x + 22f + lw + 10f;
                var pw = Mathf.Max(0f, loc.xMax - 4f - x);
                var rootStyle = PawTheme.Label(11, PawTheme.Text, true);
                var suffixStyle = PawTheme.Label(11, PawTheme.TextMuted);
                var rootW = Measure(root, rootStyle).x;
                var suffixW = string.IsNullOrEmpty(suffix) ? 0f : Measure(suffix, suffixStyle).x;
                if (rootW + suffixW <= pw)
                {
                    GUI.Label(new Rect(x, loc.y, rootW + 1f, loc.height), root, rootStyle);
                    if (suffixW > 0f) GUI.Label(new Rect(x + rootW, loc.y, suffixW + 1f, loc.height), suffix, suffixStyle);
                }
                else
                {
                    GUI.Label(new Rect(x, loc.y, pw, loc.height), Ellipsize(root + suffix, rootStyle, pw, true), rootStyle);
                }
            }
            Tooltip(loc, tooltip);
            var clicked = false;
            if (!string.IsNullOrEmpty(buttonText))
            {
                GUILayout.Space(8f);
                clicked = LayoutButton(buttonText, PawButtonKind.Secondary, buttonEnabled, null, 28f, tooltip: buttonTooltip);
            }
            EditorGUILayout.EndHorizontal();
            return clicked;
        }

        // ---- Preview strip ----------------------------------------------------------------------------
        /// <summary>
        /// "SHADER  Poiyomi Toon -> womp womp  [dice]": a raised strip showing a before/after (or source/outcome) pair, with
        /// an optional ghost icon button on the right (reroll; null = none). toColor/toBold style the right side (default:
        /// Accent2Text bold). Returns true when the button was clicked.
        /// </summary>
        internal static bool PreviewStrip(string chip, Color chipColor, string from, string to, Texture buttonGlyph, string tooltip = null,
            string buttonTooltip = null, Color toColor = default, bool toBold = true)
        {
            var r = GUILayoutUtility.GetRect(0f, 42f, GUILayout.ExpandWidth(true), GUILayout.Height(42f));
            var button = new Rect(r.xMax - 36f, r.y + 7f, 28f, 28f);
            var right = buttonGlyph != null ? button.x : r.xMax - 4f;

            if (IsRepaint)
            {
                Fill(r, PawTheme.SurfaceRaised, TileRadius);
                Stroke(r, PawTheme.Border, TileRadius);

                var x = r.x + 12f;
                if (!string.IsNullOrEmpty(chip))
                {
                    var cw = ChipWidth(chip);
                    Chip(new Rect(x, r.center.y - 10f, cw, 20f), chip, chipColor);
                    x += cw + 10f;
                }

                var srcStyle = PawTheme.Label(12, PawTheme.TextSecondary);
                var srcW = Mathf.Min(Measure(from, srcStyle).x, Mathf.Max(0f, (right - x) * 0.45f));
                GUI.Label(new Rect(x, r.y, srcW + 1f, r.height), Ellipsize(from, srcStyle, srcW + 1f), srcStyle);
                x += srcW + 8f;

                GUI.Label(new Rect(x, r.y - 1f, 16f, r.height), "\u2192", PawTheme.Label(13, PawTheme.TextMuted, true));
                x += 22f;

                // The target reads as the outcome: accent + bold by default; pass TextMuted / not bold for a "nothing happens" outcome.
                var toStyle = PawTheme.Label(12, toColor.a > 0f ? toColor : PawTheme.Accent2Text, toBold);
                var tw = Mathf.Max(0f, right - 8f - x);
                GUI.Label(new Rect(x, r.y, tw, r.height), Ellipsize(to, toStyle, tw), toStyle);
            }
            Tooltip(new Rect(r.x, r.y, Mathf.Max(0f, right - 4f - r.x), r.height), tooltip);
            return buttonGlyph != null && IconButton(button, buttonGlyph, buttonTooltip);
        }

        // ---- Apply bar (edit status + Reset / Revert / Apply) -------------------------------------------
        /// <summary>
        /// Footer for an editable card: status dot + "All changes saved" / "Unsaved changes - 3 names", then a quiet
        /// Reset (ghost), Revert (framed, disabled while clean) and Apply (primary, disabled while clean). Wraps to two
        /// rows when narrow. Identical control structure whether dirty or not. Returns 0 none, 1 reset, 2 revert, 3 apply.
        /// </summary>
        internal static int ApplyBar(bool dirty, string dirtyText, string savedText = "All changes saved", string resetText = "Reset to defaults",
            string applyTooltip = "Save (Ctrl+Enter)")
        {
            var narrow = PageWidth < 468f;
            var result = 0;
            var h = narrow ? 20f : 30f;

            EditorGUILayout.BeginHorizontal();
            var dot = GUILayoutUtility.GetRect(8f, h, GUILayout.Width(8f), GUILayout.Height(h));
            GUILayout.Space(8f);
            var status = GUILayoutUtility.GetRect(30f, h, GUILayout.MinWidth(30f), GUILayout.ExpandWidth(true), GUILayout.Height(h));
            if (IsRepaint)
            {
                Fill(new Rect(dot.x, dot.center.y - 4f, 8f, 8f), dirty ? PawTheme.Warning : PawTheme.Success, 4f);
                var statusStyle = PawTheme.Label(11, dirty ? PawTheme.Warning : PawTheme.TextSecondary, dirty);
                GUI.Label(status, Ellipsize(dirty ? dirtyText : savedText, statusStyle, status.width - 4f), statusStyle);
            }
            if (narrow)
            {
                EditorGUILayout.EndHorizontal();
                GUILayout.Space(8f);
                EditorGUILayout.BeginHorizontal();
            }
            else
            {
                GUILayout.Space(8f);
            }
            if (!string.IsNullOrEmpty(resetText) && LayoutButton(resetText, PawButtonKind.Ghost)) result = 1;
            if (narrow) GUILayout.FlexibleSpace();
            else GUILayout.Space(8f);
            if (LayoutButton("Revert", PawButtonKind.Secondary, dirty, tooltip: "Discard unsaved edits")) result = 2;
            GUILayout.Space(4f);
            if (LayoutButton("Apply", PawButtonKind.Primary, dirty, width: 84f, tooltip: applyTooltip)) result = 3;
            EditorGUILayout.EndHorizontal();
            return result;
        }
    }
}
