// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
using System;
using UnityEditor;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    /// <summary>
    /// The branded object field (EditorGUILayout.ObjectField replacement) - a drop slot: drag an asset in, click the
    /// empty slot (or press Enter/Space) to browse with the object picker, click a filled slot to ping it, double-click
    /// to open it, Delete/Backspace or the x to clear it, accent focus ring while focused. Filled: preview thumbnail,
    /// bold name, dim path. Keep one instance per slot (it holds drag and picker state):
    ///   private readonly PawObjectSlot&lt;Material&gt; _slot = new PawObjectSlot&lt;Material&gt;("MyTool.Material")
    ///       { EmptyTitle = "Drop a material here" };
    ///   EditorGUI.BeginChangeCheck();
    ///   var picked = _slot.Draw(_material);
    ///   if (EditorGUI.EndChangeCheck()) { _material = picked; EndGUIPass(); }
    /// Scene objects are refused unless AllowSceneObjects (like ObjectField's allowSceneObjects: false). A Component
    /// type also accepts a dragged GameObject that has one.
    /// </summary>
    internal sealed class PawObjectSlot<T> where T : UnityEngine.Object
    {
        private static readonly int SlotHash = "PawUI.ObjectSlot".GetHashCode();

        /// <summary>Test label (PawTest.Click) and object-picker identity. Unique per window.</summary>
        internal readonly string ControlName;
        internal bool AllowSceneObjects = false;
        internal string EmptyTitle = "Drop an asset here";
        internal string EmptySubtitle = "or click to browse the project";
        internal string EmptyTooltip = "Drop an asset here, or click to browse the project";
        internal string FilledTooltip = "Click to show it in the Project window \u00B7 double-click to open it \u00B7 drop another one to replace it";
        /// <summary>Glyph id of the empty slot. Ids, not textures: this object is usually built in a window field
        /// initializer, where Unity forbids creating textures.</summary>
        internal string EmptyGlyph = "download";
        /// <summary>Glyph id shown when the asset has neither a preview nor an icon.</summary>
        internal string FallbackGlyph = "box";
        /// <summary>Object picker search filter ("t:Material l:MyLabel"). Empty = every T.</summary>
        internal string SearchFilter = string.Empty;
        /// <summary>Extra filter for drops and picks (e.g. only materials with a custom shader). Null = any T.</summary>
        internal Func<T, bool> Accept = null;
        /// <summary>Heights: 64 filled, 84 empty (a bigger drop target).</summary>
        internal float FilledHeight = 64f;
        internal float EmptyHeight = 84f;

        private readonly string _clearLabel;
        private bool _dragHover;
        private bool _browseRequested;
        private T _pickerStart;
        private UnityEngine.Object _cachedFor;
        private int _cachedVersion = -1;
        private string _name = string.Empty;
        private string _path = string.Empty;

        internal PawObjectSlot(string controlName)
        {
            ControlName = controlName;
            _clearLabel = controlName + ".Clear";
        }

        /// <summary>Opens the object picker on the next Draw (a "Browse" button next to the slot). Call it before Draw.</summary>
        internal void Browse() => _browseRequested = true;

        /// <summary>Layout version (full width). Returns the new value; GUI.changed is set when it changes.</summary>
        internal T Draw(T value)
        {
            var h = value != null ? FilledHeight : EmptyHeight;
            var r = GUILayoutUtility.GetRect(0f, h, GUILayout.ExpandWidth(true), GUILayout.Height(h));
            return Draw(r, value);
        }

        internal T Draw(Rect r, T value)
        {
            var has = value != null;
            var clearRect = has ? new Rect(r.xMax - 40f, Mathf.Round(r.center.y - 14f), 28f, 28f) : Rect.zero;
            // The clear button is registered before the slot so it wins the click; it is drawn on top afterwards.
            var clear = PawGUI.Click(clearRect, has, _clearLabel, out var clearHover, out var clearPressed);
            var id = GUIUtility.GetControlID(SlotHash, FocusType.Keyboard, r);
            var e = Event.current;
            var focused = GUIUtility.keyboardControl == id;
            var result = value;
            var openPicker = _browseRequested && Event.current.type != EventType.Layout;
            if (openPicker) _browseRequested = false;

            if (PawTest.Active)
            {
                PawTest.Note(ControlName, r, true);
                if (PawTest.Take(r))
                {
                    // A test click focuses (and pings) - it never opens the picker window.
                    GUIUtility.keyboardControl = id;
                    if (has) EditorGUIUtility.PingObject(value);
                }
            }

            switch (e.GetTypeForControl(id))
            {
                case EventType.MouseDown:
                    if (e.button == 0 && r.Contains(e.mousePosition))
                    {
                        GUIUtility.keyboardControl = id;
                        if (!has)
                        {
                            openPicker = true;
                        }
                        else if (e.clickCount == 2)
                        {
                            e.Use();
                            if (EditorUtility.IsPersistent(value)) AssetDatabase.OpenAsset(value);
                            else Selection.activeObject = value;
                            GUIUtility.ExitGUI();
                        }
                        else
                        {
                            EditorGUIUtility.PingObject(value);
                        }
                        e.Use();
                    }
                    break;
                case EventType.KeyDown:
                    if (focused)
                    {
                        if (has && (e.keyCode == KeyCode.Delete || e.keyCode == KeyCode.Backspace))
                        {
                            result = null;
                            e.Use();
                        }
                        else if (e.keyCode == KeyCode.Return || e.keyCode == KeyCode.KeypadEnter || e.keyCode == KeyCode.Space)
                        {
                            openPicker = true;
                            e.Use();
                        }
                    }
                    break;
                case EventType.DragUpdated:
                case EventType.DragPerform:
                {
                    var dragged = r.Contains(e.mousePosition) ? Dragged() : null;
                    if (_dragHover != (dragged != null))
                    {
                        _dragHover = dragged != null;
                        HandleUtility.Repaint();
                    }
                    if (dragged != null)
                    {
                        DragAndDrop.visualMode = DragAndDropVisualMode.Generic;
                        if (e.type == EventType.DragPerform)
                        {
                            DragAndDrop.AcceptDrag();
                            GUIUtility.keyboardControl = id;
                            _dragHover = false;
                            result = dragged;
                        }
                        e.Use();
                    }
                    break;
                }
                case EventType.DragExited:
                    if (_dragHover)
                    {
                        _dragHover = false;
                        HandleUtility.Repaint();
                    }
                    break;
                case EventType.ExecuteCommand:
                    if (EditorGUIUtility.GetObjectPickerControlID() == id)
                    {
                        if (e.commandName == "ObjectSelectorUpdated")
                        {
                            var picked = EditorGUIUtility.GetObjectPickerObject() as T;
                            if (picked == null || Acceptable(picked)) result = picked;
                            e.Use();
                        }
                        else if (e.commandName == "ObjectSelectorCanceled")
                        {
                            result = _pickerStart;
                            e.Use();
                        }
                    }
                    break;
            }

            if (clear) result = null;
            if (openPicker)
            {
                _pickerStart = value;
                EditorGUIUtility.ShowObjectPicker<T>(value, AllowSceneObjects, SearchFilter, id);
            }

            if (PawGUI.IsRepaint)
            {
                var hover = !_dragHover && !clearHover && PawGUI.Hovering(r);
                const float radius = PawGUI.TileRadius;
                if (focused && !_dragHover) PawGUI.Fill(PawGUI.Inset(r, -3f), PawTheme.Alpha(PawTheme.Accent, 0.18f), radius + 3f);
                if (_dragHover)
                {
                    PawGUI.Fill(r, PawTheme.SurfaceRaised, radius);
                    PawGUI.Fill(r, PawTheme.Alpha(PawTheme.Accent, 0.14f), radius);
                    PawGUI.Stroke(r, PawTheme.Accent, radius, 1.5f);
                }
                else
                {
                    PawGUI.Fill(r, hover ? PawTheme.SurfaceHover : has ? PawTheme.SurfaceRaised : PawTheme.FieldBg, radius);
                    PawGUI.Stroke(r, focused ? PawTheme.Accent : hover ? PawTheme.BorderStrong : PawTheme.Border, radius, focused ? 1.5f : 1f);
                }
                if (has) DrawFilled(r, value, clearRect.x - 8f);
                else DrawEmpty(r);
                if (has) PawGUI.DrawButton(clearRect, string.Empty, PawButtonKind.Ghost, true, clearHover, clearPressed, PawGlyphs.Cross);
            }
            PawGUI.Tooltip(r, has ? FilledTooltip : EmptyTooltip);
            if (has) PawGUI.Tooltip(clearRect, "Clear (Delete)");

            if (result != value)
            {
                GUI.changed = true;
                HandleUtility.Repaint();
            }
            return result;
        }

        private void DrawFilled(Rect r, T value, float right)
        {
            RefreshStrings(value);
            var thumb = new Rect(r.x + 10f, Mathf.Round(r.center.y - 22f), 44f, 44f);
            PawGUI.Fill(thumb, PawTheme.FieldBg, 8f);
            var preview = AssetPreview.GetAssetPreview(value);
            if (preview != null)
            {
                GUI.DrawTexture(thumb, preview, ScaleMode.ScaleAndCrop, true, 0f, Color.white, 0f, 8f);
            }
            else
            {
                if (AssetPreview.IsLoadingAssetPreview(value.GetInstanceID())) HandleUtility.Repaint();
                var icon = AssetPreview.GetMiniThumbnail(value);
                if (icon != null)
                {
                    PawGUI.Fill(thumb, PawTheme.SurfaceHover, 8f);
                    GUI.DrawTexture(PawGUI.Inset(thumb, 12f), icon, ScaleMode.ScaleToFit, true);
                }
                else
                {
                    PawGUI.IconTile(thumb, PawGlyphs.Get(FallbackGlyph ?? "box"), PawTheme.AccentText);
                }
            }

            var x = thumb.xMax + 12f;
            var w = Mathf.Max(0f, right - x);
            var nameStyle = PawTheme.Label(13, PawTheme.Text, true);
            GUI.Label(new Rect(x, Mathf.Round(r.center.y - 20f), w, 20f), PawGUI.Ellipsize(_name, nameStyle, w), nameStyle);
            var pathStyle = PawTheme.Label(11, PawTheme.TextMuted);
            GUI.Label(new Rect(x, Mathf.Round(r.center.y), w, 18f), PawGUI.Ellipsize(_path, pathStyle, w, true), pathStyle);
        }

        private void DrawEmpty(Rect r)
        {
            var titleStyle = PawTheme.Label(12, _dragHover ? PawTheme.AccentText : PawTheme.Text, true);
            var subStyle = PawTheme.Label(11, PawTheme.TextMuted);
            var title = _dragHover ? "Release to use it" : EmptyTitle;
            var textW = Mathf.Ceil(Mathf.Max(PawGUI.Measure(title, titleStyle).x, PawGUI.Measure(EmptySubtitle ?? string.Empty, subStyle).x));
            var groupW = Mathf.Min(r.width - 24f, 36f + 12f + textW);
            var icon = new Rect(Mathf.Round(r.center.x - groupW / 2f), Mathf.Round(r.center.y - 18f), 36f, 36f);
            PawGUI.IconTile(icon, PawGlyphs.Get(EmptyGlyph ?? "download"), PawTheme.AccentText);
            var tx = icon.xMax + 12f;
            var tw = Mathf.Max(0f, r.xMax - 12f - tx);
            var oneLine = string.IsNullOrEmpty(EmptySubtitle);
            GUI.Label(new Rect(tx, oneLine ? r.center.y - 9f : r.center.y - 18f, tw, 18f), PawGUI.Ellipsize(title, titleStyle, tw), titleStyle);
            if (!oneLine) GUI.Label(new Rect(tx, r.center.y + 1f, tw, 17f), PawGUI.Ellipsize(EmptySubtitle, subStyle, tw), subStyle);
        }

        private void RefreshStrings(T value)
        {
            // Object.name and GetAssetPath allocate: only look them up when the object or the project changed.
            if (ReferenceEquals(_cachedFor, value) && _cachedVersion == PawObjectSlotShared.ProjectVersion) return;
            _cachedFor = value;
            _cachedVersion = PawObjectSlotShared.ProjectVersion;
            _name = value.name;
            var path = AssetDatabase.GetAssetPath(value);
            var builtin = string.IsNullOrEmpty(path) ? EditorUtility.IsPersistent(value) : !path.StartsWith("Assets/", StringComparison.Ordinal) &&
                !path.StartsWith("Packages/", StringComparison.Ordinal);
            _path = builtin ? "Built-in asset" : !string.IsNullOrEmpty(path) ? path :
                value is Component || value is GameObject ? "In the open scene" : "Not saved as an asset";
        }

        private bool Acceptable(T candidate) =>
            candidate != null && (AllowSceneObjects || EditorUtility.IsPersistent(candidate)) && (Accept == null || Accept(candidate));

        private T Dragged()
        {
            var refs = DragAndDrop.objectReferences;
            for (var i = 0; i < refs.Length; i++)
            {
                var candidate = refs[i] as T;
                if (candidate == null && refs[i] is GameObject go && typeof(Component).IsAssignableFrom(typeof(T)))
                {
                    candidate = go.GetComponent(typeof(T)) as T;
                }
                if (Acceptable(candidate)) return candidate;
            }
            return null;
        }
    }

    /// <summary>Bumped when the project changes, so object slots refresh cached names and paths (renames, moves).</summary>
    internal static class PawObjectSlotShared
    {
        internal static int ProjectVersion;

        [InitializeOnLoadMethod]
        private static void Hook()
        {
            EditorApplication.projectChanged -= Bump;
            EditorApplication.projectChanged += Bump;
        }

        private static void Bump() => ProjectVersion++;
    }
}
