// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
using UnityEditor;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    /// <summary>
    /// Framed multi-line text editor (a name list, notes, a template): rounded field, accent focus ring, its own
    /// scroll view whose frame is snapped to whole lines (the last visible line is never cut in half), Unity's own
    /// scrollbar for long text, and caret follow (PawCaret) so arrow keys / typing never lose the caret.
    /// Keep one instance per editor (it holds scroll, caret and measurement state) and call Draw every OnGUI.
    /// </summary>
    internal sealed class PawTextArea
    {
        internal readonly string ControlName;
        /// <summary>Never shorter than this.</summary>
        internal float MinHeight;
        /// <summary>Take whatever height the page has left (only one stretchy element per page; its card must stretch too).</summary>
        internal bool Stretch;

        private Vector2 _scroll;
        private int _caret = -1;
        private string _measuredText;
        private float _measuredWidth = -1f;
        private float _measuredHeight;

        internal PawTextArea(string controlName, float minHeight = 172f, bool stretch = true)
        {
            ControlName = controlName;
            MinHeight = minHeight;
            Stretch = stretch;
        }

        internal void ScrollToTop()
        {
            _scroll = Vector2.zero;
            _caret = -1;
        }

        /// <summary>
        /// Draws the editor and returns the (possibly edited) text. <paramref name="submit"/> is true when Ctrl/Cmd+Enter
        /// was pressed while focused (checked before the text area eats the key) - use it for "Apply".
        /// </summary>
        internal string Draw(string text, PawFocus focus, out bool submit)
        {
            text = text ?? string.Empty;
            var ev = Event.current;
            var slot = Stretch
                ? GUILayoutUtility.GetRect(0f, MinHeight, GUILayout.ExpandWidth(true), GUILayout.ExpandHeight(true))
                : GUILayoutUtility.GetRect(0f, MinHeight, GUILayout.ExpandWidth(true), GUILayout.Height(MinHeight));
            var style = PawTheme.TextArea;

            const float clipTop = 4f;
            const float clipBottom = 9f;
            var lineH = Mathf.Max(1f, style.lineHeight);
            var lines = Mathf.Max(1, Mathf.FloorToInt((slot.height - 2f - clipTop - clipBottom - style.padding.top) / lineH + 0.001f));
            var viewH = style.padding.top + lines * lineH;
            var area = new Rect(slot.x, slot.y, slot.width, Mathf.Min(slot.height, 2f + clipTop + viewH + clipBottom));
            var inner = PawGUI.Inset(area, 1f);
            var viewport = new Rect(inner.x, inner.y + clipTop, Mathf.Max(0f, inner.width - 3f), viewH);

            var bar = GUI.skin.verticalScrollbar;
            var barW = bar.fixedWidth + bar.margin.left;
            var textH = TextHeight(text, viewport.width - barW);
            var scrolls = textH > viewport.height;
            if (!scrolls) textH = TextHeight(text, viewport.width);
            var content = new Rect(0f, 0f, Mathf.Max(0f, scrolls ? viewport.width - barW : viewport.width), Mathf.Max(viewport.height, textH));

            var focused = focus != null && focus.Is(ControlName);
            if (PawGUI.IsRepaint)
            {
                PawGUI.Fill(area, PawTheme.Border, PawGUI.TileRadius);
                PawGUI.Fill(inner, PawTheme.FieldBg, PawGUI.TileRadius - 1f);
            }

            _scroll = GUI.BeginScrollView(viewport, _scroll, content, false, false, GUIStyle.none, bar);

            submit = false;
            if (focused && PawKeys.IsSubmit(ev))
            {
                ev.Use();
                submit = true;
            }

            GUI.SetNextControlName(ControlName);
            var edited = EditorGUI.TextArea(content, text, style);
            GUI.EndScrollView();

            // The text area is as tall as its text, so keep the caret inside the viewport when it moves.
            if (ev.type == EventType.Repaint &&
                PawCaret.Follow(ref _scroll, ref _caret, focused, content, style, content.width, viewport.height, content.width, content.height))
            {
                HandleUtility.Repaint();
            }

            if (PawGUI.IsRepaint && focused)
            {
                // Focus ring on top of the frame border (never over the text).
                PawGUI.Stroke(PawGUI.Inset(area, -3f), PawTheme.Alpha(PawTheme.Accent, 0.22f), 13f, 3f);
                PawGUI.Stroke(area, PawTheme.Accent, PawGUI.TileRadius, 1.5f);
            }
            return edited;
        }

        private float TextHeight(string text, float width)
        {
            // Layout passes hand GetRect a dummy rect - don't let that evict the real measurement.
            if (width <= 20f) return 0f;
            if (!ReferenceEquals(text, _measuredText) || Mathf.Abs(width - _measuredWidth) > 0.5f)
            {
                _measuredText = text;
                _measuredWidth = width;
                _measuredHeight = PawTheme.TextArea.CalcHeight(PawGUI.Content(text), width);
            }
            return _measuredHeight;
        }
    }
}
