// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
using System.Collections.Generic;
using System.Reflection;
using UnityEditor;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    /// <summary>
    /// Drives a PawWindow from an interaction test (paw-ui/tools/shoot.py runs the window's static
    /// PawShotTest(EditorWindow window, System.Action&lt;string, bool&gt; check) after the captures).
    ///
    /// Synthetic MouseDown/MouseUp events sent with EditorWindow.SendEvent never reach OnGUI in an unfocused
    /// window, so clicks travel as a command event instead: every PawGUI control built on PawGUI.Click takes the
    /// click when the point lies inside it (smaller controls registered first win, like real clicks). Controls
    /// record their label while PawTest.Active, so tests click by what the user reads:
    ///   PawTest.Click(window, "Textures")      tab, button, chip, tile, link, row title, toggle row, radio card...
    ///   PawTest.ClickAt(window, new Vector2(300, 94))   window content coordinates
    ///   PawTest.Focus(window, "My.Control") + PawTest.Type(window, "abc")   typing into a named text field
    ///   PawTest.Key(window, KeyCode.Delete), PawTest.Drop(window, point, asset), PawTest.Layout(window)
    /// Everything is a no-op cost-wise in normal use (one bool check per control).
    /// </summary>
    internal static class PawTest
    {
        internal const string ClickCommand = "PawUI.TestClick";

        /// <summary>Set by the screenshot harness: controls record label -> rect while true.</summary>
        internal static bool Active = false;

        /// <summary>A control name to focus (EditorGUI.FocusTextInControl) on the window's next OnGUI.</summary>
        internal static string PendingFocus;

        private static bool _pending;
        private static Vector2 _screenPoint;
        private static readonly Dictionary<string, List<Rect>> Seen = new Dictionary<string, List<Rect>>();
        private static readonly Dictionary<string, List<bool>> SeenEnabled = new Dictionary<string, List<bool>>();
        private static MethodInfo _repaintNow;

        // ---- used by the kit's controls (inside OnGUI) --------------------------------------------------
        /// <summary>PawWindow calls this at the start of every OnGUI.</summary>
        internal static void BeginFrame()
        {
            if (!Active) return;
            if (Event.current.type == EventType.Repaint)
            {
                Seen.Clear();
                SeenEnabled.Clear();
            }
            if (PendingFocus != null)
            {
                EditorGUI.FocusTextInControl(PendingFocus);
                PendingFocus = null;
            }
        }

        /// <summary>Records where a labelled control was drawn (Repaint only, screen space).</summary>
        internal static void Note(string label, Rect guiRect, bool enabled)
        {
            if (!Active || string.IsNullOrEmpty(label) || Event.current.type != EventType.Repaint || guiRect.width <= 0f) return;
            if (!Seen.TryGetValue(label, out var list))
            {
                Seen[label] = list = new List<Rect>();
                SeenEnabled[label] = new List<bool>();
            }
            list.Add(GUIUtility.GUIToScreenRect(guiRect));
            SeenEnabled[label].Add(enabled);
        }

        /// <summary>True (and the event is used) when the pending test click lands in guiRect.</summary>
        internal static bool Take(Rect guiRect)
        {
            if (!_pending) return false;
            var e = Event.current;
            if (e.type != EventType.ExecuteCommand || e.commandName != ClickCommand) return false;
            if (!GUIUtility.GUIToScreenRect(guiRect).Contains(_screenPoint)) return false;
            _pending = false;
            e.Use();
            return true;
        }

        // ---- used by tests (outside OnGUI) ---------------------------------------------------------------
        /// <summary>Runs Layout + Repaint on the window now (fills the label registry).</summary>
        internal static void Repaint(EditorWindow window)
        {
            if (_repaintNow == null) _repaintNow = typeof(EditorWindow).GetMethod("RepaintImmediately", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
            _repaintNow?.Invoke(window, null);
        }

        /// <summary>Every label drawn on the last repaint (call Repaint first).</summary>
        internal static IEnumerable<string> Labels => Seen.Keys;

        /// <summary>Is a control with this label on screen (index = which one, top to bottom)?</summary>
        internal static bool Has(EditorWindow window, string label, int index = 0)
        {
            Repaint(window);
            return Seen.TryGetValue(label, out var list) && index < list.Count;
        }

        /// <summary>Is that control enabled?</summary>
        internal static bool IsEnabled(EditorWindow window, string label, int index = 0)
        {
            Repaint(window);
            return SeenEnabled.TryGetValue(label, out var list) && index < list.Count && list[index];
        }

        /// <summary>Clicks the control with this label. False when it isn't on screen, is disabled or nothing took the click.</summary>
        internal static bool Click(EditorWindow window, string label, int index = 0)
        {
            Repaint(window);
            if (!Seen.TryGetValue(label, out var list) || index >= list.Count || !SeenEnabled[label][index]) return false;
            return ClickScreen(window, list[index].center);
        }

        /// <summary>Clicks a point in the window's content coordinates (what the screenshots show).</summary>
        internal static bool ClickAt(EditorWindow window, Vector2 point)
        {
            return ClickScreen(window, window.position.position + point);
        }

        private static bool ClickScreen(EditorWindow window, Vector2 screenPoint)
        {
            _screenPoint = screenPoint;
            _pending = true;
            window.SendEvent(EditorGUIUtility.CommandEvent(ClickCommand));
            var taken = !_pending;
            _pending = false;
            Repaint(window);
            return taken;
        }

        /// <summary>Focuses a named text control (GUI.SetNextControlName) so Type/Key go to it.</summary>
        internal static void Focus(EditorWindow window, string controlName)
        {
            PendingFocus = controlName;
            Repaint(window);
            Repaint(window);
        }

        internal static void Key(EditorWindow window, KeyCode key, EventModifiers modifiers = EventModifiers.None)
        {
            window.SendEvent(new Event { type = EventType.KeyDown, keyCode = key, modifiers = modifiers });
            Repaint(window);
        }

        /// <summary>Types text into the focused text field (one KeyDown per character).</summary>
        internal static void Type(EditorWindow window, string text)
        {
            foreach (var c in text) window.SendEvent(new Event { type = EventType.KeyDown, character = c, keyCode = KeyCode.None });
            Repaint(window);
        }

        /// <summary>Drag-and-drops objects onto a point (window content coordinates).</summary>
        internal static void Drop(EditorWindow window, Vector2 point, params Object[] objects)
        {
            // Drag events travel through the parent dock view, whose coordinates include its tab strip.
            point += ViewOffset(window);
            DragAndDrop.PrepareStartDrag();
            DragAndDrop.objectReferences = objects;
            DragAndDrop.paths = new string[0];
            window.SendEvent(new Event { type = EventType.DragUpdated, mousePosition = point });
            window.SendEvent(new Event { type = EventType.DragPerform, mousePosition = point });
            DragAndDrop.PrepareStartDrag();
            Repaint(window);
        }

        private static Vector2 ViewOffset(EditorWindow window)
        {
            const BindingFlags any = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;
            var parent = typeof(EditorWindow).GetField("m_Parent", any)?.GetValue(window);
            var screen = parent?.GetType().GetProperty("screenPosition", any)?.GetValue(parent);
            return screen is Rect sp ? window.position.position - sp.position : Vector2.zero;
        }

        /// <summary>Screen rect of a labelled control, converted to window content coordinates (for Drop / ClickAt).</summary>
        internal static bool TryGetRect(EditorWindow window, string label, out Rect rect, int index = 0)
        {
            Repaint(window);
            rect = default;
            if (!Seen.TryGetValue(label, out var list) || index >= list.Count) return false;
            var r = list[index];
            rect = new Rect(r.position - window.position.position, r.size);
            return true;
        }

        /// <summary>Sends a Layout event (PawWindow.OnLayout runs: snapshots, filtering).</summary>
        internal static void Layout(EditorWindow window)
        {
            window.SendEvent(new Event { type = EventType.Layout });
        }
    }
}
