// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    /// <summary>Semantic color roles, for static data (filter chips, legends) that can't hold skin-dependent Colors.</summary>
    internal enum PawTone
    {
        Accent, Accent2, AccentText, Accent2Text, Success, Warning, Danger, Muted, Secondary, Text,
        Violet, Pink, Sky, Amber, Slate, Teal,
    }

    /// <summary>
    /// Palette, procedurally generated textures and cached GUIStyles. Everything derives from the active editor
    /// skin (EditorGUIUtility.isProSkin) and the current PawBrand, and is rebuilt when either changes. Textures are
    /// HideAndDontSave and released when the last window using the theme is disabled (close, domain reload).
    /// Call PawTheme.Ensure(brand) at the top of OnGUI (PawWindow does it for you).
    /// </summary>
    internal static class PawTheme
    {
        /// <summary>Bumped on every rebuild - invalidate caches that bake colors into strings (rich text).</summary>
        internal static int Version { get; private set; }

        /// <summary>
        /// Preview-only skin override: 0 = follow the editor skin, 1 = dark, 2 = light. Lets the screenshot harness
        /// capture the light palette WITHOUT touching the user's global editor skin (never switch that).
        /// </summary>
        internal static int PreviewSkin = 0;

        /// <summary>The one place the skin is read; everything else derives from the palette built for it.</summary>
        internal static bool IsDark => PreviewSkin == 0 ? EditorGUIUtility.isProSkin : PreviewSkin == 1;

        internal static PawBrand Brand { get; private set; } = new PawBrand();

        private static bool _built;
        private static bool _builtDark;
        private static PawAccent _builtAccent;
        private static string _builtGlyph;
        private static Func<float, float, bool> _builtShape;
        private static bool _stylesReady;
        private static readonly List<Texture2D> Owned = new List<Texture2D>();
        private static readonly HashSet<object> Users = new HashSet<object>();

        // ---- Palette ---------------------------------------------------------------------------------
        internal static Color WindowBg, Surface, SurfaceRaised, SurfaceHover, SurfaceWarn, FieldBg;
        internal static Color Border, BorderStrong, Divider;
        internal static Color Text, TextSecondary, TextMuted;
        /// <summary>Brand gradient ends (A = left, B = right) and their text-safe tints.</summary>
        internal static Color Accent, Accent2, AccentText, Accent2Text;
        internal static Color Success, Warning, Danger, DangerFill, DangerFillHover;
        internal static Color SwitchOff, ShadowColor;
        /// <summary>Fixed categorical colors (kinds, avatars, groups) - independent of the brand accent.</summary>
        internal static Color TagViolet, TagPink, TagSky, TagAmber, TagSlate, TagTeal;
        /// <summary>Alpha for tinted fills behind colored glyphs/chips (icon tiles, chips).</summary>
        internal static float TintAlpha;

        // ---- Textures (all procedural) -------------------------------------------------------------
        internal static Texture2D GradientTex, BannerTex, BannerOffTex, FadeDownTex, FadeUpTex, TabIcon;

        // ---- Styles -------------------------------------------------------------------------------
        internal static GUIStyle PagePad, PagePadScroll, CardPad, CompactCardPad, StatusPad, OptionPad, LogCardPad, LogRowPad;
        /// <summary>Borderless multi-line text style (the framed text area draws its own rounded field).</summary>
        internal static GUIStyle TextArea;
        /// <summary>Borderless single-line field style (search / text fields draw their own frame).</summary>
        internal static GUIStyle FieldText;
        private static readonly Dictionary<ulong, GUIStyle> TextStyles = new Dictionary<ulong, GUIStyle>();

        /// <summary>The brand glyph as a 128px white mask (logo tile, switch knob).</summary>
        internal static Texture2D BrandGlyph => PawGlyphs.GetLarge(Brand.Glyph);

        /// <summary>The brand glyph tilted for the hero watermark.</summary>
        internal static Texture2D BrandTilted => PawGlyphs.GetTilted(Brand.Glyph);

        // ---- Lifecycle -------------------------------------------------------------------------------
        /// <summary>Register a user (a window) in OnEnable. Textures live while at least one user is registered.</summary>
        internal static void Acquire(object user)
        {
            if (user != null) Users.Add(user);
        }

        /// <summary>Unregister in OnDisable; the last one out destroys every texture (no leaks across domain reloads).</summary>
        internal static void Release(object user)
        {
            Users.Remove(user);
            Users.RemoveWhere(u => u is UnityEngine.Object o && o == null);
            if (Users.Count == 0) ReleaseAll();
        }

        /// <summary>Makes palette, textures and styles current for this brand + skin. Cheap when nothing changed.</summary>
        internal static void Ensure(PawBrand brand)
        {
            EnsureTextures(brand);
            if (!_stylesReady) BuildStyles();
        }

        internal static void EnsureTextures(PawBrand brand)
        {
            if (brand != null) Brand = brand;
            if (Brand.GlyphShape != null && !ReferenceEquals(PawGlyphs.Shape(Brand.Glyph), Brand.GlyphShape)) PawGlyphs.Define(Brand.Glyph, Brand.GlyphShape);
            var dark = IsDark;
            // The shape is compared too: a glyph (re)defined after the theme was built still gets a fresh tab icon.
            if (_built && _builtDark == dark && ReferenceEquals(_builtAccent, Brand.Accent) &&
                string.Equals(_builtGlyph, Brand.Glyph, StringComparison.Ordinal) && ReferenceEquals(_builtShape, PawGlyphs.Shape(Brand.Glyph)) &&
                GradientTex != null && BannerTex != null)
            {
                return;
            }

            ReleaseAll();
            BuildPalette(dark, Brand.Accent ?? PawAccent.Paw);
            BuildTextures(Brand.Accent ?? PawAccent.Paw);
            _built = true;
            _builtDark = dark;
            _builtAccent = Brand.Accent;
            _builtGlyph = Brand.Glyph;
            _builtShape = PawGlyphs.Shape(Brand.Glyph);
            _stylesReady = false;
            TextStyles.Clear();
            Version++;
        }

        /// <summary>Destroys every generated texture (glyph cache included). Safe to call any time.</summary>
        internal static void ReleaseAll()
        {
            foreach (var t in Owned)
            {
                if (t != null) UnityEngine.Object.DestroyImmediate(t);
            }
            Owned.Clear();
            PawGlyphs.ClearCache();
            GradientTex = BannerTex = BannerOffTex = FadeDownTex = FadeUpTex = TabIcon = null;
            _built = false;
            _stylesReady = false;
            TextStyles.Clear();
        }

        /// <summary>Hands a generated texture to the theme so it is destroyed with the rest.</summary>
        internal static void Own(Texture2D tex)
        {
            if (tex != null) Owned.Add(tex);
        }

        // ---- Tones -------------------------------------------------------------------------------------
        internal static Color Tone(PawTone tone)
        {
            switch (tone)
            {
                case PawTone.Accent: return Accent;
                case PawTone.Accent2: return Accent2;
                case PawTone.AccentText: return AccentText;
                case PawTone.Accent2Text: return Accent2Text;
                case PawTone.Success: return Success;
                case PawTone.Warning: return Warning;
                case PawTone.Danger: return Danger;
                case PawTone.Muted: return TextMuted;
                case PawTone.Secondary: return TextSecondary;
                case PawTone.Text: return Text;
                case PawTone.Violet: return TagViolet;
                case PawTone.Pink: return TagPink;
                case PawTone.Sky: return TagSky;
                case PawTone.Amber: return TagAmber;
                case PawTone.Slate: return TagSlate;
                default: return TagTeal;
            }
        }

        /// <summary>A stable categorical color for any string (avatar names, group names...).</summary>
        internal static Color TagFor(string key)
        {
            var hash = 17;
            if (key != null)
            {
                foreach (var c in key) hash = hash * 31 + c;
            }
            switch ((hash & 0x7FFFFFFF) % 5)
            {
                case 0: return TagViolet;
                case 1: return TagPink;
                case 2: return TagSky;
                case 3: return TagTeal;
                default: return TagAmber;
            }
        }

        // ---------------------------------------------------------------------------------------------
        private static void BuildPalette(bool dark, PawAccent accent)
        {
            if (dark)
            {
                WindowBg = Hex(0x1B1A21);
                Surface = Hex(0x25232D);
                SurfaceRaised = Hex(0x2D2A37);
                SurfaceHover = Hex(0x35323F);
                FieldBg = Hex(0x1F1D26);
                Border = Hex(0x36323F);
                BorderStrong = Hex(0x4C4759);
                Divider = Hex(0x2F2C38);
                Text = Hex(0xF1EEF8);
                TextSecondary = Hex(0xB3ADC2);
                TextMuted = Hex(0x857F95);
                Accent = accent.DarkA;
                Accent2 = accent.DarkB;
                AccentText = accent.DarkTextA;
                Accent2Text = accent.DarkTextB;
                Success = Hex(0x34D399);
                Warning = Hex(0xFBBF24);
                Danger = Hex(0xF87171);
                DangerFill = Hex(0xDC3F48);
                DangerFillHover = Hex(0xEA4F58);
                SwitchOff = Hex(0x423E4E);
                ShadowColor = new Color(0f, 0f, 0f, 0.45f);
                TagViolet = Hex(0xA78BFA);
                TagPink = Hex(0xF472B6);
                TagSky = Hex(0x38BDF8);
                TagAmber = Hex(0xFBBF24);
                TagSlate = Hex(0x94A3B8);
                TagTeal = Hex(0x2DD4BF);
                TintAlpha = 0.16f;
            }
            else
            {
                WindowBg = Hex(0xEFEDF4);
                Surface = Hex(0xFFFFFF);
                SurfaceRaised = Hex(0xF7F5FB);
                SurfaceHover = Hex(0xEEEAF6);
                FieldBg = Hex(0xFAF9FD);
                Border = Hex(0xDCD7E6);
                BorderStrong = Hex(0xBDB6CC);
                Divider = Hex(0xECE9F2);
                Text = Hex(0x1D1A27);
                TextSecondary = Hex(0x575168);
                TextMuted = Hex(0x857F96);
                Accent = accent.LightA;
                Accent2 = accent.LightB;
                AccentText = accent.LightTextA;
                Accent2Text = accent.LightTextB;
                Success = Hex(0x047857);
                Warning = Hex(0xB45309);
                Danger = Hex(0xDC2626);
                DangerFill = Hex(0xDC2626);
                DangerFillHover = Hex(0xE53B3B);
                SwitchOff = Hex(0xD3CEDE);
                ShadowColor = new Color(0.16f, 0.11f, 0.26f, 0.12f);
                TagViolet = Hex(0x6D28D9);
                TagPink = Hex(0xBE185D);
                TagSky = Hex(0x0369A1);
                TagAmber = Hex(0xB45309);
                TagSlate = Hex(0x475569);
                TagTeal = Hex(0x0F766E);
                TintAlpha = 0.11f;
            }
            SurfaceWarn = Color.Lerp(Surface, Warning, dark ? 0.07f : 0.06f);
        }

        private static void BuildTextures(PawAccent accent)
        {
            // Brand gradient (stretched horizontally for buttons, pills, the switch track...).
            var g0 = Accent;
            var g1 = Accent2;
            GradientTex = Make(256, 2, false, (x, y) => Color.Lerp(g0, g1, x));

            // Hero banner: deep -> mid -> end, lit from the top-left, darker towards the bottom.
            var b0 = accent.Banner0;
            var b1 = accent.Banner1;
            var b2 = accent.Banner2;
            BannerTex = Make(320, 96, false, (x, y) =>
            {
                var t = Mathf.Clamp01(x * 0.86f + (1f - y) * 0.14f);
                var c = t < 0.5f ? Color.Lerp(b0, b1, t * 2f) : Color.Lerp(b1, b2, (t - 0.5f) * 2f);
                c = Color.Lerp(c, Color.black, (1f - y) * 0.16f);
                var dx = x - 0.12f;
                var dy = (y - 1.05f) * 0.45f;
                var glow = Mathf.Clamp01(1f - Mathf.Sqrt(dx * dx + dy * dy) / 0.55f);
                c = Color.Lerp(c, Color.white, glow * glow * 0.14f);
                c.a = 1f;
                return c;
            });

            // Inactive hero: the same lighting over a cool slate that stays dominant across most of the width, with a
            // soft, desaturated amber glow in the right third - the header stops celebrating while the tool is off,
            // without turning muddy. PawWindow cross-fades the two with the status switch.
            var o0 = Hex(0x302D3C);
            var o1 = Hex(0x3E3A4A);
            var o2 = Hex(0xC08A3E);
            BannerOffTex = Make(320, 96, false, (x, y) =>
            {
                var t = Mathf.Clamp01(x * 0.86f + (1f - y) * 0.14f);
                var c = Color.Lerp(o0, o1, t);
                var ax = (x - 1.04f) / 0.5f;
                var ay = (y - 0.78f) / 1.1f;
                var amber = Mathf.SmoothStep(0f, 1f, Mathf.Clamp01(1f - Mathf.Sqrt(ax * ax + ay * ay)));
                c = Color.Lerp(c, o2, amber * 0.45f);
                c = Color.Lerp(c, Color.black, (1f - y) * 0.16f);
                var dx = x - 0.12f;
                var dy = (y - 1.05f) * 0.45f;
                var glow = Mathf.Clamp01(1f - Mathf.Sqrt(dx * dx + dy * dy) / 0.55f);
                c = Color.Lerp(c, Color.white, glow * glow * 0.1f);
                c.a = 1f;
                return c;
            });

            FadeDownTex = Make(2, 32, false, (x, y) => new Color(1f, 1f, 1f, y * y));
            FadeUpTex = Make(2, 32, false, (x, y) => new Color(1f, 1f, 1f, (1f - y) * (1f - y)));

            // Editor tab icon: the brand glyph filled with the brand gradient.
            var shape = PawGlyphs.Shape(Brand.Glyph) ?? PawShapes.Paw;
            TabIcon = Make(32, 32, false, (x, y) => GradientGlyph(x, y, g0, g1, 32, shape));
        }

        private static void BuildStyles()
        {
            PagePad = Pad(16, 16, 6, 20);
            PagePadScroll = Pad(16, 3, 6, 20);
            CardPad = Pad(16, 16, 14, 16);
            CompactCardPad = Pad(16, 16, 14, 14);
            StatusPad = Pad(18, 18, 18, 16);
            OptionPad = Pad(40, 14, 10, 11);
            LogCardPad = Pad(14, 16, 6, 6);
            LogRowPad = Pad(0, 0, 9, 9);

            // Built from the label style (not EditorStyles.textArea) so no skin background gets painted - the kit
            // draws its own rounded field behind it. Cursor and selection colors come from the skin settings.
            TextArea = new GUIStyle(EditorStyles.label)
            {
                fontSize = 12,
                wordWrap = true,
                richText = false,
                padding = new RectOffset(12, 9, 5, 5),
                margin = new RectOffset(0, 0, 0, 0),
                border = new RectOffset(0, 0, 0, 0),
                overflow = new RectOffset(0, 0, 0, 0),
                clipping = TextClipping.Clip,
                alignment = TextAnchor.UpperLeft,
                stretchWidth = true,
                stretchHeight = true,
            };
            foreach (var s in States(TextArea))
            {
                s.background = null;
                s.scaledBackgrounds = Array.Empty<Texture2D>();
                s.textColor = Text;
            }

            FieldText = new GUIStyle(EditorStyles.label)
            {
                fontSize = 12,
                wordWrap = false,
                richText = false,
                padding = new RectOffset(0, 0, 0, 0),
                margin = new RectOffset(0, 0, 0, 0),
                border = new RectOffset(0, 0, 0, 0),
                overflow = new RectOffset(0, 0, 0, 0),
                clipping = TextClipping.Clip,
                alignment = TextAnchor.MiddleLeft,
                stretchWidth = true,
                stretchHeight = false,
                fixedHeight = 0,
            };
            foreach (var s in States(FieldText))
            {
                s.background = null;
                s.scaledBackgrounds = Array.Empty<Texture2D>();
                s.textColor = Text;
            }

            _stylesReady = true;
        }

        /// <summary>Cached label style - no allocation after the first call per combination.</summary>
        internal static GUIStyle Label(int size, Color color, bool bold = false, TextAnchor anchor = TextAnchor.MiddleLeft,
            bool wrap = false, bool rich = false)
        {
            Color32 c = color;
            var key = ((ulong)c.r << 56) | ((ulong)c.g << 48) | ((ulong)c.b << 40) | ((ulong)c.a << 32) |
                      ((ulong)(size & 0xFF) << 8) | ((ulong)((int)anchor & 0xF) << 4) |
                      (bold ? 1UL : 0UL) | (wrap ? 2UL : 0UL) | (rich ? 4UL : 0UL);
            if (TextStyles.TryGetValue(key, out var style)) return style;

            style = new GUIStyle(EditorStyles.label)
            {
                fontSize = size,
                fontStyle = bold ? FontStyle.Bold : FontStyle.Normal,
                alignment = anchor,
                wordWrap = wrap,
                richText = rich,
                clipping = TextClipping.Clip,
                padding = new RectOffset(0, 0, 0, 0),
                margin = new RectOffset(0, 0, 0, 0),
                stretchWidth = wrap,
                stretchHeight = false,
                fixedHeight = 0,
                fixedWidth = 0,
            };
            foreach (var s in States(style))
            {
                s.background = null;
                s.scaledBackgrounds = Array.Empty<Texture2D>();
                s.textColor = color;
            }
            TextStyles[key] = style;
            return style;
        }

        internal static Color Alpha(Color c, float a)
        {
            c.a *= a;
            return c;
        }

        internal static Color Hex(int rgb) =>
            new Color(((rgb >> 16) & 0xFF) / 255f, ((rgb >> 8) & 0xFF) / 255f, (rgb & 0xFF) / 255f, 1f);

        // ---------------------------------------------------------------------------------------------
        private static GUIStyleState[] States(GUIStyle s) => new[]
        {
            s.normal, s.hover, s.active, s.focused, s.onNormal, s.onHover, s.onActive, s.onFocused,
        };

        private static GUIStyle Pad(int l, int r, int t, int b) => new GUIStyle
        {
            padding = new RectOffset(l, r, t, b),
            margin = new RectOffset(0, 0, 0, 0),
        };

        private static Texture2D Make(int w, int h, bool mips, Func<float, float, Color> shade)
        {
            var tex = new Texture2D(w, h, TextureFormat.RGBA32, mips)
            {
                hideFlags = HideFlags.HideAndDontSave,
                wrapMode = TextureWrapMode.Clamp,
                filterMode = FilterMode.Bilinear,
                name = "PawUI Texture",
            };
            var px = new Color[w * h];
            for (var y = 0; y < h; y++)
            {
                for (var x = 0; x < w; x++)
                {
                    px[y * w + x] = shade(w == 1 ? 0f : x / (float)(w - 1), h == 1 ? 0f : y / (float)(h - 1));
                }
            }
            tex.SetPixels(px);
            tex.Apply(mips, true);
            Owned.Add(tex);
            return tex;
        }

        private static Color GradientGlyph(float x, float y, Color a, Color b, int size, Func<float, float, bool> shape)
        {
            const int ss = 4;
            var hits = 0;
            var step = 1f / (size - 1);
            for (var sy = 0; sy < ss; sy++)
            {
                for (var sx = 0; sx < ss; sx++)
                {
                    if (shape(x + (sx - 1.5f) / ss * step, y + (sy - 1.5f) / ss * step)) hits++;
                }
            }
            var c = Color.Lerp(a, b, x);
            c.a = hits / (float)(ss * ss);
            return c;
        }
    }
}
