// PawUI kit v1.1 - part of the paw-ui style library (generated by paw-ui/tools/scaffold.py).
using System;
using UnityEditor;
using UnityEngine;

namespace AutoSavePro.PawUI
{
    /// <summary>
    /// Base class for a branded tool window: hero banner + floating pill tab bar + a scrolling page per tab (scroll
    /// remembered per tab) + optional sticky footer, with the texture/skin lifecycle handled. Subclass it, give it a
    /// PawBrand, tab labels and DrawPage(tab) - see the starter window.
    ///
    /// Screenshot-harness contract (paw-ui/tools/shoot.py): the harness sets the private fields _tab (int) and _scroll
    /// (Vector2) by reflection between repaints and reads TabCount; keep those names. Optional static members on the
    /// subclass: PawShotSeed(EditorWindow window, string variant) and string[] PawShotVariants.
    ///
    /// Do not declare OnGUI in a subclass (it would hide this one). Override OnEnable/OnDisable/OnFocus and call base.
    /// Visibility: the kit is internal by default, so the window class must be internal too. Scaffold with
    /// --public-window when code in ANOTHER assembly (asmdef) uses the window type; that makes this class and the types
    /// in its protected API (PawBrand, PawFocus, PawTabBadge, PawBannerButton) public.
    /// </summary>
    internal abstract class PawWindow : EditorWindow
    {
        // ---- Screenshot-harness contract: set by reflection between repaints; the window just reacts ----------
        [SerializeField] private int _tab;
        private Vector2 _scroll;

        private Vector2[] _tabScroll = Array.Empty<Vector2>();
        private PawTabBadge[] _badges = Array.Empty<PawTabBadge>();
        private readonly PawTween _activeTween = new PawTween(0.2f);
        private readonly PawFocus _focus = new PawFocus();
        private bool _scrollbarShown;
        private bool _inGUI;
        private float _activeT = 1f;
        private float _contentTop;

        // ================================================================== what a subclass provides
        /// <summary>Name, tagline, accent, glyph, pill words. Return the same static instance every time.</summary>
        protected abstract PawBrand Brand { get; }

        /// <summary>Tab labels (a static array). One entry (or none) hides the tab bar.</summary>
        protected abstract string[] Tabs { get; }

        /// <summary>Draws the page for a tab inside the scroll view (cards separated by GUILayout.Space(PawGUI.CardGap)).</summary>
        protected abstract void DrawPage(int tab);

        /// <summary>Drives the hero: gradient + "on" pill when true, slate/amber + "off" pill when false (animated).</summary>
        protected virtual bool IsActive => true;

        /// <summary>Status pill text; null hides the pill. narrow = window under 390px.</summary>
        protected virtual string PillText(bool active, bool narrow) => active ? Brand.PillOn : narrow ? Brand.PillOffShort : Brand.PillOff;

        protected virtual string PillTooltip(bool active) => active ? Brand.PillOnTooltip : Brand.PillOffTooltip;

        /// <summary>Fill in a badge for a tab (count, danger, unsaved dot). Called every OnGUI - use cached strings (PawGUI.CountText).</summary>
        protected virtual void GetTabBadge(int tab, ref PawTabBadge badge)
        {
        }

        /// <summary>True when the tab shows a sticky footer (e.g. "3 selected [Delete selected]").</summary>
        protected virtual bool HasFooter(int tab) => false;

        protected virtual float FooterHeight => 64f;

        /// <summary>Draws the sticky footer (PawGUI.FooterBar) into rect - outside the scroll view.</summary>
        protected virtual void DrawFooter(int tab, Rect rect)
        {
        }

        /// <summary>Frosted icon buttons in the banner, right to left before the pill. Return a cached array.</summary>
        protected virtual PawBannerButton[] BannerButtons => null;

        /// <summary>Minimum window size (the kit's layout is designed for 380x480 and up; a rebranded window may keep its old minimum).</summary>
        protected virtual Vector2 MinWindowSize => new Vector2(380f, 480f);

        /// <summary>
        /// Called on every Layout event before anything is drawn: take snapshots here (filtered lists, search text) so
        /// every event of the frame draws the same rows.
        /// </summary>
        protected virtual void OnLayout()
        {
        }

        // ================================================================== what a subclass can use
        /// <summary>The current tab (clamped).</summary>
        protected int Tab => Mathf.Clamp(_tab, 0, Mathf.Max(0, TabCount - 1));

        /// <summary>Number of tabs (the screenshot harness reads this).</summary>
        internal int TabCount => Tabs?.Length ?? 0;

        /// <summary>Animated 0..1 "on-ness" for the status card switch (valid inside DrawPage).</summary>
        protected float ActiveT => _activeT;

        /// <summary>Cached focused-control lookup - pass it to PawGUI fields / PawTextArea.</summary>
        protected PawFocus KeyFocus => _focus;

        protected bool ScrollbarShown => _scrollbarShown;

        /// <summary>Main page scroll position (per tab).</summary>
        protected Vector2 Scroll
        {
            get => _scroll;
            set => _scroll = value;
        }

        /// <summary>True while inside OnGUI (actions only ExitGUI then).</summary>
        protected bool InGUI => _inGUI && Event.current != null;

        /// <summary>
        /// Switches tab, remembering each tab's scroll position. Inside OnGUI it drops keyboard focus and ends the GUI
        /// pass (GUIUtility.ExitGUI) - make it the last call of your click handler.
        /// </summary>
        protected void SetTab(int tab)
        {
            var count = TabCount;
            if (tab < 0 || tab >= count) return;
            EnsureTabArrays(count);
            if (_tab == tab)
            {
                Repaint();
                return;
            }
            _tabScroll[Mathf.Clamp(_tab, 0, count - 1)] = _scroll;
            _tab = tab;
            _scroll = _tabScroll[tab];
            if (Event.current != null) GUI.FocusControl(null);
            Repaint();
            if (InGUI) GUIUtility.ExitGUI();
        }

        /// <summary>
        /// Call right after mutating a collection the current GUI pass is drawing (deleting rows, clearing a list): the
        /// rest of this event would otherwise draw a different number of controls than Layout measured.
        /// </summary>
        protected static void EndGUIPass()
        {
            if (Event.current != null) GUIUtility.ExitGUI();
        }

        /// <summary>Toast in the window corner for a completed action ("Deleted 3 items").</summary>
        protected void Notify(string message, double seconds = 2.5)
        {
            ShowNotification(new GUIContent(message), seconds);
        }

        /// <summary>Reports unsaved edits to Unity (asks Save / Discard on close). Override SaveChanges / DiscardChanges.</summary>
        protected void SyncUnsaved(bool dirty, string message)
        {
            if (dirty && saveChangesMessage != message) saveChangesMessage = message;
            if (hasUnsavedChanges != dirty) hasUnsavedChanges = dirty;
        }

        /// <summary>Opens (or focuses) the window of type T. Use from a [MenuItem].</summary>
        protected static T Open<T>() where T : PawWindow
        {
            var window = GetWindow<T>(false, null, true);
            window.minSize = window.MinWindowSize;
            window.UpdateTitle();
            window.Show();
            window.Repaint();
            return window;
        }

        // ================================================================== lifecycle
        protected virtual void OnEnable()
        {
            minSize = MinWindowSize;
            wantsMouseMove = true;
            wantsMouseEnterLeaveWindow = true;
            PawTheme.Acquire(this);
            PawTheme.EnsureTextures(Brand);
            _activeTween.Snap(IsActive);
            UpdateTitle();
        }

        protected virtual void OnDisable()
        {
            PawTheme.Release(this);
        }

        protected virtual void OnFocus()
        {
            Repaint();
        }

        protected void OnGUI()
        {
            var brand = Brand;
            PawTheme.Ensure(brand);
            UpdateTitle();

            var e = Event.current;
            if (PawTest.Active) PawTest.BeginFrame();
            if (e.type == EventType.MouseMove || e.type == EventType.MouseLeaveWindow || e.type == EventType.MouseEnterWindow) Repaint();

            var tabs = Tabs;
            var count = tabs?.Length ?? 0;
            EnsureTabArrays(count);
            if (_tab < 0 || (count > 0 && _tab >= count)) _tab = 0;
            if (e.type == EventType.Layout) OnLayout();

            var w = position.width;
            var h = position.height;
            PawGUI.Fill(new Rect(0, 0, w, h), PawTheme.WindowBg);

            var active = IsActive;
            _activeT = _activeTween.Value(active);
            var buttons = BannerButtons;
            var bannerClick = PawGUI.HeroBanner(w, brand, _activeT, PillText(active, w < 390f), active, PillTooltip(active), buttons, out var bannerRect);

            var tabClick = -1;
            if (count > 1)
            {
                for (var i = 0; i < count; i++)
                {
                    _badges[i] = default;
                    GetTabBadge(i, ref _badges[i]);
                }
                // While inactive the active pill is toned down (~40% toward the surface) so it isn't the loudest thing
                // under the "off" hero.
                tabClick = PawGUI.TabBar(new Rect(PawGUI.Margin, PawGUI.TabBarY, w - PawGUI.Margin * 2f, PawGUI.TabBarHeight), tabs, _tab,
                    0.4f * (1f - _activeT), _badges);
                _contentTop = PawGUI.TabBarY + PawGUI.TabBarHeight + 8f;
            }
            else
            {
                _contentTop = PawGUI.BannerHeight + 12f;
            }

            var tab = Tab;
            var hasFooter = HasFooter(tab);
            var areaHeight = Mathf.Max(0f, h - _contentTop - (hasFooter ? FooterHeight : 0f));
            var bar = GUI.skin.verticalScrollbar;
            PawGUI.PageWidth = w - (_scrollbarShown
                ? PawTheme.PagePadScroll.padding.horizontal + bar.fixedWidth + bar.margin.left
                : PawTheme.PagePad.padding.horizontal);

            Rect page;
            _inGUI = true;
            try
            {
                GUILayout.BeginArea(new Rect(0, _contentTop, w, areaHeight));
                _scroll = GUILayout.BeginScrollView(_scroll, false, false, GUIStyle.none, bar, GUIStyle.none);
                // The page always fills the viewport: when it fits, IMGUI hands the spare height to the one stretchy
                // element (a stretch card / PawTextArea) in the same layout pass - no measuring, no feedback loop.
                page = EditorGUILayout.BeginVertical(_scrollbarShown ? PawTheme.PagePadScroll : PawTheme.PagePad, GUILayout.ExpandHeight(true));
                DrawPage(tab);
                EditorGUILayout.EndVertical();
                GUILayout.EndScrollView();
                GUILayout.EndArea();
            }
            finally
            {
                _inGUI = false;
            }

            if (e.type == EventType.Repaint)
            {
                // The page trades its right padding for the scrollbar, so card edges stay aligned with the tab bar.
                var shown = page.height > areaHeight + 0.5f;
                if (shown != _scrollbarShown)
                {
                    _scrollbarShown = shown;
                    Repaint();
                }
                // Content scrolls away under a soft fade instead of a hard cut below the tab bar.
                if (_scroll.y > 0.5f)
                {
                    GUI.DrawTexture(new Rect(0, _contentTop, w - (_scrollbarShown ? 14f : 0f), 12f), PawTheme.FadeDownTex,
                        ScaleMode.StretchToFill, true, 0f, PawTheme.WindowBg, 0f, 0f);
                }
            }

            if (hasFooter)
            {
                _inGUI = true;
                try
                {
                    DrawFooter(tab, new Rect(0, h - FooterHeight, w, FooterHeight));
                }
                finally
                {
                    _inGUI = false;
                }
            }

            // Last: these may open menus or end the GUI pass.
            if (bannerClick >= 0 && buttons != null) buttons[bannerClick]?.OnClick?.Invoke(bannerRect);
            if (tabClick >= 0)
            {
                _inGUI = true;
                try
                {
                    SetTab(tabClick);
                }
                finally
                {
                    _inGUI = false;
                }
            }
        }

        // ================================================================== internals
        private void EnsureTabArrays(int count)
        {
            if (_tabScroll.Length != count) Array.Resize(ref _tabScroll, count);
            if (_badges.Length != count) Array.Resize(ref _badges, count);
        }

        /// <summary>Tab title + gradient glyph icon; allocates only when something changed.</summary>
        private void UpdateTitle()
        {
            var brand = Brand;
            if (brand == null) return;
            var icon = PawTheme.TabIcon;
            var current = titleContent;
            if (current != null && current.image == icon && current.text == brand.Name && current.tooltip == brand.TitleTooltip) return;
            titleContent = new GUIContent(brand.Name, icon, brand.TitleTooltip);
        }
    }
}
